// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_page.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT id, domain, enterprise_id, actor_type, actor_id, action, resource_type, resource_id, result, details, previous_hash, event_hash, created_at FROM audit_events
WHERE domain = $1::text
  AND ((domain = 'platform' AND enterprise_id IS NULL)
    OR (domain = 'enterprise' AND enterprise_id = $2::uuid))
  AND ($3::text IS NULL OR action = $3::text)
  AND ($4::text IS NULL OR actor_id = $4::text)
  AND ($5::text IS NULL OR resource_type = $5::text)
  AND ($6::text IS NULL OR resource_id = $6::text)
  AND ($7::text IS NULL OR result = $7::text)
  AND ($8::timestamptz IS NULL OR created_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR created_at < $9::timestamptz)
  AND ($10::text IS NULL OR position(lower(btrim($10::text)) IN lower(concat_ws(' ', action, actor_id, resource_type, resource_id, details::text))) > 0)
  AND ($11::timestamptz IS NULL OR (created_at,id) < ($11::timestamptz,$12::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $13::int
`

type ListAuditEventsPageParams struct {
	Domain       string             `json:"domain"`
	EnterpriseID uuid.NullUUID      `json:"enterprise_id"`
	Action       pgtype.Text        `json:"action"`
	ActorID      pgtype.Text        `json:"actor_id"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Result       pgtype.Text        `json:"result"`
	Since        pgtype.Timestamptz `json:"since"`
	Until        pgtype.Timestamptz `json:"until"`
	Search       pgtype.Text        `json:"search"`
	BeforeTime   pgtype.Timestamptz `json:"before_time"`
	BeforeID     uuid.NullUUID      `json:"before_id"`
	PageSize     int32              `json:"page_size"`
}

func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsPage,
		arg.Domain,
		arg.EnterpriseID,
		arg.Action,
		arg.ActorID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.Since,
		arg.Until,
		arg.Search,
		arg.BeforeTime,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.EnterpriseID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.Details,
			&i.PreviousHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
