// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connector_runtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConnectorEpoch = `-- name: AdvanceConnectorEpoch :one
UPDATE connectors SET connection_epoch = connection_epoch + 1, status = 'online', connected_at = now(), last_heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status NOT IN ('uninstalled','revoked') RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type AdvanceConnectorEpochParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) AdvanceConnectorEpoch(ctx context.Context, arg AdvanceConnectorEpochParams) (Connector, error) {
	row := q.db.QueryRow(ctx, advanceConnectorEpoch, arg.ID, arg.EnterpriseID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeConnectorSession = `-- name: CloseConnectorSession :execrows
DELETE FROM connector_sessions WHERE connector_id = $1 AND enterprise_id = $2 AND connection_epoch = $3
`

type CloseConnectorSessionParams struct {
	ConnectorID     uuid.UUID `json:"connector_id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) CloseConnectorSession(ctx context.Context, arg CloseConnectorSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeConnectorSession, arg.ConnectorID, arg.EnterpriseID, arg.ConnectionEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeConnectorCertificateRotation = `-- name: CompleteConnectorCertificateRotation :one
UPDATE connectors SET public_key_hash = $3, certificate_expires_at = $4,
 certificate_rotation_requested_at = NULL, version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status NOT IN ('uninstalled','revoked') RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type CompleteConnectorCertificateRotationParams struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	PublicKeyHash        []byte             `json:"public_key_hash"`
	CertificateExpiresAt pgtype.Timestamptz `json:"certificate_expires_at"`
}

func (q *Queries) CompleteConnectorCertificateRotation(ctx context.Context, arg CompleteConnectorCertificateRotationParams) (Connector, error) {
	row := q.db.QueryRow(ctx, completeConnectorCertificateRotation,
		arg.ID,
		arg.EnterpriseID,
		arg.PublicKeyHash,
		arg.CertificateExpiresAt,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnectorCertificate = `-- name: CreateConnectorCertificate :one
INSERT INTO connector_certificates (id, connector_id, enterprise_id, serial_number, issuer_generation, certificate_request_name, certificate_pem, ca_bundle_pem, not_before, not_after)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, connector_id, enterprise_id, serial_number, issuer_generation, certificate_request_name, certificate_pem, ca_bundle_pem, status, not_before, not_after, revoked_at, created_at
`

type CreateConnectorCertificateParams struct {
	ID                     uuid.UUID          `json:"id"`
	ConnectorID            uuid.UUID          `json:"connector_id"`
	EnterpriseID           uuid.UUID          `json:"enterprise_id"`
	SerialNumber           string             `json:"serial_number"`
	IssuerGeneration       int32              `json:"issuer_generation"`
	CertificateRequestName string             `json:"certificate_request_name"`
	CertificatePem         string             `json:"certificate_pem"`
	CaBundlePem            string             `json:"ca_bundle_pem"`
	NotBefore              pgtype.Timestamptz `json:"not_before"`
	NotAfter               pgtype.Timestamptz `json:"not_after"`
}

func (q *Queries) CreateConnectorCertificate(ctx context.Context, arg CreateConnectorCertificateParams) (ConnectorCertificate, error) {
	row := q.db.QueryRow(ctx, createConnectorCertificate,
		arg.ID,
		arg.ConnectorID,
		arg.EnterpriseID,
		arg.SerialNumber,
		arg.IssuerGeneration,
		arg.CertificateRequestName,
		arg.CertificatePem,
		arg.CaBundlePem,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i ConnectorCertificate
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.EnterpriseID,
		&i.SerialNumber,
		&i.IssuerGeneration,
		&i.CertificateRequestName,
		&i.CertificatePem,
		&i.CaBundlePem,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createConnectorCommand = `-- name: CreateConnectorCommand :one
INSERT INTO connector_commands (id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at
`

type CreateConnectorCommandParams struct {
	ID                   uuid.UUID          `json:"id"`
	CommandID            string             `json:"command_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ConnectorID          uuid.UUID          `json:"connector_id"`
	ConnectionEpoch      int64              `json:"connection_epoch"`
	OperationRef         string             `json:"operation_ref"`
	CredentialLeaseID    uuid.NullUUID      `json:"credential_lease_id"`
	CommandType          string             `json:"command_type"`
	PayloadSchemaVersion string             `json:"payload_schema_version"`
	Payload              []byte             `json:"payload"`
	PayloadHash          []byte             `json:"payload_hash"`
	IdempotencyKey       string             `json:"idempotency_key"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateConnectorCommand(ctx context.Context, arg CreateConnectorCommandParams) (ConnectorCommand, error) {
	row := q.db.QueryRow(ctx, createConnectorCommand,
		arg.ID,
		arg.CommandID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.ConnectionEpoch,
		arg.OperationRef,
		arg.CredentialLeaseID,
		arg.CommandType,
		arg.PayloadSchemaVersion,
		arg.Payload,
		arg.PayloadHash,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i ConnectorCommand
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.ConnectionEpoch,
		&i.OperationRef,
		&i.CredentialLeaseID,
		&i.CommandType,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.PayloadHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultHash,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.AcknowledgedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnectorSessionsForReplacement = `-- name: DeleteConnectorSessionsForReplacement :execrows
DELETE FROM connector_sessions WHERE connector_id = $1 AND enterprise_id = $2
`

type DeleteConnectorSessionsForReplacementParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteConnectorSessionsForReplacement(ctx context.Context, arg DeleteConnectorSessionsForReplacementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectorSessionsForReplacement, arg.ConnectorID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireQueuedConnectorCommands = `-- name: ExpireQueuedConnectorCommands :many
UPDATE connector_commands SET status = 'expired', error_code = 'CONNECTOR_COMMAND_EXPIRED', completed_at = now(), updated_at = now()
WHERE status = 'queued' AND expires_at <= now() RETURNING id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ExpireQueuedConnectorCommands(ctx context.Context) ([]ConnectorCommand, error) {
	rows, err := q.db.Query(ctx, expireQueuedConnectorCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCommand{}
	for rows.Next() {
		var i ConnectorCommand
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.ConnectionEpoch,
			&i.OperationRef,
			&i.CredentialLeaseID,
			&i.CommandType,
			&i.PayloadSchemaVersion,
			&i.Payload,
			&i.PayloadHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultHash,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.AcknowledgedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fenceConnectorForReplacement = `-- name: FenceConnectorForReplacement :execrows
UPDATE connectors SET status = 'revoked', connection_epoch = connection_epoch + 1,
 version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status <> 'revoked'
`

type FenceConnectorForReplacementParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) FenceConnectorForReplacement(ctx context.Context, arg FenceConnectorForReplacementParams) (int64, error) {
	result, err := q.db.Exec(ctx, fenceConnectorForReplacement, arg.ID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeBastionConnectorUninstall = `-- name: FinalizeBastionConnectorUninstall :execrows
UPDATE bastion_scopes SET active_connector_id = NULL, status = 'uninstalled', fencing_generation = fencing_generation + 1,
 resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND active_connector_id = $2 AND status IN ('active','uninstalling','suspected_offline','offline')
`

type FinalizeBastionConnectorUninstallParams struct {
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) FinalizeBastionConnectorUninstall(ctx context.Context, arg FinalizeBastionConnectorUninstallParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeBastionConnectorUninstall, arg.EnterpriseID, arg.ActiveConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeConnectorUninstall = `-- name: FinalizeConnectorUninstall :one
UPDATE connectors SET status = 'uninstalled', version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status IN ('draining','online','suspected_offline','offline')
RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type FinalizeConnectorUninstallParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) FinalizeConnectorUninstall(ctx context.Context, arg FinalizeConnectorUninstallParams) (Connector, error) {
	row := q.db.QueryRow(ctx, finalizeConnectorUninstall, arg.ID, arg.EnterpriseID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeKubernetesConnectorUninstall = `-- name: FinalizeKubernetesConnectorUninstall :execrows
UPDATE kubernetes_clusters SET connector_id = NULL, connection_status = 'disconnected', resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND connector_id = $2 AND status <> 'deleted'
`

type FinalizeKubernetesConnectorUninstallParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) FinalizeKubernetesConnectorUninstall(ctx context.Context, arg FinalizeKubernetesConnectorUninstallParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeKubernetesConnectorUninstall, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveConnectorCertificate = `-- name: GetActiveConnectorCertificate :one
SELECT id, connector_id, enterprise_id, serial_number, issuer_generation, certificate_request_name, certificate_pem, ca_bundle_pem, status, not_before, not_after, revoked_at, created_at FROM connector_certificates
WHERE connector_id = $1 AND enterprise_id = $2 AND status IN ('active','overlap') AND not_after > now()
ORDER BY not_after DESC LIMIT 1
`

type GetActiveConnectorCertificateParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveConnectorCertificate(ctx context.Context, arg GetActiveConnectorCertificateParams) (ConnectorCertificate, error) {
	row := q.db.QueryRow(ctx, getActiveConnectorCertificate, arg.ConnectorID, arg.EnterpriseID)
	var i ConnectorCertificate
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.EnterpriseID,
		&i.SerialNumber,
		&i.IssuerGeneration,
		&i.CertificateRequestName,
		&i.CertificatePem,
		&i.CaBundlePem,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectorCommand = `-- name: GetConnectorCommand :one
SELECT id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at FROM connector_commands WHERE command_id = $1 AND connector_id = $2 AND connection_epoch = $3
`

type GetConnectorCommandParams struct {
	CommandID       string    `json:"command_id"`
	ConnectorID     uuid.UUID `json:"connector_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) GetConnectorCommand(ctx context.Context, arg GetConnectorCommandParams) (ConnectorCommand, error) {
	row := q.db.QueryRow(ctx, getConnectorCommand, arg.CommandID, arg.ConnectorID, arg.ConnectionEpoch)
	var i ConnectorCommand
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.ConnectionEpoch,
		&i.OperationRef,
		&i.CredentialLeaseID,
		&i.CommandType,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.PayloadHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultHash,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.AcknowledgedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorCommandByID = `-- name: GetConnectorCommandByID :one
SELECT id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at FROM connector_commands WHERE id = $1
`

func (q *Queries) GetConnectorCommandByID(ctx context.Context, id uuid.UUID) (ConnectorCommand, error) {
	row := q.db.QueryRow(ctx, getConnectorCommandByID, id)
	var i ConnectorCommand
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.ConnectionEpoch,
		&i.OperationRef,
		&i.CredentialLeaseID,
		&i.CommandType,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.PayloadHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultHash,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.AcknowledgedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorSession = `-- name: GetConnectorSession :one
SELECT connector_id, enterprise_id, gateway_instance_id, connection_epoch, capabilities, connected_at, last_heartbeat_at, draining FROM connector_sessions
WHERE connector_id=$1 AND connection_epoch=$2 AND draining=false
  AND last_heartbeat_at > now() - interval '95 seconds'
`

type GetConnectorSessionParams struct {
	ConnectorID     uuid.UUID `json:"connector_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) GetConnectorSession(ctx context.Context, arg GetConnectorSessionParams) (ConnectorSession, error) {
	row := q.db.QueryRow(ctx, getConnectorSession, arg.ConnectorID, arg.ConnectionEpoch)
	var i ConnectorSession
	err := row.Scan(
		&i.ConnectorID,
		&i.EnterpriseID,
		&i.GatewayInstanceID,
		&i.ConnectionEpoch,
		&i.Capabilities,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Draining,
	)
	return i, err
}

const getLatestConnectorCommandForOperation = `-- name: GetLatestConnectorCommandForOperation :one
SELECT id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at FROM connector_commands WHERE enterprise_id=$1 AND operation_ref=$2 ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestConnectorCommandForOperationParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OperationRef string    `json:"operation_ref"`
}

func (q *Queries) GetLatestConnectorCommandForOperation(ctx context.Context, arg GetLatestConnectorCommandForOperationParams) (ConnectorCommand, error) {
	row := q.db.QueryRow(ctx, getLatestConnectorCommandForOperation, arg.EnterpriseID, arg.OperationRef)
	var i ConnectorCommand
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.ConnectionEpoch,
		&i.OperationRef,
		&i.CredentialLeaseID,
		&i.CommandType,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.PayloadHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultHash,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.AcknowledgedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidConnectorCertificateBySerial = `-- name: GetValidConnectorCertificateBySerial :one
SELECT id, connector_id, enterprise_id, serial_number, issuer_generation, certificate_request_name, certificate_pem, ca_bundle_pem, status, not_before, not_after, revoked_at, created_at FROM connector_certificates
WHERE connector_id = $1 AND enterprise_id = $2 AND serial_number = $3
  AND status IN ('active','overlap') AND not_before <= now() AND not_after > now()
`

type GetValidConnectorCertificateBySerialParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	SerialNumber string    `json:"serial_number"`
}

func (q *Queries) GetValidConnectorCertificateBySerial(ctx context.Context, arg GetValidConnectorCertificateBySerialParams) (ConnectorCertificate, error) {
	row := q.db.QueryRow(ctx, getValidConnectorCertificateBySerial, arg.ConnectorID, arg.EnterpriseID, arg.SerialNumber)
	var i ConnectorCertificate
	err := row.Scan(
		&i.ID,
		&i.ConnectorID,
		&i.EnterpriseID,
		&i.SerialNumber,
		&i.IssuerGeneration,
		&i.CertificateRequestName,
		&i.CertificatePem,
		&i.CaBundlePem,
		&i.Status,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const heartbeatConnectorSession = `-- name: HeartbeatConnectorSession :execrows
UPDATE connector_sessions SET last_heartbeat_at = now()
WHERE connector_id = $1 AND enterprise_id = $2 AND connection_epoch = $3
`

type HeartbeatConnectorSessionParams struct {
	ConnectorID     uuid.UUID `json:"connector_id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) HeartbeatConnectorSession(ctx context.Context, arg HeartbeatConnectorSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatConnectorSession, arg.ConnectorID, arg.EnterpriseID, arg.ConnectionEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDispatchableConnectorCommands = `-- name: ListDispatchableConnectorCommands :many
SELECT command.id, command.command_id, command.enterprise_id, command.connector_id, command.connection_epoch, command.operation_ref, command.credential_lease_id, command.command_type, command.payload_schema_version, command.payload, command.payload_hash, command.idempotency_key, command.status, command.result, command.result_hash, command.error_code, command.expires_at, command.acknowledged_at, command.started_at, command.completed_at, command.created_at, command.updated_at FROM connector_commands command
WHERE command.connector_id = $1 AND command.connection_epoch = $2 AND command.status = 'queued' AND command.expires_at > now()
AND (
  command.command_type <> 'collector_management' OR
  command.payload->>'transport' = 'direct' OR
  EXISTS (
    SELECT 1 FROM telemetry_tunnels tunnel
    WHERE tunnel.enterprise_id = command.enterprise_id
      AND tunnel.collector_id = (command.payload->>'collector_id')::uuid
      AND tunnel.transport = command.payload->>'transport'
      AND tunnel.status = 'established'
  )
)
AND (
  command.command_type <> 'collector_management' OR
  command.payload->>'route_kind' <> 'bastion_gateway' OR
  EXISTS (
    SELECT 1 FROM collector_instances gateway
    WHERE gateway.enterprise_id = command.enterprise_id
      AND gateway.id = (command.payload->>'gateway_collector_id')::uuid
      AND gateway.role = 'edge_gateway'
      AND gateway.status = 'converged'
  )
)
ORDER BY command.created_at LIMIT $3 FOR UPDATE SKIP LOCKED
`

type ListDispatchableConnectorCommandsParams struct {
	ConnectorID     uuid.UUID `json:"connector_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
	Limit           int32     `json:"limit"`
}

func (q *Queries) ListDispatchableConnectorCommands(ctx context.Context, arg ListDispatchableConnectorCommandsParams) ([]ConnectorCommand, error) {
	rows, err := q.db.Query(ctx, listDispatchableConnectorCommands, arg.ConnectorID, arg.ConnectionEpoch, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCommand{}
	for rows.Next() {
		var i ConnectorCommand
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.ConnectionEpoch,
			&i.OperationRef,
			&i.CredentialLeaseID,
			&i.CommandType,
			&i.PayloadSchemaVersion,
			&i.Payload,
			&i.PayloadHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultHash,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.AcknowledgedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncertainConnectorCommands = `-- name: ListUncertainConnectorCommands :many
SELECT id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at FROM connector_commands WHERE connector_id = $1 AND status IN ('delivery_unknown','result_unknown')
ORDER BY created_at LIMIT $2
`

type ListUncertainConnectorCommandsParams struct {
	ConnectorID uuid.UUID `json:"connector_id"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListUncertainConnectorCommands(ctx context.Context, arg ListUncertainConnectorCommandsParams) ([]ConnectorCommand, error) {
	rows, err := q.db.Query(ctx, listUncertainConnectorCommands, arg.ConnectorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCommand{}
	for rows.Next() {
		var i ConnectorCommand
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.ConnectionEpoch,
			&i.OperationRef,
			&i.CredentialLeaseID,
			&i.CommandType,
			&i.PayloadSchemaVersion,
			&i.Payload,
			&i.PayloadHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultHash,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.AcknowledgedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBastionScopeConnectorSuspectedOffline = `-- name: MarkBastionScopeConnectorSuspectedOffline :execrows
UPDATE bastion_scopes SET status = 'suspected_offline',relay_status='degraded', updated_at = now()
WHERE enterprise_id = $1 AND active_connector_id = $2 AND status = 'active'
`

type MarkBastionScopeConnectorSuspectedOfflineParams struct {
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) MarkBastionScopeConnectorSuspectedOffline(ctx context.Context, arg MarkBastionScopeConnectorSuspectedOfflineParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBastionScopeConnectorSuspectedOffline, arg.EnterpriseID, arg.ActiveConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markBastionScopeUninstalling = `-- name: MarkBastionScopeUninstalling :execrows
UPDATE bastion_scopes SET status = 'uninstalling', resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND active_connector_id = $2 AND status = 'active'
`

type MarkBastionScopeUninstallingParams struct {
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) MarkBastionScopeUninstalling(ctx context.Context, arg MarkBastionScopeUninstallingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBastionScopeUninstalling, arg.EnterpriseID, arg.ActiveConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConnectorCertificatesOverlap = `-- name: MarkConnectorCertificatesOverlap :exec
UPDATE connector_certificates
SET status = 'overlap', not_after = LEAST(not_after, now() + interval '15 minutes')
WHERE connector_id = $1 AND enterprise_id = $2 AND status = 'active'
`

type MarkConnectorCertificatesOverlapParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkConnectorCertificatesOverlap(ctx context.Context, arg MarkConnectorCertificatesOverlapParams) error {
	_, err := q.db.Exec(ctx, markConnectorCertificatesOverlap, arg.ConnectorID, arg.EnterpriseID)
	return err
}

const markConnectorDisconnected = `-- name: MarkConnectorDisconnected :execrows
UPDATE connectors SET status = 'suspected_offline', updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND connection_epoch = $3 AND status IN ('online','draining')
`

type MarkConnectorDisconnectedParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) MarkConnectorDisconnected(ctx context.Context, arg MarkConnectorDisconnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markConnectorDisconnected, arg.ID, arg.EnterpriseID, arg.ConnectionEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markKubernetesConnectorUninstalling = `-- name: MarkKubernetesConnectorUninstalling :execrows
UPDATE kubernetes_clusters SET connection_status = 'degraded', resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND connector_id = $2 AND status <> 'deleted'
`

type MarkKubernetesConnectorUninstallingParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) MarkKubernetesConnectorUninstalling(ctx context.Context, arg MarkKubernetesConnectorUninstallingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markKubernetesConnectorUninstalling, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleBastionScopesOffline = `-- name: MarkStaleBastionScopesOffline :execrows
UPDATE bastion_scopes AS scope SET status = 'offline', relay_status='offline', updated_at = now()
WHERE scope.status = 'suspected_offline' AND EXISTS (
  SELECT 1 FROM connectors AS connector
  WHERE connector.id = scope.active_connector_id AND connector.enterprise_id = scope.enterprise_id AND connector.status = 'offline'
)
`

func (q *Queries) MarkStaleBastionScopesOffline(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleBastionScopesOffline)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markStaleConnectorsOffline = `-- name: MarkStaleConnectorsOffline :execrows
UPDATE connectors SET status = 'offline', updated_at = now()
WHERE status = 'suspected_offline' AND last_heartbeat_at < now() - interval '5 minutes'
`

func (q *Queries) MarkStaleConnectorsOffline(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markStaleConnectorsOffline)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestConnectorCertificateRotation = `-- name: RequestConnectorCertificateRotation :one
UPDATE connectors SET certificate_rotation_requested_at = now(), version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3
  AND status NOT IN ('uninstalled','revoked') RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type RequestConnectorCertificateRotationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) RequestConnectorCertificateRotation(ctx context.Context, arg RequestConnectorCertificateRotationParams) (Connector, error) {
	row := q.db.QueryRow(ctx, requestConnectorCertificateRotation, arg.ID, arg.EnterpriseID, arg.Version)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeConnectorCertificates = `-- name: RevokeConnectorCertificates :exec
UPDATE connector_certificates SET status = 'revoked', revoked_at = now()
WHERE connector_id = $1 AND enterprise_id = $2 AND status IN ('active','overlap')
`

type RevokeConnectorCertificatesParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeConnectorCertificates(ctx context.Context, arg RevokeConnectorCertificatesParams) error {
	_, err := q.db.Exec(ctx, revokeConnectorCertificates, arg.ConnectorID, arg.EnterpriseID)
	return err
}

const startConnectorUninstall = `-- name: StartConnectorUninstall :one
UPDATE connectors SET status = 'draining', version = version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND version = $3 AND connection_epoch = $4 AND status = 'online'
RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type StartConnectorUninstallParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	Version         int64     `json:"version"`
	ConnectionEpoch int64     `json:"connection_epoch"`
}

func (q *Queries) StartConnectorUninstall(ctx context.Context, arg StartConnectorUninstallParams) (Connector, error) {
	row := q.db.QueryRow(ctx, startConnectorUninstall,
		arg.ID,
		arg.EnterpriseID,
		arg.Version,
		arg.ConnectionEpoch,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const timeoutActiveConnectorCommands = `-- name: TimeoutActiveConnectorCommands :many
UPDATE connector_commands SET status = 'timed_out', error_code = 'CONNECTOR_COMMAND_TIMED_OUT', completed_at = now(), updated_at = now()
WHERE status IN ('dispatched','acknowledged','running') AND expires_at <= now() RETURNING id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) TimeoutActiveConnectorCommands(ctx context.Context) ([]ConnectorCommand, error) {
	rows, err := q.db.Query(ctx, timeoutActiveConnectorCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCommand{}
	for rows.Next() {
		var i ConnectorCommand
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.ConnectionEpoch,
			&i.OperationRef,
			&i.CredentialLeaseID,
			&i.CommandType,
			&i.PayloadSchemaVersion,
			&i.Payload,
			&i.PayloadHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultHash,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.AcknowledgedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionConnectorCommand = `-- name: TransitionConnectorCommand :one
UPDATE connector_commands SET status = $4, result = COALESCE($5, result), result_hash = COALESCE($6, result_hash),
 error_code = COALESCE($7, error_code), updated_at = now(),
 acknowledged_at = CASE WHEN $4 = 'acknowledged' THEN now() ELSE acknowledged_at END,
 started_at = CASE WHEN $4 = 'running' THEN now() ELSE started_at END,
 completed_at = CASE WHEN $4 IN ('succeeded','failed','timed_out','expired') THEN now() ELSE completed_at END
WHERE command_id = $1 AND connector_id = $2 AND connection_epoch = $3
  AND status = $8 RETURNING id, command_id, enterprise_id, connector_id, connection_epoch, operation_ref, credential_lease_id, command_type, payload_schema_version, payload, payload_hash, idempotency_key, status, result, result_hash, error_code, expires_at, acknowledged_at, started_at, completed_at, created_at, updated_at
`

type TransitionConnectorCommandParams struct {
	CommandID       string      `json:"command_id"`
	ConnectorID     uuid.UUID   `json:"connector_id"`
	ConnectionEpoch int64       `json:"connection_epoch"`
	Status          string      `json:"status"`
	Result          []byte      `json:"result"`
	ResultHash      []byte      `json:"result_hash"`
	ErrorCode       pgtype.Text `json:"error_code"`
	ExpectedStatus  string      `json:"expected_status"`
}

func (q *Queries) TransitionConnectorCommand(ctx context.Context, arg TransitionConnectorCommandParams) (ConnectorCommand, error) {
	row := q.db.QueryRow(ctx, transitionConnectorCommand,
		arg.CommandID,
		arg.ConnectorID,
		arg.ConnectionEpoch,
		arg.Status,
		arg.Result,
		arg.ResultHash,
		arg.ErrorCode,
		arg.ExpectedStatus,
	)
	var i ConnectorCommand
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.ConnectionEpoch,
		&i.OperationRef,
		&i.CredentialLeaseID,
		&i.CommandType,
		&i.PayloadSchemaVersion,
		&i.Payload,
		&i.PayloadHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultHash,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.AcknowledgedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectorSession = `-- name: UpsertConnectorSession :one
INSERT INTO connector_sessions (connector_id, enterprise_id, gateway_instance_id, connection_epoch, capabilities, connected_at, last_heartbeat_at)
VALUES ($1,$2,$3,$4,$5,now(),now())
ON CONFLICT (connector_id) DO UPDATE SET gateway_instance_id = EXCLUDED.gateway_instance_id, connection_epoch = EXCLUDED.connection_epoch,
 capabilities = EXCLUDED.capabilities, connected_at = now(), last_heartbeat_at = now(), draining = false
RETURNING connector_id, enterprise_id, gateway_instance_id, connection_epoch, capabilities, connected_at, last_heartbeat_at, draining
`

type UpsertConnectorSessionParams struct {
	ConnectorID       uuid.UUID `json:"connector_id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	GatewayInstanceID string    `json:"gateway_instance_id"`
	ConnectionEpoch   int64     `json:"connection_epoch"`
	Capabilities      []string  `json:"capabilities"`
}

func (q *Queries) UpsertConnectorSession(ctx context.Context, arg UpsertConnectorSessionParams) (ConnectorSession, error) {
	row := q.db.QueryRow(ctx, upsertConnectorSession,
		arg.ConnectorID,
		arg.EnterpriseID,
		arg.GatewayInstanceID,
		arg.ConnectionEpoch,
		arg.Capabilities,
	)
	var i ConnectorSession
	err := row.Scan(
		&i.ConnectorID,
		&i.EnterpriseID,
		&i.GatewayInstanceID,
		&i.ConnectionEpoch,
		&i.Capabilities,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Draining,
	)
	return i, err
}
