// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connectors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateBastionConnector = `-- name: ActivateBastionConnector :one
UPDATE bastion_scopes SET connector_host_id = $3, active_connector_id = $4, status = 'active', relay_status='pending', resource_version = resource_version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type ActivateBastionConnectorParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorHostID   uuid.NullUUID `json:"connector_host_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) ActivateBastionConnector(ctx context.Context, arg ActivateBastionConnectorParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, activateBastionConnector,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorHostID,
		arg.ActiveConnectorID,
	)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const activateKubernetesConnector = `-- name: ActivateKubernetesConnector :one
UPDATE kubernetes_clusters SET connector_id = $3, connection_status = 'connected', resource_version = resource_version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 RETURNING id, enterprise_id, name, api_server, connection_mode, bastion_scope_id, connector_id, credential_id, default_namespace, environment, labels, labels_hash, labels_version, resource_version, connection_status, kubernetes_version, node_count, ready_node_count, status, deleted_at, created_at, updated_at
`

type ActivateKubernetesConnectorParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) ActivateKubernetesConnector(ctx context.Context, arg ActivateKubernetesConnectorParams) (KubernetesCluster, error) {
	row := q.db.QueryRow(ctx, activateKubernetesConnector, arg.ID, arg.EnterpriseID, arg.ConnectorID)
	var i KubernetesCluster
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.ApiServer,
		&i.ConnectionMode,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.CredentialID,
		&i.DefaultNamespace,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.ReadyNodeCount,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const attachBastionRootHost = `-- name: AttachBastionRootHost :one
UPDATE bastion_scopes SET connector_host_id = $3, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND status = 'pending' AND connector_host_id IS NULL
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type AttachBastionRootHostParams struct {
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	ConnectorHostID uuid.NullUUID `json:"connector_host_id"`
}

// Creation is one transaction: link the preallocated root Host before the
// newly created Scope can become externally visible.
func (q *Queries) AttachBastionRootHost(ctx context.Context, arg AttachBastionRootHostParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, attachBastionRootHost, arg.ID, arg.EnterpriseID, arg.ConnectorHostID)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const bastionNameAvailable = `-- name: BastionNameAvailable :one
SELECT NOT EXISTS (
  SELECT 1 FROM bastion_scopes AS scope
  WHERE scope.enterprise_id = $1
    AND lower(scope.name) = lower($2) AND scope.status <> 'deleted'
) AND NOT EXISTS (
  SELECT 1 FROM hosts AS host
  WHERE host.enterprise_id = $1
    AND lower(host.name) = lower($2) AND host.status <> 'deleted'
) AS available
`

type BastionNameAvailableParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
}

// A Bastion Scope and its Bastion Host share the user-visible
// name. Both live-name namespaces must therefore be free before preview.
func (q *Queries) BastionNameAvailable(ctx context.Context, arg BastionNameAvailableParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, bastionNameAvailable, arg.EnterpriseID, arg.Name)
	var available pgtype.Bool
	err := row.Scan(&available)
	return available, err
}

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :one
UPDATE connector_enrollment_tokens SET status = 'consumed', consumed_at = now(), consumed_device_hash = $2, registered_connector_id = $3
WHERE id = $1 AND status = 'active' AND expires_at > now() RETURNING id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id
`

type ConsumeEnrollmentTokenParams struct {
	ID                    uuid.UUID     `json:"id"`
	ConsumedDeviceHash    []byte        `json:"consumed_device_hash"`
	RegisteredConnectorID uuid.NullUUID `json:"registered_connector_id"`
}

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (ConnectorEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentToken, arg.ID, arg.ConsumedDeviceHash, arg.RegisteredConnectorID)
	var i ConnectorEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.PreallocatedConnectorID,
		&i.EnterpriseID,
		&i.Role,
		&i.Purpose,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.PreallocatedHostID,
		&i.TokenHash,
		&i.Policy,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedDeviceHash,
		&i.RegisteredConnectorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ReleaseVersionID,
	)
	return i, err
}

const createBastionScope = `-- name: CreateBastionScope :one
INSERT INTO bastion_scopes (id, enterprise_id, name, environment, labels, labels_hash, onboarding_mode)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type CreateBastionScopeParams struct {
	ID             uuid.UUID `json:"id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	Name           string    `json:"name"`
	Environment    string    `json:"environment"`
	Labels         []byte    `json:"labels"`
	LabelsHash     []byte    `json:"labels_hash"`
	OnboardingMode string    `json:"onboarding_mode"`
}

func (q *Queries) CreateBastionScope(ctx context.Context, arg CreateBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, createBastionScope,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Environment,
		arg.Labels,
		arg.LabelsHash,
		arg.OnboardingMode,
	)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const createConnector = `-- name: CreateConnector :one
INSERT INTO connectors (id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, certificate_expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at
`

type CreateConnectorParams struct {
	ID                    uuid.UUID          `json:"id"`
	EnterpriseID          uuid.UUID          `json:"enterprise_id"`
	Role                  string             `json:"role"`
	Name                  string             `json:"name"`
	HostID                uuid.NullUUID      `json:"host_id"`
	BastionScopeID        uuid.NullUUID      `json:"bastion_scope_id"`
	KubernetesClusterID   uuid.NullUUID      `json:"kubernetes_cluster_id"`
	InstanceID            string             `json:"instance_id"`
	DeviceFingerprintHash []byte             `json:"device_fingerprint_hash"`
	PublicKeyHash         []byte             `json:"public_key_hash"`
	SoftwareVersion       string             `json:"software_version"`
	Capabilities          []string           `json:"capabilities"`
	CertificateExpiresAt  pgtype.Timestamptz `json:"certificate_expires_at"`
}

func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, createConnector,
		arg.ID,
		arg.EnterpriseID,
		arg.Role,
		arg.Name,
		arg.HostID,
		arg.BastionScopeID,
		arg.KubernetesClusterID,
		arg.InstanceID,
		arg.DeviceFingerprintHash,
		arg.PublicKeyHash,
		arg.SoftwareVersion,
		arg.Capabilities,
		arg.CertificateExpiresAt,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnectorEnrollmentToken = `-- name: CreateConnectorEnrollmentToken :one
INSERT INTO connector_enrollment_tokens (id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, expires_at, created_by, release_version_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id
`

type CreateConnectorEnrollmentTokenParams struct {
	ID                      uuid.UUID          `json:"id"`
	PreallocatedConnectorID uuid.UUID          `json:"preallocated_connector_id"`
	EnterpriseID            uuid.UUID          `json:"enterprise_id"`
	Role                    string             `json:"role"`
	Purpose                 string             `json:"purpose"`
	BastionScopeID          uuid.NullUUID      `json:"bastion_scope_id"`
	KubernetesClusterID     uuid.NullUUID      `json:"kubernetes_cluster_id"`
	PreallocatedHostID      uuid.NullUUID      `json:"preallocated_host_id"`
	TokenHash               []byte             `json:"token_hash"`
	Policy                  []byte             `json:"policy"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	CreatedBy               uuid.UUID          `json:"created_by"`
	ReleaseVersionID        uuid.NullUUID      `json:"release_version_id"`
}

func (q *Queries) CreateConnectorEnrollmentToken(ctx context.Context, arg CreateConnectorEnrollmentTokenParams) (ConnectorEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createConnectorEnrollmentToken,
		arg.ID,
		arg.PreallocatedConnectorID,
		arg.EnterpriseID,
		arg.Role,
		arg.Purpose,
		arg.BastionScopeID,
		arg.KubernetesClusterID,
		arg.PreallocatedHostID,
		arg.TokenHash,
		arg.Policy,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.ReleaseVersionID,
	)
	var i ConnectorEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.PreallocatedConnectorID,
		&i.EnterpriseID,
		&i.Role,
		&i.Purpose,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.PreallocatedHostID,
		&i.TokenHash,
		&i.Policy,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedDeviceHash,
		&i.RegisteredConnectorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ReleaseVersionID,
	)
	return i, err
}

const deleteBastionScope = `-- name: DeleteBastionScope :one
UPDATE bastion_scopes AS scope SET status = 'deleted', deleted_at = now(), resource_version = scope.resource_version + 1, updated_at = now()
WHERE scope.id = $1 AND scope.enterprise_id = $2 AND scope.resource_version = $3
AND scope.status IN ('uninstalled','pending')
AND NOT EXISTS (SELECT 1 FROM hosts AS host WHERE host.bastion_scope_id = scope.id AND host.role = 'managed_host' AND host.status <> 'deleted')
AND NOT EXISTS (SELECT 1 FROM hosts AS host WHERE host.bastion_scope_id = scope.id AND host.role = 'bastion' AND host.status <> 'deleted')
AND NOT EXISTS (
  SELECT 1 FROM connector_commands AS command
  JOIN connectors AS connector ON connector.id = command.connector_id AND connector.enterprise_id = command.enterprise_id
  WHERE connector.bastion_scope_id = scope.id
    AND command.status IN ('queued','dispatched','acknowledged','running','delivery_unknown','result_unknown')
)
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type DeleteBastionScopeParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) DeleteBastionScope(ctx context.Context, arg DeleteBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, deleteBastionScope, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const deleteUnregisteredBastionRootHost = `-- name: DeleteUnregisteredBastionRootHost :one
UPDATE hosts SET status='deleted',connection_status='offline',deleted_at=now(),resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND bastion_scope_id=$3 AND role='bastion' AND status='active' AND connector_id IS NULL
RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type DeleteUnregisteredBastionRootHostParams struct {
	ID             uuid.UUID     `json:"id"`
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	BastionScopeID uuid.NullUUID `json:"bastion_scope_id"`
}

func (q *Queries) DeleteUnregisteredBastionRootHost(ctx context.Context, arg DeleteUnregisteredBastionRootHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, deleteUnregisteredBastionRootHost, arg.ID, arg.EnterpriseID, arg.BastionScopeID)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const deleteUnregisteredManagedHost = `-- name: DeleteUnregisteredManagedHost :one
UPDATE hosts SET status='deleted',connection_status='offline',deleted_at=now(),resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND role='managed_host' AND status='active' AND connector_id IS NULL
RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type DeleteUnregisteredManagedHostParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) DeleteUnregisteredManagedHost(ctx context.Context, arg DeleteUnregisteredManagedHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, deleteUnregisteredManagedHost, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const fenceBastionScope = `-- name: FenceBastionScope :one
UPDATE bastion_scopes SET fencing_generation = fencing_generation + 1, active_connector_id = NULL, status = 'offline', resource_version = resource_version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND resource_version = $3 AND status IN ('active','offline','uninstalled','suspected_offline') RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type FenceBastionScopeParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) FenceBastionScope(ctx context.Context, arg FenceBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, fenceBastionScope, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const getBastionScope = `-- name: GetBastionScope :one
SELECT s.id, s.enterprise_id, s.name, s.environment, s.labels, s.labels_hash, s.status, s.connector_host_id, s.active_connector_id, s.fencing_generation, s.resource_version, s.deleted_at, s.created_at, s.updated_at, s.onboarding_mode, s.relay_address, s.relay_https_port, s.relay_gateway_port, s.relay_port_generation, s.relay_status, s.relay_error_code, s.removal_generation, s.local_cleanup,
  COALESCE((SELECT tunnel.status::text FROM connector_control_tunnels AS tunnel
   WHERE tunnel.bastion_scope_id = s.id
   ORDER BY tunnel.epoch DESC, tunnel.updated_at DESC LIMIT 1), ''::text)::text AS control_tunnel_status,
  (SELECT count(*) FROM hosts h WHERE h.bastion_scope_id = s.id AND h.role = 'managed_host' AND h.status <> 'deleted')::bigint AS member_count
  ,(SELECT operation.id FROM host_removal_operations operation
    WHERE operation.enterprise_id=s.enterprise_id AND operation.bastion_scope_id=s.id AND operation.target_type='bastion_scope'
      AND operation.removal_generation=s.removal_generation
      AND s.status IN ('draining','uninstalling','removal_failed','cleanup_unknown','uninstalled')
      AND ((s.active_connector_id IS NOT NULL AND operation.connector_id=s.active_connector_id)
        OR (s.active_connector_id IS NULL AND s.status='uninstalled' AND EXISTS (
          SELECT 1 FROM hosts root WHERE root.id=s.connector_host_id AND root.enterprise_id=s.enterprise_id
            AND root.role='bastion' AND root.status='uninstalled' AND root.removal_generation=s.removal_generation
            AND root.connector_id=operation.connector_id)))
    ORDER BY operation.created_at DESC,operation.id DESC LIMIT 1) AS removal_operation_id
FROM bastion_scopes s WHERE s.id = $1 AND s.enterprise_id = $2 AND s.status <> 'deleted'
`

type GetBastionScopeParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type GetBastionScopeRow struct {
	ID                  uuid.UUID          `json:"id"`
	EnterpriseID        uuid.UUID          `json:"enterprise_id"`
	Name                string             `json:"name"`
	Environment         string             `json:"environment"`
	Labels              []byte             `json:"labels"`
	LabelsHash          []byte             `json:"labels_hash"`
	Status              string             `json:"status"`
	ConnectorHostID     uuid.NullUUID      `json:"connector_host_id"`
	ActiveConnectorID   uuid.NullUUID      `json:"active_connector_id"`
	FencingGeneration   int64              `json:"fencing_generation"`
	ResourceVersion     int64              `json:"resource_version"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OnboardingMode      string             `json:"onboarding_mode"`
	RelayAddress        string             `json:"relay_address"`
	RelayHttpsPort      int32              `json:"relay_https_port"`
	RelayGatewayPort    int32              `json:"relay_gateway_port"`
	RelayPortGeneration int64              `json:"relay_port_generation"`
	RelayStatus         string             `json:"relay_status"`
	RelayErrorCode      string             `json:"relay_error_code"`
	RemovalGeneration   int64              `json:"removal_generation"`
	LocalCleanup        string             `json:"local_cleanup"`
	ControlTunnelStatus string             `json:"control_tunnel_status"`
	MemberCount         int64              `json:"member_count"`
	RemovalOperationID  uuid.UUID          `json:"removal_operation_id"`
}

func (q *Queries) GetBastionScope(ctx context.Context, arg GetBastionScopeParams) (GetBastionScopeRow, error) {
	row := q.db.QueryRow(ctx, getBastionScope, arg.ID, arg.EnterpriseID)
	var i GetBastionScopeRow
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
		&i.ControlTunnelStatus,
		&i.MemberCount,
		&i.RemovalOperationID,
	)
	return i, err
}

const getConnector = `-- name: GetConnector :one
SELECT id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at FROM connectors WHERE id = $1 AND enterprise_id = $2
`

type GetConnectorParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.ID, arg.EnterpriseID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorByID = `-- name: GetConnectorByID :one
SELECT id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at FROM connectors WHERE id = $1
`

func (q *Queries) GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByID, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorByInstance = `-- name: GetConnectorByInstance :one
SELECT id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at FROM connectors WHERE enterprise_id = $1 AND instance_id = $2
`

type GetConnectorByInstanceParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	InstanceID   string    `json:"instance_id"`
}

func (q *Queries) GetConnectorByInstance(ctx context.Context, arg GetConnectorByInstanceParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByInstance, arg.EnterpriseID, arg.InstanceID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
SELECT id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id FROM connector_enrollment_tokens WHERE token_hash = $1
`

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash []byte) (ConnectorEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByHash, tokenHash)
	var i ConnectorEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.PreallocatedConnectorID,
		&i.EnterpriseID,
		&i.Role,
		&i.Purpose,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.PreallocatedHostID,
		&i.TokenHash,
		&i.Policy,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedDeviceHash,
		&i.RegisteredConnectorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ReleaseVersionID,
	)
	return i, err
}

const getEnrollmentTokenForUpdate = `-- name: GetEnrollmentTokenForUpdate :one
SELECT id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id FROM connector_enrollment_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetEnrollmentTokenForUpdate(ctx context.Context, tokenHash []byte) (ConnectorEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenForUpdate, tokenHash)
	var i ConnectorEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.PreallocatedConnectorID,
		&i.EnterpriseID,
		&i.Role,
		&i.Purpose,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.PreallocatedHostID,
		&i.TokenHash,
		&i.Policy,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedDeviceHash,
		&i.RegisteredConnectorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ReleaseVersionID,
	)
	return i, err
}

const getLiveConnectorByInstanceForUpdate = `-- name: GetLiveConnectorByInstanceForUpdate :one
SELECT id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at FROM connectors
WHERE enterprise_id=$1 AND instance_id=$2 AND status NOT IN ('revoked','uninstalled')
ORDER BY created_at DESC,id DESC LIMIT 1 FOR UPDATE
`

type GetLiveConnectorByInstanceForUpdateParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	InstanceID   string    `json:"instance_id"`
}

func (q *Queries) GetLiveConnectorByInstanceForUpdate(ctx context.Context, arg GetLiveConnectorByInstanceForUpdateParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getLiveConnectorByInstanceForUpdate, arg.EnterpriseID, arg.InstanceID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Role,
		&i.Name,
		&i.HostID,
		&i.BastionScopeID,
		&i.KubernetesClusterID,
		&i.InstanceID,
		&i.DeviceFingerprintHash,
		&i.PublicKeyHash,
		&i.SoftwareVersion,
		&i.Capabilities,
		&i.Status,
		&i.ConnectionEpoch,
		&i.CertificateExpiresAt,
		&i.CertificateRotationRequestedAt,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBastionScopes = `-- name: ListBastionScopes :many
SELECT s.id, s.enterprise_id, s.name, s.environment, s.labels, s.labels_hash, s.status, s.connector_host_id, s.active_connector_id, s.fencing_generation, s.resource_version, s.deleted_at, s.created_at, s.updated_at, s.onboarding_mode, s.relay_address, s.relay_https_port, s.relay_gateway_port, s.relay_port_generation, s.relay_status, s.relay_error_code, s.removal_generation, s.local_cleanup,
  COALESCE((SELECT tunnel.status::text FROM connector_control_tunnels AS tunnel
   WHERE tunnel.bastion_scope_id = s.id
   ORDER BY tunnel.epoch DESC, tunnel.updated_at DESC LIMIT 1), ''::text)::text AS control_tunnel_status,
  (SELECT count(*) FROM hosts h WHERE h.bastion_scope_id = s.id AND h.role = 'managed_host' AND h.status <> 'deleted')::bigint AS member_count
  ,(SELECT operation.id FROM host_removal_operations operation
    WHERE operation.enterprise_id=s.enterprise_id AND operation.bastion_scope_id=s.id AND operation.target_type='bastion_scope'
      AND operation.removal_generation=s.removal_generation
      AND s.status IN ('draining','uninstalling','removal_failed','cleanup_unknown','uninstalled')
      AND ((s.active_connector_id IS NOT NULL AND operation.connector_id=s.active_connector_id)
        OR (s.active_connector_id IS NULL AND s.status='uninstalled' AND EXISTS (
          SELECT 1 FROM hosts root WHERE root.id=s.connector_host_id AND root.enterprise_id=s.enterprise_id
            AND root.role='bastion' AND root.status='uninstalled' AND root.removal_generation=s.removal_generation
            AND root.connector_id=operation.connector_id)))
    ORDER BY operation.created_at DESC,operation.id DESC LIMIT 1) AS removal_operation_id
FROM bastion_scopes s WHERE s.enterprise_id = $1 AND s.status <> 'deleted' ORDER BY s.created_at, s.id
`

type ListBastionScopesRow struct {
	ID                  uuid.UUID          `json:"id"`
	EnterpriseID        uuid.UUID          `json:"enterprise_id"`
	Name                string             `json:"name"`
	Environment         string             `json:"environment"`
	Labels              []byte             `json:"labels"`
	LabelsHash          []byte             `json:"labels_hash"`
	Status              string             `json:"status"`
	ConnectorHostID     uuid.NullUUID      `json:"connector_host_id"`
	ActiveConnectorID   uuid.NullUUID      `json:"active_connector_id"`
	FencingGeneration   int64              `json:"fencing_generation"`
	ResourceVersion     int64              `json:"resource_version"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	OnboardingMode      string             `json:"onboarding_mode"`
	RelayAddress        string             `json:"relay_address"`
	RelayHttpsPort      int32              `json:"relay_https_port"`
	RelayGatewayPort    int32              `json:"relay_gateway_port"`
	RelayPortGeneration int64              `json:"relay_port_generation"`
	RelayStatus         string             `json:"relay_status"`
	RelayErrorCode      string             `json:"relay_error_code"`
	RemovalGeneration   int64              `json:"removal_generation"`
	LocalCleanup        string             `json:"local_cleanup"`
	ControlTunnelStatus string             `json:"control_tunnel_status"`
	MemberCount         int64              `json:"member_count"`
	RemovalOperationID  uuid.UUID          `json:"removal_operation_id"`
}

func (q *Queries) ListBastionScopes(ctx context.Context, enterpriseID uuid.UUID) ([]ListBastionScopesRow, error) {
	rows, err := q.db.Query(ctx, listBastionScopes, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBastionScopesRow{}
	for rows.Next() {
		var i ListBastionScopesRow
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Environment,
			&i.Labels,
			&i.LabelsHash,
			&i.Status,
			&i.ConnectorHostID,
			&i.ActiveConnectorID,
			&i.FencingGeneration,
			&i.ResourceVersion,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnboardingMode,
			&i.RelayAddress,
			&i.RelayHttpsPort,
			&i.RelayGatewayPort,
			&i.RelayPortGeneration,
			&i.RelayStatus,
			&i.RelayErrorCode,
			&i.RemovalGeneration,
			&i.LocalCleanup,
			&i.ControlTunnelStatus,
			&i.MemberCount,
			&i.RemovalOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, enterprise_id, role, name, host_id, bastion_scope_id, kubernetes_cluster_id, instance_id, device_fingerprint_hash, public_key_hash, software_version, capabilities, status, connection_epoch, certificate_expires_at, certificate_rotation_requested_at, connected_at, last_heartbeat_at, version, created_at, updated_at FROM connectors WHERE enterprise_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListConnectors(ctx context.Context, enterpriseID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectors, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Role,
			&i.Name,
			&i.HostID,
			&i.BastionScopeID,
			&i.KubernetesClusterID,
			&i.InstanceID,
			&i.DeviceFingerprintHash,
			&i.PublicKeyHash,
			&i.SoftwareVersion,
			&i.Capabilities,
			&i.Status,
			&i.ConnectionEpoch,
			&i.CertificateExpiresAt,
			&i.CertificateRotationRequestedAt,
			&i.ConnectedAt,
			&i.LastHeartbeatAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBastionEnrollmentTokensForCancellation = `-- name: LockBastionEnrollmentTokensForCancellation :many
SELECT id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id FROM connector_enrollment_tokens
WHERE enterprise_id=$1 AND bastion_scope_id=$2 ORDER BY created_at,id FOR UPDATE
`

type LockBastionEnrollmentTokensForCancellationParams struct {
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	BastionScopeID uuid.NullUUID `json:"bastion_scope_id"`
}

func (q *Queries) LockBastionEnrollmentTokensForCancellation(ctx context.Context, arg LockBastionEnrollmentTokensForCancellationParams) ([]ConnectorEnrollmentToken, error) {
	rows, err := q.db.Query(ctx, lockBastionEnrollmentTokensForCancellation, arg.EnterpriseID, arg.BastionScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorEnrollmentToken{}
	for rows.Next() {
		var i ConnectorEnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.PreallocatedConnectorID,
			&i.EnterpriseID,
			&i.Role,
			&i.Purpose,
			&i.BastionScopeID,
			&i.KubernetesClusterID,
			&i.PreallocatedHostID,
			&i.TokenHash,
			&i.Policy,
			&i.Status,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ConsumedDeviceHash,
			&i.RegisteredConnectorID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ReleaseVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHostEnrollmentTokensForCancellation = `-- name: LockHostEnrollmentTokensForCancellation :many
SELECT id, preallocated_connector_id, enterprise_id, role, purpose, bastion_scope_id, kubernetes_cluster_id, preallocated_host_id, token_hash, policy, status, expires_at, consumed_at, consumed_device_hash, registered_connector_id, created_by, created_at, release_version_id FROM connector_enrollment_tokens
WHERE enterprise_id=$1 AND preallocated_host_id=$2 ORDER BY created_at,id FOR UPDATE
`

type LockHostEnrollmentTokensForCancellationParams struct {
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	PreallocatedHostID uuid.NullUUID `json:"preallocated_host_id"`
}

func (q *Queries) LockHostEnrollmentTokensForCancellation(ctx context.Context, arg LockHostEnrollmentTokensForCancellationParams) ([]ConnectorEnrollmentToken, error) {
	rows, err := q.db.Query(ctx, lockHostEnrollmentTokensForCancellation, arg.EnterpriseID, arg.PreallocatedHostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorEnrollmentToken{}
	for rows.Next() {
		var i ConnectorEnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.PreallocatedConnectorID,
			&i.EnterpriseID,
			&i.Role,
			&i.Purpose,
			&i.BastionScopeID,
			&i.KubernetesClusterID,
			&i.PreallocatedHostID,
			&i.TokenHash,
			&i.Policy,
			&i.Status,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.ConsumedDeviceHash,
			&i.RegisteredConnectorID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ReleaseVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBastionConnectorOfflineForTakeover = `-- name: MarkBastionConnectorOfflineForTakeover :execrows
UPDATE bastion_scopes SET status='offline',relay_status='offline',updated_at=now()
WHERE enterprise_id=$1 AND active_connector_id=$2
  AND status IN ('active','suspected_offline','offline')
`

type MarkBastionConnectorOfflineForTakeoverParams struct {
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) MarkBastionConnectorOfflineForTakeover(ctx context.Context, arg MarkBastionConnectorOfflineForTakeoverParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBastionConnectorOfflineForTakeover, arg.EnterpriseID, arg.ActiveConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markHostConnectorOffline = `-- name: MarkHostConnectorOffline :execrows
UPDATE hosts SET connection_status='offline',updated_at=now()
WHERE enterprise_id=$1 AND connector_id=$2 AND status IN ('active','disabled','draining','uninstalling')
`

type MarkHostConnectorOfflineParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) MarkHostConnectorOffline(ctx context.Context, arg MarkHostConnectorOfflineParams) (int64, error) {
	result, err := q.db.Exec(ctx, markHostConnectorOffline, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreBastionConnectorOnline = `-- name: RestoreBastionConnectorOnline :execrows
UPDATE bastion_scopes SET status = 'active', resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND active_connector_id = $2 AND status IN ('suspected_offline','offline')
`

type RestoreBastionConnectorOnlineParams struct {
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) RestoreBastionConnectorOnline(ctx context.Context, arg RestoreBastionConnectorOnlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreBastionConnectorOnline, arg.EnterpriseID, arg.ActiveConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreHostConnectorOnline = `-- name: RestoreHostConnectorOnline :execrows
UPDATE hosts SET connection_status='online',last_seen_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND connector_id=$2 AND status IN ('active','disabled')
`

type RestoreHostConnectorOnlineParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) RestoreHostConnectorOnline(ctx context.Context, arg RestoreHostConnectorOnlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreHostConnectorOnline, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreKubernetesConnectorOnline = `-- name: RestoreKubernetesConnectorOnline :execrows
UPDATE kubernetes_clusters SET connection_status = 'connected', resource_version = resource_version + 1, updated_at = now()
WHERE enterprise_id = $1 AND connector_id = $2 AND status <> 'deleted' AND connection_status IN ('degraded','disconnected')
`

type RestoreKubernetesConnectorOnlineParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ConnectorID  uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) RestoreKubernetesConnectorOnline(ctx context.Context, arg RestoreKubernetesConnectorOnlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreKubernetesConnectorOnline, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeActiveEnrollmentTokens = `-- name: RevokeActiveEnrollmentTokens :exec
UPDATE connector_enrollment_tokens SET status = 'revoked'
WHERE enterprise_id = $1 AND status = 'active' AND (bastion_scope_id = $2 OR kubernetes_cluster_id = $2)
`

type RevokeActiveEnrollmentTokensParams struct {
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	BastionScopeID uuid.NullUUID `json:"bastion_scope_id"`
}

func (q *Queries) RevokeActiveEnrollmentTokens(ctx context.Context, arg RevokeActiveEnrollmentTokensParams) error {
	_, err := q.db.Exec(ctx, revokeActiveEnrollmentTokens, arg.EnterpriseID, arg.BastionScopeID)
	return err
}

const revokeActiveHostEnrollmentTokens = `-- name: RevokeActiveHostEnrollmentTokens :execrows
UPDATE connector_enrollment_tokens SET status='revoked'
WHERE enterprise_id=$1 AND preallocated_host_id=$2 AND status='active'
`

type RevokeActiveHostEnrollmentTokensParams struct {
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	PreallocatedHostID uuid.NullUUID `json:"preallocated_host_id"`
}

func (q *Queries) RevokeActiveHostEnrollmentTokens(ctx context.Context, arg RevokeActiveHostEnrollmentTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveHostEnrollmentTokens, arg.EnterpriseID, arg.PreallocatedHostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBastionRelayStatus = `-- name: SetBastionRelayStatus :execrows
UPDATE bastion_scopes SET relay_status=$1, relay_error_code=$2,
 relay_address=CASE WHEN $3::text<>'' THEN $3 ELSE relay_address END,
 relay_https_port=CASE WHEN $4::bigint>0 THEN $5 ELSE relay_https_port END,
 relay_gateway_port=CASE WHEN $4::bigint>0 THEN $6 ELSE relay_gateway_port END,
 relay_port_generation=CASE WHEN $4::bigint>0 THEN $4 ELSE relay_port_generation END,
 updated_at=now()
WHERE enterprise_id=$7 AND active_connector_id=$8
  AND status IN ('active','suspected_offline','offline','draining','uninstalling','removal_failed','cleanup_unknown')
 AND (relay_port_generation=0 OR (
   relay_port_generation=$4
   AND relay_https_port=$5
   AND relay_gateway_port=$6
 ))
`

type SetBastionRelayStatusParams struct {
	RelayStatus         string        `json:"relay_status"`
	RelayErrorCode      string        `json:"relay_error_code"`
	RelayAddress        string        `json:"relay_address"`
	RelayPortGeneration int64         `json:"relay_port_generation"`
	RelayHttpsPort      int32         `json:"relay_https_port"`
	RelayGatewayPort    int32         `json:"relay_gateway_port"`
	EnterpriseID        uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID   uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) SetBastionRelayStatus(ctx context.Context, arg SetBastionRelayStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBastionRelayStatus,
		arg.RelayStatus,
		arg.RelayErrorCode,
		arg.RelayAddress,
		arg.RelayPortGeneration,
		arg.RelayHttpsPort,
		arg.RelayGatewayPort,
		arg.EnterpriseID,
		arg.ActiveConnectorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPendingBastionScope = `-- name: TouchPendingBastionScope :one
UPDATE bastion_scopes SET resource_version = resource_version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND resource_version = $3 AND status = 'pending' RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type TouchPendingBastionScopeParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

// pending(尚未注册)作用域的替换:撤销旧令牌并递增版本,不发生 fencing。
func (q *Queries) TouchPendingBastionScope(ctx context.Context, arg TouchPendingBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, touchPendingBastionScope, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const updateBastionScope = `-- name: UpdateBastionScope :one
UPDATE bastion_scopes SET name = COALESCE($4, name), environment = COALESCE($5, environment),
 labels = COALESCE($6, labels), labels_hash = COALESCE($7, labels_hash),
 resource_version = resource_version + 1, updated_at = now()
WHERE id = $1 AND enterprise_id = $2 AND resource_version = $3 AND status <> 'deleted' RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type UpdateBastionScopeParams struct {
	ID              uuid.UUID   `json:"id"`
	EnterpriseID    uuid.UUID   `json:"enterprise_id"`
	ResourceVersion int64       `json:"resource_version"`
	Name            pgtype.Text `json:"name"`
	Environment     pgtype.Text `json:"environment"`
	Labels          []byte      `json:"labels"`
	LabelsHash      []byte      `json:"labels_hash"`
}

func (q *Queries) UpdateBastionScope(ctx context.Context, arg UpdateBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, updateBastionScope,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceVersion,
		arg.Name,
		arg.Environment,
		arg.Labels,
		arg.LabelsHash,
	)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}
