// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_parameters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDashboardAnalysisContext = `-- name: CreateDashboardAnalysisContext :one
INSERT INTO dashboard_analysis_contexts(id,enterprise_id,conversation_id,run_id,dashboard_id,owner_user_id,revision_id,condition_version,input_hash,user_event_id,state,parameters)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, enterprise_id, conversation_id, run_id, dashboard_id, owner_user_id, revision_id, condition_version, input_hash, user_event_id, state, parameters, created_at
`

type CreateDashboardAnalysisContextParams struct {
	ID               uuid.UUID `json:"id"`
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	ConversationID   uuid.UUID `json:"conversation_id"`
	RunID            uuid.UUID `json:"run_id"`
	DashboardID      uuid.UUID `json:"dashboard_id"`
	OwnerUserID      uuid.UUID `json:"owner_user_id"`
	RevisionID       uuid.UUID `json:"revision_id"`
	ConditionVersion int64     `json:"condition_version"`
	InputHash        string    `json:"input_hash"`
	UserEventID      uuid.UUID `json:"user_event_id"`
	State            []byte    `json:"state"`
	Parameters       []byte    `json:"parameters"`
}

func (q *Queries) CreateDashboardAnalysisContext(ctx context.Context, arg CreateDashboardAnalysisContextParams) (DashboardAnalysisContext, error) {
	row := q.db.QueryRow(ctx, createDashboardAnalysisContext,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.DashboardID,
		arg.OwnerUserID,
		arg.RevisionID,
		arg.ConditionVersion,
		arg.InputHash,
		arg.UserEventID,
		arg.State,
		arg.Parameters,
	)
	var i DashboardAnalysisContext
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.RevisionID,
		&i.ConditionVersion,
		&i.InputHash,
		&i.UserEventID,
		&i.State,
		&i.Parameters,
		&i.CreatedAt,
	)
	return i, err
}

const createDashboardRunParameters = `-- name: CreateDashboardRunParameters :exec
INSERT INTO dashboard_run_parameters(run_id,enterprise_id,conversation_id,dashboard_id,owner_user_id,version,state) VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateDashboardRunParametersParams struct {
	RunID          uuid.UUID `json:"run_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	DashboardID    uuid.UUID `json:"dashboard_id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
	Version        int64     `json:"version"`
	State          []byte    `json:"state"`
}

func (q *Queries) CreateDashboardRunParameters(ctx context.Context, arg CreateDashboardRunParametersParams) error {
	_, err := q.db.Exec(ctx, createDashboardRunParameters,
		arg.RunID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.DashboardID,
		arg.OwnerUserID,
		arg.Version,
		arg.State,
	)
	return err
}

const getDashboardAnalysisContext = `-- name: GetDashboardAnalysisContext :one
SELECT id, enterprise_id, conversation_id, run_id, dashboard_id, owner_user_id, revision_id, condition_version, input_hash, user_event_id, state, parameters, created_at FROM dashboard_analysis_contexts WHERE id=$1 AND enterprise_id=$2 AND conversation_id=$3 AND run_id=$4 AND owner_user_id=$5
`

type GetDashboardAnalysisContextParams struct {
	ID             uuid.UUID `json:"id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	RunID          uuid.UUID `json:"run_id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetDashboardAnalysisContext(ctx context.Context, arg GetDashboardAnalysisContextParams) (DashboardAnalysisContext, error) {
	row := q.db.QueryRow(ctx, getDashboardAnalysisContext,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.RunID,
		arg.OwnerUserID,
	)
	var i DashboardAnalysisContext
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.RevisionID,
		&i.ConditionVersion,
		&i.InputHash,
		&i.UserEventID,
		&i.State,
		&i.Parameters,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboardParameterState = `-- name: GetDashboardParameterState :one
SELECT enterprise_id, conversation_id, dashboard_id, owner_user_id, run_id, version, state FROM dashboard_parameter_states WHERE conversation_id=$1 AND dashboard_id=$2 AND enterprise_id=$3 AND owner_user_id=$4
`

type GetDashboardParameterStateParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	DashboardID    uuid.UUID `json:"dashboard_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetDashboardParameterState(ctx context.Context, arg GetDashboardParameterStateParams) (DashboardParameterState, error) {
	row := q.db.QueryRow(ctx, getDashboardParameterState,
		arg.ConversationID,
		arg.DashboardID,
		arg.EnterpriseID,
		arg.OwnerUserID,
	)
	var i DashboardParameterState
	err := row.Scan(
		&i.EnterpriseID,
		&i.ConversationID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.RunID,
		&i.Version,
		&i.State,
	)
	return i, err
}

const getDashboardRunParameters = `-- name: GetDashboardRunParameters :one
SELECT run_id, enterprise_id, conversation_id, dashboard_id, owner_user_id, version, state FROM dashboard_run_parameters WHERE run_id=$1 AND dashboard_id=$2 AND enterprise_id=$3 AND owner_user_id=$4
`

type GetDashboardRunParametersParams struct {
	RunID        uuid.UUID `json:"run_id"`
	DashboardID  uuid.UUID `json:"dashboard_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetDashboardRunParameters(ctx context.Context, arg GetDashboardRunParametersParams) (DashboardRunParameter, error) {
	row := q.db.QueryRow(ctx, getDashboardRunParameters,
		arg.RunID,
		arg.DashboardID,
		arg.EnterpriseID,
		arg.OwnerUserID,
	)
	var i DashboardRunParameter
	err := row.Scan(
		&i.RunID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.Version,
		&i.State,
	)
	return i, err
}

const getDashboardRunUserMessage = `-- name: GetDashboardRunUserMessage :one
SELECT id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification, occurred_at FROM conversation_events WHERE run_id=$1 AND enterprise_id=$2 AND conversation_id=$3 AND event_type='user_message' ORDER BY sequence LIMIT 1
`

type GetDashboardRunUserMessageParams struct {
	RunID          uuid.NullUUID `json:"run_id"`
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	ConversationID uuid.UUID     `json:"conversation_id"`
}

func (q *Queries) GetDashboardRunUserMessage(ctx context.Context, arg GetDashboardRunUserMessageParams) (ConversationEvent, error) {
	row := q.db.QueryRow(ctx, getDashboardRunUserMessage, arg.RunID, arg.EnterpriseID, arg.ConversationID)
	var i ConversationEvent
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.StepID,
		&i.Sequence,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.Payload,
		&i.ContentHash,
		&i.ArtifactRef,
		&i.DataClassification,
		&i.OccurredAt,
	)
	return i, err
}

const lockDashboardRunParameters = `-- name: LockDashboardRunParameters :one
SELECT run_id, enterprise_id, conversation_id, dashboard_id, owner_user_id, version, state FROM dashboard_run_parameters WHERE run_id=$1 AND dashboard_id=$2 AND enterprise_id=$3 AND owner_user_id=$4 FOR UPDATE
`

type LockDashboardRunParametersParams struct {
	RunID        uuid.UUID `json:"run_id"`
	DashboardID  uuid.UUID `json:"dashboard_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) LockDashboardRunParameters(ctx context.Context, arg LockDashboardRunParametersParams) (DashboardRunParameter, error) {
	row := q.db.QueryRow(ctx, lockDashboardRunParameters,
		arg.RunID,
		arg.DashboardID,
		arg.EnterpriseID,
		arg.OwnerUserID,
	)
	var i DashboardRunParameter
	err := row.Scan(
		&i.RunID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.Version,
		&i.State,
	)
	return i, err
}

const setDashboardParameterState = `-- name: SetDashboardParameterState :one
INSERT INTO dashboard_parameter_states(enterprise_id,conversation_id,dashboard_id,owner_user_id,run_id,version,state) VALUES($1,$2,$3,$4,$5,$6,$7)
ON CONFLICT(conversation_id,dashboard_id) DO UPDATE SET run_id=EXCLUDED.run_id,version=EXCLUDED.version,state=EXCLUDED.state
WHERE dashboard_parameter_states.enterprise_id=EXCLUDED.enterprise_id AND dashboard_parameter_states.owner_user_id=EXCLUDED.owner_user_id
 AND dashboard_parameter_states.version=$8
RETURNING enterprise_id, conversation_id, dashboard_id, owner_user_id, run_id, version, state
`

type SetDashboardParameterStateParams struct {
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ConversationID  uuid.UUID `json:"conversation_id"`
	DashboardID     uuid.UUID `json:"dashboard_id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	RunID           uuid.UUID `json:"run_id"`
	Version         int64     `json:"version"`
	State           []byte    `json:"state"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) SetDashboardParameterState(ctx context.Context, arg SetDashboardParameterStateParams) (DashboardParameterState, error) {
	row := q.db.QueryRow(ctx, setDashboardParameterState,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.DashboardID,
		arg.OwnerUserID,
		arg.RunID,
		arg.Version,
		arg.State,
		arg.ExpectedVersion,
	)
	var i DashboardParameterState
	err := row.Scan(
		&i.EnterpriseID,
		&i.ConversationID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.RunID,
		&i.Version,
		&i.State,
	)
	return i, err
}

const setDashboardRunParameters = `-- name: SetDashboardRunParameters :one
UPDATE dashboard_run_parameters SET state=$5,version=version+1
WHERE run_id=$1 AND dashboard_id=$2 AND enterprise_id=$3 AND owner_user_id=$4 AND version=$6
RETURNING run_id, enterprise_id, conversation_id, dashboard_id, owner_user_id, version, state
`

type SetDashboardRunParametersParams struct {
	RunID           uuid.UUID `json:"run_id"`
	DashboardID     uuid.UUID `json:"dashboard_id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	OwnerUserID     uuid.UUID `json:"owner_user_id"`
	State           []byte    `json:"state"`
	ExpectedVersion int64     `json:"expected_version"`
}

func (q *Queries) SetDashboardRunParameters(ctx context.Context, arg SetDashboardRunParametersParams) (DashboardRunParameter, error) {
	row := q.db.QueryRow(ctx, setDashboardRunParameters,
		arg.RunID,
		arg.DashboardID,
		arg.EnterpriseID,
		arg.OwnerUserID,
		arg.State,
		arg.ExpectedVersion,
	)
	var i DashboardRunParameter
	err := row.Scan(
		&i.RunID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.DashboardID,
		&i.OwnerUserID,
		&i.Version,
		&i.State,
	)
	return i, err
}
