// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const abandonDashboardQueryAttempts = `-- name: AbandonDashboardQueryAttempts :exec
UPDATE dashboard_query_attempts SET status='abandoned' WHERE job_id=$1 AND enterprise_id=$2 AND status='fetching'
`

type AbandonDashboardQueryAttemptsParams struct {
	JobID        uuid.UUID `json:"job_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) AbandonDashboardQueryAttempts(ctx context.Context, arg AbandonDashboardQueryAttemptsParams) error {
	_, err := q.db.Exec(ctx, abandonDashboardQueryAttempts, arg.JobID, arg.EnterpriseID)
	return err
}

const cancelConversationDashboardQueryJobs = `-- name: CancelConversationDashboardQueryJobs :exec
UPDATE dashboard_query_jobs SET status='cancelled',error_code='CONVERSATION_DELETED',version=version+1,updated_at=now()
WHERE conversation_id=$1 AND enterprise_id=$2 AND status NOT IN ('complete','partial','cancelled','failed')
`

type CancelConversationDashboardQueryJobsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CancelConversationDashboardQueryJobs(ctx context.Context, arg CancelConversationDashboardQueryJobsParams) error {
	_, err := q.db.Exec(ctx, cancelConversationDashboardQueryJobs, arg.ConversationID, arg.EnterpriseID)
	return err
}

const cancelQueuedDashboardQueryTasks = `-- name: CancelQueuedDashboardQueryTasks :exec
UPDATE runtime_tasks SET status='cancelled',updated_at=now() WHERE status='pending' AND id IN
(SELECT j.task_id FROM dashboard_query_jobs j WHERE j.conversation_id=$1 AND j.enterprise_id=$2 AND j.status='cancelled')
`

type CancelQueuedDashboardQueryTasksParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CancelQueuedDashboardQueryTasks(ctx context.Context, arg CancelQueuedDashboardQueryTasksParams) error {
	_, err := q.db.Exec(ctx, cancelQueuedDashboardQueryTasks, arg.ConversationID, arg.EnterpriseID)
	return err
}

const createDashboardQueryAttempt = `-- name: CreateDashboardQueryAttempt :one
INSERT INTO dashboard_query_attempts(id,enterprise_id,job_id,ordinal,status) VALUES($1,$2,$3,$4,'fetching') RETURNING id, enterprise_id, job_id, ordinal, status, created_at, sealed_at
`

type CreateDashboardQueryAttemptParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	JobID        uuid.UUID `json:"job_id"`
	Ordinal      int32     `json:"ordinal"`
}

func (q *Queries) CreateDashboardQueryAttempt(ctx context.Context, arg CreateDashboardQueryAttemptParams) (DashboardQueryAttempt, error) {
	row := q.db.QueryRow(ctx, createDashboardQueryAttempt,
		arg.ID,
		arg.EnterpriseID,
		arg.JobID,
		arg.Ordinal,
	)
	var i DashboardQueryAttempt
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.JobID,
		&i.Ordinal,
		&i.Status,
		&i.CreatedAt,
		&i.SealedAt,
	)
	return i, err
}

const createDashboardQueryDelivery = `-- name: CreateDashboardQueryDelivery :exec
INSERT INTO dashboard_query_deliveries(file_id,enterprise_id,workspace_id,workspace_file_id) VALUES($1,$2,$3,$4) ON CONFLICT(file_id,workspace_id) DO NOTHING
`

type CreateDashboardQueryDeliveryParams struct {
	FileID          uuid.UUID `json:"file_id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	WorkspaceID     uuid.UUID `json:"workspace_id"`
	WorkspaceFileID uuid.UUID `json:"workspace_file_id"`
}

func (q *Queries) CreateDashboardQueryDelivery(ctx context.Context, arg CreateDashboardQueryDeliveryParams) error {
	_, err := q.db.Exec(ctx, createDashboardQueryDelivery,
		arg.FileID,
		arg.EnterpriseID,
		arg.WorkspaceID,
		arg.WorkspaceFileID,
	)
	return err
}

const createDashboardQueryFile = `-- name: CreateDashboardQueryFile :one
INSERT INTO dashboard_query_files(id,enterprise_id,job_id,attempt_id,panel_id,target_id,file_kind,byte_size,content_hash,chunks) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, enterprise_id, job_id, attempt_id, panel_id, target_id, file_kind, byte_size, content_hash, chunks, created_at
`

type CreateDashboardQueryFileParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	JobID        uuid.UUID `json:"job_id"`
	AttemptID    uuid.UUID `json:"attempt_id"`
	PanelID      string    `json:"panel_id"`
	TargetID     string    `json:"target_id"`
	FileKind     string    `json:"file_kind"`
	ByteSize     int64     `json:"byte_size"`
	ContentHash  string    `json:"content_hash"`
	Chunks       []byte    `json:"chunks"`
}

func (q *Queries) CreateDashboardQueryFile(ctx context.Context, arg CreateDashboardQueryFileParams) (DashboardQueryFile, error) {
	row := q.db.QueryRow(ctx, createDashboardQueryFile,
		arg.ID,
		arg.EnterpriseID,
		arg.JobID,
		arg.AttemptID,
		arg.PanelID,
		arg.TargetID,
		arg.FileKind,
		arg.ByteSize,
		arg.ContentHash,
		arg.Chunks,
	)
	var i DashboardQueryFile
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.JobID,
		&i.AttemptID,
		&i.PanelID,
		&i.TargetID,
		&i.FileKind,
		&i.ByteSize,
		&i.ContentHash,
		&i.Chunks,
		&i.CreatedAt,
	)
	return i, err
}

const createDashboardQueryJob = `-- name: CreateDashboardQueryJob :one
INSERT INTO dashboard_query_jobs(id,enterprise_id,conversation_id,owner_user_id,run_id,dashboard_id,revision_id,authorization_version,task_id,request_key,input_hash,frozen_plan)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at
`

type CreateDashboardQueryJobParams struct {
	ID                   uuid.UUID     `json:"id"`
	EnterpriseID         uuid.UUID     `json:"enterprise_id"`
	ConversationID       uuid.UUID     `json:"conversation_id"`
	OwnerUserID          uuid.UUID     `json:"owner_user_id"`
	RunID                uuid.NullUUID `json:"run_id"`
	DashboardID          uuid.UUID     `json:"dashboard_id"`
	RevisionID           uuid.UUID     `json:"revision_id"`
	AuthorizationVersion int64         `json:"authorization_version"`
	TaskID               uuid.UUID     `json:"task_id"`
	RequestKey           string        `json:"request_key"`
	InputHash            string        `json:"input_hash"`
	FrozenPlan           []byte        `json:"frozen_plan"`
}

func (q *Queries) CreateDashboardQueryJob(ctx context.Context, arg CreateDashboardQueryJobParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, createDashboardQueryJob,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.OwnerUserID,
		arg.RunID,
		arg.DashboardID,
		arg.RevisionID,
		arg.AuthorizationVersion,
		arg.TaskID,
		arg.RequestKey,
		arg.InputHash,
		arg.FrozenPlan,
	)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDashboardQueryJob = `-- name: FindDashboardQueryJob :one
SELECT id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at FROM dashboard_query_jobs WHERE enterprise_id=$1 AND conversation_id=$2 AND owner_user_id=$3 AND request_key=$4
`

type FindDashboardQueryJobParams struct {
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	OwnerUserID    uuid.UUID `json:"owner_user_id"`
	RequestKey     string    `json:"request_key"`
}

func (q *Queries) FindDashboardQueryJob(ctx context.Context, arg FindDashboardQueryJobParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, findDashboardQueryJob,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.OwnerUserID,
		arg.RequestKey,
	)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardQueryDelivery = `-- name: GetDashboardQueryDelivery :one
SELECT d.file_id, d.enterprise_id, d.workspace_id, d.workspace_file_id, d.created_at FROM dashboard_query_deliveries d JOIN workspace_files f ON f.id=d.workspace_file_id
WHERE d.file_id=$1 AND d.workspace_id=$2 AND d.enterprise_id=$3 AND f.deleted_at IS NULL
`

type GetDashboardQueryDeliveryParams struct {
	FileID       uuid.UUID `json:"file_id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboardQueryDelivery(ctx context.Context, arg GetDashboardQueryDeliveryParams) (DashboardQueryDelivery, error) {
	row := q.db.QueryRow(ctx, getDashboardQueryDelivery, arg.FileID, arg.WorkspaceID, arg.EnterpriseID)
	var i DashboardQueryDelivery
	err := row.Scan(
		&i.FileID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.WorkspaceFileID,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboardQueryFile = `-- name: GetDashboardQueryFile :one
SELECT id, enterprise_id, job_id, attempt_id, panel_id, target_id, file_kind, byte_size, content_hash, chunks, created_at FROM dashboard_query_files WHERE id=$1 AND enterprise_id=$2
`

type GetDashboardQueryFileParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboardQueryFile(ctx context.Context, arg GetDashboardQueryFileParams) (DashboardQueryFile, error) {
	row := q.db.QueryRow(ctx, getDashboardQueryFile, arg.ID, arg.EnterpriseID)
	var i DashboardQueryFile
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.JobID,
		&i.AttemptID,
		&i.PanelID,
		&i.TargetID,
		&i.FileKind,
		&i.ByteSize,
		&i.ContentHash,
		&i.Chunks,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboardQueryJob = `-- name: GetDashboardQueryJob :one
SELECT id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at FROM dashboard_query_jobs WHERE id=$1 AND enterprise_id=$2
`

type GetDashboardQueryJobParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboardQueryJob(ctx context.Context, arg GetDashboardQueryJobParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, getDashboardQueryJob, arg.ID, arg.EnterpriseID)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceFileByPath = `-- name: GetWorkspaceFileByPath :one
SELECT id, enterprise_id, workspace_id, conversation_id, name, path, byte_size, content_hash, media_type, source_result_refs, created_at, deleted_at FROM workspace_files WHERE workspace_id=$1 AND enterprise_id=$2 AND path=$3 AND deleted_at IS NULL
`

type GetWorkspaceFileByPathParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Path         string    `json:"path"`
}

func (q *Queries) GetWorkspaceFileByPath(ctx context.Context, arg GetWorkspaceFileByPathParams) (WorkspaceFile, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFileByPath, arg.WorkspaceID, arg.EnterpriseID, arg.Path)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Name,
		&i.Path,
		&i.ByteSize,
		&i.ContentHash,
		&i.MediaType,
		&i.SourceResultRefs,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDashboardQueryFiles = `-- name: ListDashboardQueryFiles :many
SELECT id, enterprise_id, job_id, attempt_id, panel_id, target_id, file_kind, byte_size, content_hash, chunks, created_at FROM dashboard_query_files WHERE attempt_id=$1 AND enterprise_id=$2 ORDER BY file_kind,panel_id,target_id
`

type ListDashboardQueryFilesParams struct {
	AttemptID    uuid.UUID `json:"attempt_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListDashboardQueryFiles(ctx context.Context, arg ListDashboardQueryFilesParams) ([]DashboardQueryFile, error) {
	rows, err := q.db.Query(ctx, listDashboardQueryFiles, arg.AttemptID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardQueryFile{}
	for rows.Next() {
		var i DashboardQueryFile
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.JobID,
			&i.AttemptID,
			&i.PanelID,
			&i.TargetID,
			&i.FileKind,
			&i.ByteSize,
			&i.ContentHash,
			&i.Chunks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDashboardQueryJob = `-- name: LockDashboardQueryJob :one
SELECT id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at FROM dashboard_query_jobs WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockDashboardQueryJobParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) LockDashboardQueryJob(ctx context.Context, arg LockDashboardQueryJobParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, lockDashboardQueryJob, arg.ID, arg.EnterpriseID)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryDashboardQueryTask = `-- name: RetryDashboardQueryTask :execrows
UPDATE runtime_tasks SET status='pending',available_at=now(),max_attempts=attempt+5,last_error_code=NULL,
 lease_owner=NULL,lease_until=NULL,updated_at=now() WHERE id=$1 AND enterprise_id=$2 AND queue='dashboard_query' AND status='failed'
`

type RetryDashboardQueryTaskParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.NullUUID `json:"enterprise_id"`
}

func (q *Queries) RetryDashboardQueryTask(ctx context.Context, arg RetryDashboardQueryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryDashboardQueryTask, arg.ID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sealDashboardQueryAttempt = `-- name: SealDashboardQueryAttempt :one
UPDATE dashboard_query_attempts SET status='materialized',sealed_at=now() WHERE id=$1 AND enterprise_id=$2 AND status='fetching' RETURNING id, enterprise_id, job_id, ordinal, status, created_at, sealed_at
`

type SealDashboardQueryAttemptParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) SealDashboardQueryAttempt(ctx context.Context, arg SealDashboardQueryAttemptParams) (DashboardQueryAttempt, error) {
	row := q.db.QueryRow(ctx, sealDashboardQueryAttempt, arg.ID, arg.EnterpriseID)
	var i DashboardQueryAttempt
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.JobID,
		&i.Ordinal,
		&i.Status,
		&i.CreatedAt,
		&i.SealedAt,
	)
	return i, err
}

const sealDashboardQueryJob = `-- name: SealDashboardQueryJob :one
UPDATE dashboard_query_jobs SET status='materialized',manifest=$3,version=version+1,updated_at=now() WHERE id=$1 AND enterprise_id=$2 AND status='fetching' AND attempt_id=$4 AND manifest IS NULL RETURNING id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at
`

type SealDashboardQueryJobParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	Manifest     []byte        `json:"manifest"`
	AttemptID    uuid.NullUUID `json:"attempt_id"`
}

func (q *Queries) SealDashboardQueryJob(ctx context.Context, arg SealDashboardQueryJobParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, sealDashboardQueryJob,
		arg.ID,
		arg.EnterpriseID,
		arg.Manifest,
		arg.AttemptID,
	)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDashboardQueryJobState = `-- name: SetDashboardQueryJobState :one
UPDATE dashboard_query_jobs SET status=$3,attempt_id=$4,error_code=$5,version=version+1,updated_at=now() WHERE id=$1 AND enterprise_id=$2 RETURNING id, enterprise_id, conversation_id, owner_user_id, run_id, dashboard_id, revision_id, authorization_version, task_id, request_key, input_hash, frozen_plan, status, attempt_id, manifest, error_code, version, created_at, updated_at
`

type SetDashboardQueryJobStateParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	Status       string        `json:"status"`
	AttemptID    uuid.NullUUID `json:"attempt_id"`
	ErrorCode    string        `json:"error_code"`
}

func (q *Queries) SetDashboardQueryJobState(ctx context.Context, arg SetDashboardQueryJobStateParams) (DashboardQueryJob, error) {
	row := q.db.QueryRow(ctx, setDashboardQueryJobState,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.AttemptID,
		arg.ErrorCode,
	)
	var i DashboardQueryJob
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.OwnerUserID,
		&i.RunID,
		&i.DashboardID,
		&i.RevisionID,
		&i.AuthorizationVersion,
		&i.TaskID,
		&i.RequestKey,
		&i.InputHash,
		&i.FrozenPlan,
		&i.Status,
		&i.AttemptID,
		&i.Manifest,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
