// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const activateDashboardRevision = `-- name: ActivateDashboardRevision :one
UPDATE dashboards SET active_revision_id=$3,name=$4,description=$5,folder_id=$6,updated_by=$7,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$8 AND lifecycle='active' RETURNING id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at
`

type ActivateDashboardRevisionParams struct {
	ID               uuid.UUID     `json:"id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	ActiveRevisionID uuid.NullUUID `json:"active_revision_id"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	FolderID         uuid.NullUUID `json:"folder_id"`
	UpdatedBy        uuid.UUID     `json:"updated_by"`
	Version          int64         `json:"version"`
}

func (q *Queries) ActivateDashboardRevision(ctx context.Context, arg ActivateDashboardRevisionParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, activateDashboardRevision,
		arg.ID,
		arg.EnterpriseID,
		arg.ActiveRevisionID,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.UpdatedBy,
		arg.Version,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.ActiveRevisionID,
		&i.Version,
		&i.Lifecycle,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeDashboardDraft = `-- name: ConsumeDashboardDraft :one
UPDATE dashboard_drafts SET status='published',dashboard_id=$3,published_revision_id=$4,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND draft_version=$5 AND status='editing' RETURNING id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at
`

type ConsumeDashboardDraftParams struct {
	ID                  uuid.UUID     `json:"id"`
	EnterpriseID        uuid.UUID     `json:"enterprise_id"`
	DashboardID         uuid.NullUUID `json:"dashboard_id"`
	PublishedRevisionID uuid.NullUUID `json:"published_revision_id"`
	DraftVersion        int64         `json:"draft_version"`
}

func (q *Queries) ConsumeDashboardDraft(ctx context.Context, arg ConsumeDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, consumeDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.DashboardID,
		arg.PublishedRevisionID,
		arg.DraftVersion,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFolderDashboards = `-- name: CountFolderDashboards :one
SELECT count(*) FROM dashboards WHERE enterprise_id=$1 AND folder_id=$2
`

type CountFolderDashboardsParams struct {
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	FolderID     uuid.NullUUID `json:"folder_id"`
}

func (q *Queries) CountFolderDashboards(ctx context.Context, arg CountFolderDashboardsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFolderDashboards, arg.EnterpriseID, arg.FolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards(id,enterprise_id,folder_id,name,description,created_by,updated_by)
VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at
`

type CreateDashboardParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	FolderID     uuid.NullUUID `json:"folder_id"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	CreatedBy    uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard,
		arg.ID,
		arg.EnterpriseID,
		arg.FolderID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.ActiveRevisionID,
		&i.Version,
		&i.Lifecycle,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDashboardBinding = `-- name: CreateDashboardBinding :one
INSERT INTO dashboard_bindings(id,enterprise_id,dashboard_id,resource_type,resource_id,created_by)
VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(enterprise_id,dashboard_id,resource_type,resource_id) DO UPDATE SET dashboard_id=EXCLUDED.dashboard_id RETURNING id, enterprise_id, dashboard_id, resource_type, resource_id, version, created_by, created_at
`

type CreateDashboardBindingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	DashboardID  uuid.UUID `json:"dashboard_id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDashboardBinding(ctx context.Context, arg CreateDashboardBindingParams) (DashboardBinding, error) {
	row := q.db.QueryRow(ctx, createDashboardBinding,
		arg.ID,
		arg.EnterpriseID,
		arg.DashboardID,
		arg.ResourceType,
		arg.ResourceID,
		arg.CreatedBy,
	)
	var i DashboardBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createDashboardDraft = `-- name: CreateDashboardDraft :one
INSERT INTO dashboard_drafts(id,enterprise_id,dashboard_id,editor_subject_type,editor_subject_id,base_revision_id,base_object_version,name,description,folder_id,spec,proposed_bindings)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at
`

type CreateDashboardDraftParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	DashboardID       uuid.NullUUID `json:"dashboard_id"`
	EditorSubjectType string        `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID     `json:"editor_subject_id"`
	BaseRevisionID    uuid.NullUUID `json:"base_revision_id"`
	BaseObjectVersion int64         `json:"base_object_version"`
	Name              string        `json:"name"`
	Description       string        `json:"description"`
	FolderID          uuid.NullUUID `json:"folder_id"`
	Spec              []byte        `json:"spec"`
	ProposedBindings  []byte        `json:"proposed_bindings"`
}

func (q *Queries) CreateDashboardDraft(ctx context.Context, arg CreateDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, createDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.DashboardID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
		arg.BaseRevisionID,
		arg.BaseObjectVersion,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.Spec,
		arg.ProposedBindings,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDashboardFolder = `-- name: CreateDashboardFolder :one
INSERT INTO dashboard_folders(id,enterprise_id,name,description,sort_order,created_by,updated_by)
VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING id, enterprise_id, name, description, sort_order, status, version, created_by, updated_by, created_at, updated_at
`

type CreateDashboardFolderParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	SortOrder    int32     `json:"sort_order"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDashboardFolder(ctx context.Context, arg CreateDashboardFolderParams) (DashboardFolder, error) {
	row := q.db.QueryRow(ctx, createDashboardFolder,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i DashboardFolder
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDashboardRevision = `-- name: CreateDashboardRevision :one
INSERT INTO dashboard_revisions(id,enterprise_id,dashboard_id,revision_number,schema_version,name,description,folder_id,spec,spec_hash,validation_report,sample_report,created_by)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, enterprise_id, dashboard_id, revision_number, schema_version, name, description, folder_id, spec, spec_hash, validation_report, sample_report, created_by, created_at
`

type CreateDashboardRevisionParams struct {
	ID               uuid.UUID     `json:"id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	DashboardID      uuid.UUID     `json:"dashboard_id"`
	RevisionNumber   int64         `json:"revision_number"`
	SchemaVersion    string        `json:"schema_version"`
	Name             string        `json:"name"`
	Description      string        `json:"description"`
	FolderID         uuid.NullUUID `json:"folder_id"`
	Spec             []byte        `json:"spec"`
	SpecHash         string        `json:"spec_hash"`
	ValidationReport []byte        `json:"validation_report"`
	SampleReport     []byte        `json:"sample_report"`
	CreatedBy        uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateDashboardRevision(ctx context.Context, arg CreateDashboardRevisionParams) (DashboardRevision, error) {
	row := q.db.QueryRow(ctx, createDashboardRevision,
		arg.ID,
		arg.EnterpriseID,
		arg.DashboardID,
		arg.RevisionNumber,
		arg.SchemaVersion,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.Spec,
		arg.SpecHash,
		arg.ValidationReport,
		arg.SampleReport,
		arg.CreatedBy,
	)
	var i DashboardRevision
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.RevisionNumber,
		&i.SchemaVersion,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.SpecHash,
		&i.ValidationReport,
		&i.SampleReport,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDashboardBinding = `-- name: DeleteDashboardBinding :execrows
DELETE FROM dashboard_bindings WHERE id=$1 AND enterprise_id=$2 AND version=$3
`

type DeleteDashboardBindingParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) DeleteDashboardBinding(ctx context.Context, arg DeleteDashboardBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashboardBinding, arg.ID, arg.EnterpriseID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const discardDashboardDraft = `-- name: DiscardDashboardDraft :execrows
UPDATE dashboard_drafts SET status='discarded',draft_version=draft_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND editor_subject_type=$3 AND editor_subject_id=$4 AND draft_version=$5 AND status='editing'
`

type DiscardDashboardDraftParams struct {
	ID                uuid.UUID `json:"id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	EditorSubjectType string    `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID `json:"editor_subject_id"`
	DraftVersion      int64     `json:"draft_version"`
}

func (q *Queries) DiscardDashboardDraft(ctx context.Context, arg DiscardDashboardDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
		arg.DraftVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDashboardBinding = `-- name: FindDashboardBinding :one
SELECT id, enterprise_id, dashboard_id, resource_type, resource_id, version, created_by, created_at FROM dashboard_bindings WHERE enterprise_id=$1 AND dashboard_id=$2 AND resource_type=$3 AND resource_id=$4
`

type FindDashboardBindingParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	DashboardID  uuid.UUID `json:"dashboard_id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) FindDashboardBinding(ctx context.Context, arg FindDashboardBindingParams) (DashboardBinding, error) {
	row := q.db.QueryRow(ctx, findDashboardBinding,
		arg.EnterpriseID,
		arg.DashboardID,
		arg.ResourceType,
		arg.ResourceID,
	)
	var i DashboardBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at FROM dashboards WHERE id=$1 AND enterprise_id=$2
`

type GetDashboardParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboard(ctx context.Context, arg GetDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboard, arg.ID, arg.EnterpriseID)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.ActiveRevisionID,
		&i.Version,
		&i.Lifecycle,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardDraft = `-- name: GetDashboardDraft :one
SELECT id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at FROM dashboard_drafts WHERE id=$1 AND enterprise_id=$2 AND editor_subject_type=$3 AND editor_subject_id=$4
`

type GetDashboardDraftParams struct {
	ID                uuid.UUID `json:"id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	EditorSubjectType string    `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID `json:"editor_subject_id"`
}

func (q *Queries) GetDashboardDraft(ctx context.Context, arg GetDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, getDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardFolder = `-- name: GetDashboardFolder :one
SELECT id, enterprise_id, name, description, sort_order, status, version, created_by, updated_by, created_at, updated_at FROM dashboard_folders WHERE id=$1 AND enterprise_id=$2
`

type GetDashboardFolderParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboardFolder(ctx context.Context, arg GetDashboardFolderParams) (DashboardFolder, error) {
	row := q.db.QueryRow(ctx, getDashboardFolder, arg.ID, arg.EnterpriseID)
	var i DashboardFolder
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDashboardRevision = `-- name: GetDashboardRevision :one
SELECT id, enterprise_id, dashboard_id, revision_number, schema_version, name, description, folder_id, spec, spec_hash, validation_report, sample_report, created_by, created_at FROM dashboard_revisions WHERE id=$1 AND enterprise_id=$2
`

type GetDashboardRevisionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetDashboardRevision(ctx context.Context, arg GetDashboardRevisionParams) (DashboardRevision, error) {
	row := q.db.QueryRow(ctx, getDashboardRevision, arg.ID, arg.EnterpriseID)
	var i DashboardRevision
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.RevisionNumber,
		&i.SchemaVersion,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.SpecHash,
		&i.ValidationReport,
		&i.SampleReport,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDashboardBindings = `-- name: ListDashboardBindings :many
SELECT id, enterprise_id, dashboard_id, resource_type, resource_id, version, created_by, created_at FROM dashboard_bindings WHERE enterprise_id=$1 AND dashboard_id=$2 ORDER BY created_at,id
`

type ListDashboardBindingsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	DashboardID  uuid.UUID `json:"dashboard_id"`
}

func (q *Queries) ListDashboardBindings(ctx context.Context, arg ListDashboardBindingsParams) ([]DashboardBinding, error) {
	rows, err := q.db.Query(ctx, listDashboardBindings, arg.EnterpriseID, arg.DashboardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardBinding{}
	for rows.Next() {
		var i DashboardBinding
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.DashboardID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardDrafts = `-- name: ListDashboardDrafts :many
SELECT id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at FROM dashboard_drafts WHERE enterprise_id=$1 AND editor_subject_type=$2 AND editor_subject_id=$3 AND status='editing' ORDER BY updated_at DESC,id
`

type ListDashboardDraftsParams struct {
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	EditorSubjectType string    `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID `json:"editor_subject_id"`
}

func (q *Queries) ListDashboardDrafts(ctx context.Context, arg ListDashboardDraftsParams) ([]DashboardDraft, error) {
	rows, err := q.db.Query(ctx, listDashboardDrafts, arg.EnterpriseID, arg.EditorSubjectType, arg.EditorSubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDraft{}
	for rows.Next() {
		var i DashboardDraft
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.DashboardID,
			&i.EditorSubjectType,
			&i.EditorSubjectID,
			&i.BaseRevisionID,
			&i.BaseObjectVersion,
			&i.DraftVersion,
			&i.Status,
			&i.PublishedRevisionID,
			&i.Name,
			&i.Description,
			&i.FolderID,
			&i.Spec,
			&i.ProposedBindings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardFolders = `-- name: ListDashboardFolders :many
SELECT id, enterprise_id, name, description, sort_order, status, version, created_by, updated_by, created_at, updated_at FROM dashboard_folders WHERE enterprise_id=$1 ORDER BY sort_order,name,id
`

func (q *Queries) ListDashboardFolders(ctx context.Context, enterpriseID uuid.UUID) ([]DashboardFolder, error) {
	rows, err := q.db.Query(ctx, listDashboardFolders, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardFolder{}
	for rows.Next() {
		var i DashboardFolder
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Status,
			&i.Version,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardRevisions = `-- name: ListDashboardRevisions :many
SELECT id, enterprise_id, dashboard_id, revision_number, schema_version, name, description, folder_id, spec, spec_hash, validation_report, sample_report, created_by, created_at FROM dashboard_revisions WHERE dashboard_id=$1 AND enterprise_id=$2 ORDER BY revision_number DESC
`

type ListDashboardRevisionsParams struct {
	DashboardID  uuid.UUID `json:"dashboard_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListDashboardRevisions(ctx context.Context, arg ListDashboardRevisionsParams) ([]DashboardRevision, error) {
	rows, err := q.db.Query(ctx, listDashboardRevisions, arg.DashboardID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRevision{}
	for rows.Next() {
		var i DashboardRevision
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.DashboardID,
			&i.RevisionNumber,
			&i.SchemaVersion,
			&i.Name,
			&i.Description,
			&i.FolderID,
			&i.Spec,
			&i.SpecHash,
			&i.ValidationReport,
			&i.SampleReport,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboards = `-- name: ListDashboards :many
SELECT id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at FROM dashboards WHERE enterprise_id=$1 ORDER BY name,id
`

func (q *Queries) ListDashboards(ctx context.Context, enterpriseID uuid.UUID) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboards, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dashboard{}
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.FolderID,
			&i.Name,
			&i.Description,
			&i.ActiveRevisionID,
			&i.Version,
			&i.Lifecycle,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceDashboardBindings = `-- name: ListResourceDashboardBindings :many
SELECT id, enterprise_id, dashboard_id, resource_type, resource_id, version, created_by, created_at FROM dashboard_bindings WHERE enterprise_id=$1 AND resource_type=$2 AND resource_id=$3 ORDER BY created_at,id
`

type ListResourceDashboardBindingsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) ListResourceDashboardBindings(ctx context.Context, arg ListResourceDashboardBindingsParams) ([]DashboardBinding, error) {
	rows, err := q.db.Query(ctx, listResourceDashboardBindings, arg.EnterpriseID, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardBinding{}
	for rows.Next() {
		var i DashboardBinding
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.DashboardID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDashboard = `-- name: LockDashboard :one
SELECT id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at FROM dashboards WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockDashboardParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) LockDashboard(ctx context.Context, arg LockDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, lockDashboard, arg.ID, arg.EnterpriseID)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.ActiveRevisionID,
		&i.Version,
		&i.Lifecycle,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDashboardBindingCluster = `-- name: LockDashboardBindingCluster :one
SELECT id,name,status,resource_version FROM kubernetes_clusters WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockDashboardBindingClusterParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type LockDashboardBindingClusterRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Status          string    `json:"status"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) LockDashboardBindingCluster(ctx context.Context, arg LockDashboardBindingClusterParams) (LockDashboardBindingClusterRow, error) {
	row := q.db.QueryRow(ctx, lockDashboardBindingCluster, arg.ID, arg.EnterpriseID)
	var i LockDashboardBindingClusterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ResourceVersion,
	)
	return i, err
}

const lockDashboardBindingHost = `-- name: LockDashboardBindingHost :one
SELECT id,name,status,resource_version FROM hosts WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockDashboardBindingHostParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

type LockDashboardBindingHostRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Status          string    `json:"status"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) LockDashboardBindingHost(ctx context.Context, arg LockDashboardBindingHostParams) (LockDashboardBindingHostRow, error) {
	row := q.db.QueryRow(ctx, lockDashboardBindingHost, arg.ID, arg.EnterpriseID)
	var i LockDashboardBindingHostRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ResourceVersion,
	)
	return i, err
}

const lockDashboardDraft = `-- name: LockDashboardDraft :one
SELECT id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at FROM dashboard_drafts WHERE id=$1 AND enterprise_id=$2 AND editor_subject_type=$3 AND editor_subject_id=$4 FOR UPDATE
`

type LockDashboardDraftParams struct {
	ID                uuid.UUID `json:"id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	EditorSubjectType string    `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID `json:"editor_subject_id"`
}

func (q *Queries) LockDashboardDraft(ctx context.Context, arg LockDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, lockDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockDashboardFolder = `-- name: LockDashboardFolder :one
SELECT id, enterprise_id, name, description, sort_order, status, version, created_by, updated_by, created_at, updated_at FROM dashboard_folders WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockDashboardFolderParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) LockDashboardFolder(ctx context.Context, arg LockDashboardFolderParams) (DashboardFolder, error) {
	row := q.db.QueryRow(ctx, lockDashboardFolder, arg.ID, arg.EnterpriseID)
	var i DashboardFolder
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rebaseDashboardDraft = `-- name: RebaseDashboardDraft :one
UPDATE dashboard_drafts SET base_revision_id=$5,base_object_version=$6,draft_version=draft_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND editor_subject_type=$3 AND editor_subject_id=$4 AND draft_version=$7 AND status='editing' RETURNING id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at
`

type RebaseDashboardDraftParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	EditorSubjectType string        `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID     `json:"editor_subject_id"`
	BaseRevisionID    uuid.NullUUID `json:"base_revision_id"`
	BaseObjectVersion int64         `json:"base_object_version"`
	DraftVersion      int64         `json:"draft_version"`
}

func (q *Queries) RebaseDashboardDraft(ctx context.Context, arg RebaseDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, rebaseDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
		arg.BaseRevisionID,
		arg.BaseObjectVersion,
		arg.DraftVersion,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveDashboardDraft = `-- name: SaveDashboardDraft :one
UPDATE dashboard_drafts SET name=$5,description=$6,folder_id=$7,spec=$8,proposed_bindings=$9,draft_version=draft_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND editor_subject_type=$3 AND editor_subject_id=$4 AND draft_version=$10 AND status='editing' RETURNING id, enterprise_id, dashboard_id, editor_subject_type, editor_subject_id, base_revision_id, base_object_version, draft_version, status, published_revision_id, name, description, folder_id, spec, proposed_bindings, created_at, updated_at
`

type SaveDashboardDraftParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	EditorSubjectType string        `json:"editor_subject_type"`
	EditorSubjectID   uuid.UUID     `json:"editor_subject_id"`
	Name              string        `json:"name"`
	Description       string        `json:"description"`
	FolderID          uuid.NullUUID `json:"folder_id"`
	Spec              []byte        `json:"spec"`
	ProposedBindings  []byte        `json:"proposed_bindings"`
	DraftVersion      int64         `json:"draft_version"`
}

func (q *Queries) SaveDashboardDraft(ctx context.Context, arg SaveDashboardDraftParams) (DashboardDraft, error) {
	row := q.db.QueryRow(ctx, saveDashboardDraft,
		arg.ID,
		arg.EnterpriseID,
		arg.EditorSubjectType,
		arg.EditorSubjectID,
		arg.Name,
		arg.Description,
		arg.FolderID,
		arg.Spec,
		arg.ProposedBindings,
		arg.DraftVersion,
	)
	var i DashboardDraft
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.DashboardID,
		&i.EditorSubjectType,
		&i.EditorSubjectID,
		&i.BaseRevisionID,
		&i.BaseObjectVersion,
		&i.DraftVersion,
		&i.Status,
		&i.PublishedRevisionID,
		&i.Name,
		&i.Description,
		&i.FolderID,
		&i.Spec,
		&i.ProposedBindings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDashboardFolder = `-- name: UpdateDashboardFolder :one
UPDATE dashboard_folders SET name=$3,description=$4,sort_order=$5,status=$6,updated_by=$7,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$8 RETURNING id, enterprise_id, name, description, sort_order, status, version, created_by, updated_by, created_at, updated_at
`

type UpdateDashboardFolderParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	SortOrder    int32     `json:"sort_order"`
	Status       string    `json:"status"`
	UpdatedBy    uuid.UUID `json:"updated_by"`
	Version      int64     `json:"version"`
}

func (q *Queries) UpdateDashboardFolder(ctx context.Context, arg UpdateDashboardFolderParams) (DashboardFolder, error) {
	row := q.db.QueryRow(ctx, updateDashboardFolder,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Status,
		arg.UpdatedBy,
		arg.Version,
	)
	var i DashboardFolder
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Status,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDashboardLifecycle = `-- name: UpdateDashboardLifecycle :one
UPDATE dashboards SET lifecycle=$3,updated_by=$4,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$5 RETURNING id, enterprise_id, folder_id, name, description, active_revision_id, version, lifecycle, created_by, updated_by, created_at, updated_at
`

type UpdateDashboardLifecycleParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Lifecycle    string    `json:"lifecycle"`
	UpdatedBy    uuid.UUID `json:"updated_by"`
	Version      int64     `json:"version"`
}

func (q *Queries) UpdateDashboardLifecycle(ctx context.Context, arg UpdateDashboardLifecycleParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, updateDashboardLifecycle,
		arg.ID,
		arg.EnterpriseID,
		arg.Lifecycle,
		arg.UpdatedBy,
		arg.Version,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.FolderID,
		&i.Name,
		&i.Description,
		&i.ActiveRevisionID,
		&i.Version,
		&i.Lifecycle,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
