// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_runtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getHostRuntimeObservation = `-- name: GetHostRuntimeObservation :one
SELECT host_id, enterprise_id, connector_id, platform, openssh_status, rdp_status, rdp_nla_enabled, rdp_firewall_enabled, rdp_service_running, observed_at, updated_at FROM host_runtime_observations WHERE enterprise_id=$1 AND host_id=$2
`

type GetHostRuntimeObservationParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

func (q *Queries) GetHostRuntimeObservation(ctx context.Context, arg GetHostRuntimeObservationParams) (HostRuntimeObservation, error) {
	row := q.db.QueryRow(ctx, getHostRuntimeObservation, arg.EnterpriseID, arg.HostID)
	var i HostRuntimeObservation
	err := row.Scan(
		&i.HostID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.Platform,
		&i.OpensshStatus,
		&i.RdpStatus,
		&i.RdpNlaEnabled,
		&i.RdpFirewallEnabled,
		&i.RdpServiceRunning,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHostRuntimeObservations = `-- name: ListHostRuntimeObservations :many
SELECT host_id, enterprise_id, connector_id, platform, openssh_status, rdp_status, rdp_nla_enabled, rdp_firewall_enabled, rdp_service_running, observed_at, updated_at FROM host_runtime_observations WHERE enterprise_id=$1 AND host_id=ANY($2::uuid[]) ORDER BY host_id
`

type ListHostRuntimeObservationsParams struct {
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Column2      []uuid.UUID `json:"column_2"`
}

func (q *Queries) ListHostRuntimeObservations(ctx context.Context, arg ListHostRuntimeObservationsParams) ([]HostRuntimeObservation, error) {
	rows, err := q.db.Query(ctx, listHostRuntimeObservations, arg.EnterpriseID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRuntimeObservation{}
	for rows.Next() {
		var i HostRuntimeObservation
		if err := rows.Scan(
			&i.HostID,
			&i.EnterpriseID,
			&i.ConnectorID,
			&i.Platform,
			&i.OpensshStatus,
			&i.RdpStatus,
			&i.RdpNlaEnabled,
			&i.RdpFirewallEnabled,
			&i.RdpServiceRunning,
			&i.ObservedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHostRuntimeObservation = `-- name: UpsertHostRuntimeObservation :one
INSERT INTO host_runtime_observations (host_id,enterprise_id,connector_id,platform,openssh_status,rdp_status,rdp_nla_enabled,rdp_firewall_enabled,rdp_service_running,observed_at)
SELECT connector.host_id,connector.enterprise_id,connector.id,$3,$4,$5,$6,$7,$8,$9
FROM connectors connector
JOIN hosts host ON host.id=connector.host_id AND host.enterprise_id=connector.enterprise_id AND host.status<>'deleted'
WHERE connector.id=$1 AND connector.enterprise_id=$2 AND connector.role IN ('host','bastion') AND host.platform=$3
ON CONFLICT (host_id) DO UPDATE SET connector_id=EXCLUDED.connector_id,platform=EXCLUDED.platform,openssh_status=EXCLUDED.openssh_status,
 rdp_status=EXCLUDED.rdp_status,rdp_nla_enabled=EXCLUDED.rdp_nla_enabled,rdp_firewall_enabled=EXCLUDED.rdp_firewall_enabled,
 rdp_service_running=EXCLUDED.rdp_service_running,observed_at=EXCLUDED.observed_at,updated_at=now()
RETURNING host_id, enterprise_id, connector_id, platform, openssh_status, rdp_status, rdp_nla_enabled, rdp_firewall_enabled, rdp_service_running, observed_at, updated_at
`

type UpsertHostRuntimeObservationParams struct {
	ID                 uuid.UUID          `json:"id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	Platform           string             `json:"platform"`
	OpensshStatus      string             `json:"openssh_status"`
	RdpStatus          string             `json:"rdp_status"`
	RdpNlaEnabled      bool               `json:"rdp_nla_enabled"`
	RdpFirewallEnabled bool               `json:"rdp_firewall_enabled"`
	RdpServiceRunning  bool               `json:"rdp_service_running"`
	ObservedAt         pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) UpsertHostRuntimeObservation(ctx context.Context, arg UpsertHostRuntimeObservationParams) (HostRuntimeObservation, error) {
	row := q.db.QueryRow(ctx, upsertHostRuntimeObservation,
		arg.ID,
		arg.EnterpriseID,
		arg.Platform,
		arg.OpensshStatus,
		arg.RdpStatus,
		arg.RdpNlaEnabled,
		arg.RdpFirewallEnabled,
		arg.RdpServiceRunning,
		arg.ObservedAt,
	)
	var i HostRuntimeObservation
	err := row.Scan(
		&i.HostID,
		&i.EnterpriseID,
		&i.ConnectorID,
		&i.Platform,
		&i.OpensshStatus,
		&i.RdpStatus,
		&i.RdpNlaEnabled,
		&i.RdpFirewallEnabled,
		&i.RdpServiceRunning,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}
