// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const revokeHostRemovalTokens = `-- name: RevokeHostRemovalTokens :execrows
UPDATE host_removal_tokens SET status='revoked'
WHERE operation_id=$1 AND enterprise_id=$2 AND status='active'
`

type RevokeHostRemovalTokensParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeHostRemovalTokens(ctx context.Context, arg RevokeHostRemovalTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeHostRemovalTokens, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRemovalConnectorCommands = `-- name: RevokeRemovalConnectorCommands :execrows
UPDATE connector_commands SET status='expired',error_code='HOST_REMOVAL_DRAINING',completed_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND connector_id=$2 AND status IN ('queued','dispatched','acknowledged','running')
`

type RevokeRemovalConnectorCommandsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ConnectorID  uuid.UUID `json:"connector_id"`
}

func (q *Queries) RevokeRemovalConnectorCommands(ctx context.Context, arg RevokeRemovalConnectorCommandsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRemovalConnectorCommands, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startBastionRootHostRemoval = `-- name: StartBastionRootHostRemoval :one
UPDATE hosts SET status='draining',local_cleanup='pending',removal_generation=$4,
 resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND role='bastion'
  AND status IN ('active','disabled','removal_failed','cleanup_unknown') RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type StartBastionRootHostRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) StartBastionRootHostRemoval(ctx context.Context, arg StartBastionRootHostRemovalParams) (Host, error) {
	row := q.db.QueryRow(ctx, startBastionRootHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const startBastionScopeRemoval = `-- name: StartBastionScopeRemoval :one
UPDATE bastion_scopes SET status='draining', local_cleanup='pending', removal_generation=removal_generation+1,
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND active_connector_id=$4
  AND status IN ('active','suspected_offline','offline','removal_failed','cleanup_unknown')
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type StartBastionScopeRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ResourceVersion   int64         `json:"resource_version"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) StartBastionScopeRemoval(ctx context.Context, arg StartBastionScopeRemovalParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, startBastionScopeRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceVersion,
		arg.ActiveConnectorID,
	)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const startManagedHostRemoval = `-- name: StartManagedHostRemoval :one
UPDATE hosts SET status='draining', local_cleanup='pending', removal_generation=removal_generation+1,
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND connector_id=$4
  AND role='managed_host' AND status IN ('active','disabled','removal_failed','cleanup_unknown')
RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type StartManagedHostRemovalParams struct {
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	ResourceVersion int64         `json:"resource_version"`
	ConnectorID     uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) StartManagedHostRemoval(ctx context.Context, arg StartManagedHostRemovalParams) (Host, error) {
	row := q.db.QueryRow(ctx, startManagedHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceVersion,
		arg.ConnectorID,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const supersedeHostRemovalCommands = `-- name: SupersedeHostRemovalCommands :execrows
UPDATE connector_commands SET status='failed',error_code='CONNECTOR_COMMAND_SUPERSEDED',completed_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND operation_ref=$2 AND command_type='host_connector_removal'
  AND status IN ('delivery_unknown','result_unknown')
`

type SupersedeHostRemovalCommandsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OperationRef string    `json:"operation_ref"`
}

func (q *Queries) SupersedeHostRemovalCommands(ctx context.Context, arg SupersedeHostRemovalCommandsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeHostRemovalCommands, arg.EnterpriseID, arg.OperationRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeHostRemovalOperations = `-- name: SupersedeHostRemovalOperations :execrows
UPDATE host_removal_operations SET status='failed',error_code='HOST_REMOVAL_SUPERSEDED',completed_at=now(),
 lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE enterprise_id=$1 AND host_id=$2 AND status IN ('queued','running','awaiting_manual_execution','failed','cleanup_unknown')
`

type SupersedeHostRemovalOperationsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

func (q *Queries) SupersedeHostRemovalOperations(ctx context.Context, arg SupersedeHostRemovalOperationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeHostRemovalOperations, arg.EnterpriseID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const terminateRemoteAccessSessionsByHostRemoval = `-- name: TerminateRemoteAccessSessionsByHostRemoval :execrows
UPDATE remote_access_sessions SET status='terminating',session_fence=session_fence+1,
 termination_reason='host_removal',updated_at=now()
WHERE enterprise_id=$1 AND host_id=$2 AND status IN ('authorized','connecting','active')
`

type TerminateRemoteAccessSessionsByHostRemovalParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

func (q *Queries) TerminateRemoteAccessSessionsByHostRemoval(ctx context.Context, arg TerminateRemoteAccessSessionsByHostRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, terminateRemoteAccessSessionsByHostRemoval, arg.EnterpriseID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertHostManagedChangeJournal = `-- name: UpsertHostManagedChangeJournal :one
INSERT INTO host_managed_change_journals (id,enterprise_id,host_id,connector_id,change_type,before_state,applied_state,state_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (enterprise_id,host_id,change_type) WHERE status='active'
DO UPDATE SET connector_id=EXCLUDED.connector_id,before_state=EXCLUDED.before_state,applied_state=EXCLUDED.applied_state,
 state_hash=EXCLUDED.state_hash,updated_at=now() RETURNING id, enterprise_id, host_id, connector_id, change_type, before_state, applied_state, state_hash, status, restored_at, created_at, updated_at
`

type UpsertHostManagedChangeJournalParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
	ConnectorID  uuid.UUID `json:"connector_id"`
	ChangeType   string    `json:"change_type"`
	BeforeState  []byte    `json:"before_state"`
	AppliedState []byte    `json:"applied_state"`
	StateHash    []byte    `json:"state_hash"`
}

func (q *Queries) UpsertHostManagedChangeJournal(ctx context.Context, arg UpsertHostManagedChangeJournalParams) (HostManagedChangeJournal, error) {
	row := q.db.QueryRow(ctx, upsertHostManagedChangeJournal,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.ConnectorID,
		arg.ChangeType,
		arg.BeforeState,
		arg.AppliedState,
		arg.StateHash,
	)
	var i HostManagedChangeJournal
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.ChangeType,
		&i.BeforeState,
		&i.AppliedState,
		&i.StateHash,
		&i.Status,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostRemovalStep = `-- name: UpsertHostRemovalStep :one
INSERT INTO host_removal_operation_steps (operation_id,enterprise_id,stage,status,attempt,postcondition,result_hash,error_code,started_at,completed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $4='running' THEN now() ELSE NULL END,
 CASE WHEN $4 IN ('succeeded','failed','unknown') THEN now() ELSE NULL END)
ON CONFLICT (operation_id,stage) DO UPDATE SET status=EXCLUDED.status,attempt=EXCLUDED.attempt,
 postcondition=EXCLUDED.postcondition,result_hash=EXCLUDED.result_hash,error_code=EXCLUDED.error_code,
 started_at=COALESCE(host_removal_operation_steps.started_at,EXCLUDED.started_at),completed_at=EXCLUDED.completed_at,updated_at=now()
RETURNING operation_id, enterprise_id, stage, status, attempt, postcondition, result_hash, error_code, started_at, completed_at, updated_at
`

type UpsertHostRemovalStepParams struct {
	OperationID   uuid.UUID   `json:"operation_id"`
	EnterpriseID  uuid.UUID   `json:"enterprise_id"`
	Stage         string      `json:"stage"`
	Status        string      `json:"status"`
	Attempt       int32       `json:"attempt"`
	Postcondition []byte      `json:"postcondition"`
	ResultHash    []byte      `json:"result_hash"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) UpsertHostRemovalStep(ctx context.Context, arg UpsertHostRemovalStepParams) (HostRemovalOperationStep, error) {
	row := q.db.QueryRow(ctx, upsertHostRemovalStep,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Stage,
		arg.Status,
		arg.Attempt,
		arg.Postcondition,
		arg.ResultHash,
		arg.ErrorCode,
	)
	var i HostRemovalOperationStep
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.Stage,
		&i.Status,
		&i.Attempt,
		&i.Postcondition,
		&i.ResultHash,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
