// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_onboarding_operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceHostOnboardingOperation = `-- name: AdvanceHostOnboardingOperation :one
UPDATE host_onboarding_operations SET status='running',stage=$3,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('queued','running') RETURNING id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type AdvanceHostOnboardingOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Stage        string    `json:"stage"`
}

func (q *Queries) AdvanceHostOnboardingOperation(ctx context.Context, arg AdvanceHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, advanceHostOnboardingOperation, arg.ID, arg.EnterpriseID, arg.Stage)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelHostOnboardingOperationsByHost = `-- name: CancelHostOnboardingOperationsByHost :execrows
UPDATE host_onboarding_operations SET status='cancelled',error_code='HOST_ONBOARDING_CANCELLED_BY_DELETE',
 completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE host_id=$1 AND enterprise_id=$2 AND status IN ('queued','running','result_unknown')
`

type CancelHostOnboardingOperationsByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CancelHostOnboardingOperationsByHost(ctx context.Context, arg CancelHostOnboardingOperationsByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelHostOnboardingOperationsByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimBastionHostOnboardingOperations = `-- name: ClaimBastionHostOnboardingOperations :many
WITH claimed AS (
 SELECT id FROM host_onboarding_operations WHERE status='queued' AND ssh_path='bastion_connector' AND expires_at>now()
 ORDER BY created_at,id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE host_onboarding_operations operation SET status='running',stage='probing',attempts=attempts+1,lease_owner=$2,lease_expires_at=now()+interval '90 seconds',updated_at=now()
FROM claimed WHERE operation.id=claimed.id RETURNING operation.id, operation.enterprise_id, operation.host_id, operation.connector_id, operation.pending_action_id, operation.retry_of, operation.release_version_id, operation.connection_test_id, operation.install_method, operation.ssh_path, operation.target_platform, operation.control_path, operation.bastion_scope_id, operation.status, operation.stage, operation.plan, operation.plan_hash, operation.attempts, operation.lease_owner, operation.fence, operation.lease_expires_at, operation.error_code, operation.connector_online_at, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimBastionHostOnboardingOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimBastionHostOnboardingOperations(ctx context.Context, arg ClaimBastionHostOnboardingOperationsParams) ([]HostOnboardingOperation, error) {
	rows, err := q.db.Query(ctx, claimBastionHostOnboardingOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostOnboardingOperation{}
	for rows.Next() {
		var i HostOnboardingOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.ConnectorID,
			&i.PendingActionID,
			&i.RetryOf,
			&i.ReleaseVersionID,
			&i.ConnectionTestID,
			&i.InstallMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.BastionScopeID,
			&i.Status,
			&i.Stage,
			&i.Plan,
			&i.PlanHash,
			&i.Attempts,
			&i.LeaseOwner,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.ConnectorOnlineAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimHostOnboardingOperations = `-- name: ClaimHostOnboardingOperations :many
WITH claimed AS (
 SELECT id FROM host_onboarding_operations WHERE status='queued' AND ssh_path='direct_executor' AND expires_at>now()
 ORDER BY created_at,id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE host_onboarding_operations operation SET status='running',stage='probing',attempts=attempts+1,lease_owner=$2,lease_expires_at=now()+interval '90 seconds',updated_at=now()
FROM claimed WHERE operation.id=claimed.id RETURNING operation.id, operation.enterprise_id, operation.host_id, operation.connector_id, operation.pending_action_id, operation.retry_of, operation.release_version_id, operation.connection_test_id, operation.install_method, operation.ssh_path, operation.target_platform, operation.control_path, operation.bastion_scope_id, operation.status, operation.stage, operation.plan, operation.plan_hash, operation.attempts, operation.lease_owner, operation.fence, operation.lease_expires_at, operation.error_code, operation.connector_online_at, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimHostOnboardingOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimHostOnboardingOperations(ctx context.Context, arg ClaimHostOnboardingOperationsParams) ([]HostOnboardingOperation, error) {
	rows, err := q.db.Query(ctx, claimHostOnboardingOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostOnboardingOperation{}
	for rows.Next() {
		var i HostOnboardingOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.ConnectorID,
			&i.PendingActionID,
			&i.RetryOf,
			&i.ReleaseVersionID,
			&i.ConnectionTestID,
			&i.InstallMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.BastionScopeID,
			&i.Status,
			&i.Stage,
			&i.Plan,
			&i.PlanHash,
			&i.Attempts,
			&i.LeaseOwner,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.ConnectorOnlineAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeHostOnboardingOperation = `-- name: CompleteHostOnboardingOperation :one
UPDATE host_onboarding_operations SET status='succeeded',stage='completed',connector_online_at=now(),completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='running' RETURNING id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type CompleteHostOnboardingOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CompleteHostOnboardingOperation(ctx context.Context, arg CompleteHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, completeHostOnboardingOperation, arg.ID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeHostOnboardingOperationSecret = `-- name: ConsumeHostOnboardingOperationSecret :execrows
UPDATE host_onboarding_operation_secrets SET consumed_at=now() WHERE operation_id=$1 AND enterprise_id=$2 AND consumed_at IS NULL
`

type ConsumeHostOnboardingOperationSecretParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ConsumeHostOnboardingOperationSecret(ctx context.Context, arg ConsumeHostOnboardingOperationSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeHostOnboardingOperationSecret, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHostOnboardingOperation = `-- name: CreateHostOnboardingOperation :one
INSERT INTO host_onboarding_operations (id,enterprise_id,host_id,connector_id,pending_action_id,retry_of,release_version_id,connection_test_id,install_method,ssh_path,target_platform,control_path,bastion_scope_id,plan,plan_hash,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type CreateHostOnboardingOperationParams struct {
	ID               uuid.UUID          `json:"id"`
	EnterpriseID     uuid.UUID          `json:"enterprise_id"`
	HostID           uuid.UUID          `json:"host_id"`
	ConnectorID      uuid.UUID          `json:"connector_id"`
	PendingActionID  uuid.UUID          `json:"pending_action_id"`
	RetryOf          uuid.NullUUID      `json:"retry_of"`
	ReleaseVersionID uuid.UUID          `json:"release_version_id"`
	ConnectionTestID uuid.NullUUID      `json:"connection_test_id"`
	InstallMethod    string             `json:"install_method"`
	SshPath          string             `json:"ssh_path"`
	TargetPlatform   string             `json:"target_platform"`
	ControlPath      string             `json:"control_path"`
	BastionScopeID   uuid.NullUUID      `json:"bastion_scope_id"`
	Plan             []byte             `json:"plan"`
	PlanHash         []byte             `json:"plan_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHostOnboardingOperation(ctx context.Context, arg CreateHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, createHostOnboardingOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.ConnectorID,
		arg.PendingActionID,
		arg.RetryOf,
		arg.ReleaseVersionID,
		arg.ConnectionTestID,
		arg.InstallMethod,
		arg.SshPath,
		arg.TargetPlatform,
		arg.ControlPath,
		arg.BastionScopeID,
		arg.Plan,
		arg.PlanHash,
		arg.ExpiresAt,
	)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHostOnboardingOperationEvent = `-- name: CreateHostOnboardingOperationEvent :one
INSERT INTO host_onboarding_operation_events (id,operation_id,enterprise_id,sequence,stage,status,error_code)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at
`

type CreateHostOnboardingOperationEventParams struct {
	ID           uuid.UUID   `json:"id"`
	OperationID  uuid.UUID   `json:"operation_id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Sequence     int64       `json:"sequence"`
	Stage        string      `json:"stage"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateHostOnboardingOperationEvent(ctx context.Context, arg CreateHostOnboardingOperationEventParams) (HostOnboardingOperationEvent, error) {
	row := q.db.QueryRow(ctx, createHostOnboardingOperationEvent,
		arg.ID,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.Stage,
		arg.Status,
		arg.ErrorCode,
	)
	var i HostOnboardingOperationEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EnterpriseID,
		&i.Sequence,
		&i.Stage,
		&i.Status,
		&i.ErrorCode,
		&i.OccurredAt,
	)
	return i, err
}

const createHostOnboardingOperationSecret = `-- name: CreateHostOnboardingOperationSecret :one
INSERT INTO host_onboarding_operation_secrets (operation_id,enterprise_id,key_version,nonce,ciphertext,expires_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING operation_id, enterprise_id, key_version, nonce, ciphertext, expires_at, consumed_at, created_at
`

type CreateHostOnboardingOperationSecretParams struct {
	OperationID  uuid.UUID          `json:"operation_id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	KeyVersion   int32              `json:"key_version"`
	Nonce        []byte             `json:"nonce"`
	Ciphertext   []byte             `json:"ciphertext"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHostOnboardingOperationSecret(ctx context.Context, arg CreateHostOnboardingOperationSecretParams) (HostOnboardingOperationSecret, error) {
	row := q.db.QueryRow(ctx, createHostOnboardingOperationSecret,
		arg.OperationID,
		arg.EnterpriseID,
		arg.KeyVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.ExpiresAt,
	)
	var i HostOnboardingOperationSecret
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHostOnboardingOperationSecretsByHost = `-- name: DeleteHostOnboardingOperationSecretsByHost :execrows
DELETE FROM host_onboarding_operation_secrets secret
USING host_onboarding_operations operation
WHERE secret.operation_id=operation.id AND secret.enterprise_id=operation.enterprise_id
  AND operation.host_id=$1 AND operation.enterprise_id=$2
`

type DeleteHostOnboardingOperationSecretsByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteHostOnboardingOperationSecretsByHost(ctx context.Context, arg DeleteHostOnboardingOperationSecretsByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHostOnboardingOperationSecretsByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireHostOnboardingConnectorCommandsByHost = `-- name: ExpireHostOnboardingConnectorCommandsByHost :execrows
UPDATE connector_commands command SET status='expired',error_code='HOST_ONBOARDING_CANCELLED_BY_DELETE',completed_at=now(),updated_at=now()
WHERE command.enterprise_id=$2 AND command.status IN ('queued','dispatched','acknowledged','running','delivery_unknown','result_unknown')
  AND command.operation_ref IN (SELECT operation.id::text FROM host_onboarding_operations operation WHERE operation.host_id=$1 AND operation.enterprise_id=$2)
`

type ExpireHostOnboardingConnectorCommandsByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ExpireHostOnboardingConnectorCommandsByHost(ctx context.Context, arg ExpireHostOnboardingConnectorCommandsByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireHostOnboardingConnectorCommandsByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireHostOnboardingOperations = `-- name: ExpireHostOnboardingOperations :execrows
UPDATE host_onboarding_operations SET status='expired',error_code='HOST_ONBOARDING_EXPIRED',completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE status IN ('queued','running') AND expires_at<=now()
`

func (q *Queries) ExpireHostOnboardingOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireHostOnboardingOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failHostOnboardingOperation = `-- name: FailHostOnboardingOperation :one
UPDATE host_onboarding_operations SET status='failed',error_code=$3,completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('queued','running') RETURNING id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type FailHostOnboardingOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) FailHostOnboardingOperation(ctx context.Context, arg FailHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, failHostOnboardingOperation, arg.ID, arg.EnterpriseID, arg.ErrorCode)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveHostOnboardingOperationByConnector = `-- name: GetActiveHostOnboardingOperationByConnector :one
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations
WHERE connector_id=$1 AND enterprise_id=$2 AND status IN ('queued','running')
ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetActiveHostOnboardingOperationByConnectorParams struct {
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveHostOnboardingOperationByConnector(ctx context.Context, arg GetActiveHostOnboardingOperationByConnectorParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, getActiveHostOnboardingOperationByConnector, arg.ConnectorID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostOnboardingOperation = `-- name: GetHostOnboardingOperation :one
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations WHERE id=$1 AND enterprise_id=$2
`

type GetHostOnboardingOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetHostOnboardingOperation(ctx context.Context, arg GetHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, getHostOnboardingOperation, arg.ID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostOnboardingOperationSecret = `-- name: GetHostOnboardingOperationSecret :one
SELECT operation_id, enterprise_id, key_version, nonce, ciphertext, expires_at, consumed_at, created_at FROM host_onboarding_operation_secrets WHERE operation_id=$1 AND enterprise_id=$2 AND consumed_at IS NULL AND expires_at>now()
`

type GetHostOnboardingOperationSecretParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetHostOnboardingOperationSecret(ctx context.Context, arg GetHostOnboardingOperationSecretParams) (HostOnboardingOperationSecret, error) {
	row := q.db.QueryRow(ctx, getHostOnboardingOperationSecret, arg.OperationID, arg.EnterpriseID)
	var i HostOnboardingOperationSecret
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestHostOnboardingOperation = `-- name: GetLatestHostOnboardingOperation :one
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations WHERE host_id=$1 AND enterprise_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestHostOnboardingOperationParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestHostOnboardingOperation(ctx context.Context, arg GetLatestHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, getLatestHostOnboardingOperation, arg.HostID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestHostOnboardingOperationByConnector = `-- name: GetLatestHostOnboardingOperationByConnector :one
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations
WHERE host_id=$1 AND connector_id=$2 AND enterprise_id=$3
ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestHostOnboardingOperationByConnectorParams struct {
	HostID       uuid.UUID `json:"host_id"`
	ConnectorID  uuid.UUID `json:"connector_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestHostOnboardingOperationByConnector(ctx context.Context, arg GetLatestHostOnboardingOperationByConnectorParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, getLatestHostOnboardingOperationByConnector, arg.HostID, arg.ConnectorID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSuccessfulHostOnboardingOperation = `-- name: GetLatestSuccessfulHostOnboardingOperation :one
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations
WHERE host_id=$1 AND enterprise_id=$2 AND status='succeeded'
ORDER BY completed_at DESC NULLS LAST,created_at DESC,id DESC LIMIT 1
`

type GetLatestSuccessfulHostOnboardingOperationParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestSuccessfulHostOnboardingOperation(ctx context.Context, arg GetLatestSuccessfulHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, getLatestSuccessfulHostOnboardingOperation, arg.HostID, arg.EnterpriseID)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHostOnboardingOperationEvents = `-- name: ListHostOnboardingOperationEvents :many
SELECT id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at FROM host_onboarding_operation_events WHERE operation_id=$1 AND enterprise_id=$2 ORDER BY sequence
`

type ListHostOnboardingOperationEventsParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListHostOnboardingOperationEvents(ctx context.Context, arg ListHostOnboardingOperationEventsParams) ([]HostOnboardingOperationEvent, error) {
	rows, err := q.db.Query(ctx, listHostOnboardingOperationEvents, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostOnboardingOperationEvent{}
	for rows.Next() {
		var i HostOnboardingOperationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EnterpriseID,
			&i.Sequence,
			&i.Stage,
			&i.Status,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningBastionHostOnboardingOperations = `-- name: ListRunningBastionHostOnboardingOperations :many
SELECT id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at FROM host_onboarding_operations WHERE status='running' AND ssh_path='bastion_connector' ORDER BY updated_at,id
`

func (q *Queries) ListRunningBastionHostOnboardingOperations(ctx context.Context) ([]HostOnboardingOperation, error) {
	rows, err := q.db.Query(ctx, listRunningBastionHostOnboardingOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostOnboardingOperation{}
	for rows.Next() {
		var i HostOnboardingOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.HostID,
			&i.ConnectorID,
			&i.PendingActionID,
			&i.RetryOf,
			&i.ReleaseVersionID,
			&i.ConnectionTestID,
			&i.InstallMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.BastionScopeID,
			&i.Status,
			&i.Stage,
			&i.Plan,
			&i.PlanHash,
			&i.Attempts,
			&i.LeaseOwner,
			&i.Fence,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.ConnectorOnlineAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostControlTunnelsRemovedByHost = `-- name: MarkHostControlTunnelsRemovedByHost :execrows
UPDATE connector_control_tunnels SET status='removed',last_drop_reason='host_onboarding_cancelled_by_delete',epoch=epoch+1,
 lease_owner='',lease_expires_at=NULL,next_claim_at=NULL,updated_at=now()
WHERE host_id=$1 AND enterprise_id=$2 AND status<>'removed'
`

type MarkHostControlTunnelsRemovedByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkHostControlTunnelsRemovedByHost(ctx context.Context, arg MarkHostControlTunnelsRemovedByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, markHostControlTunnelsRemovedByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverHostOnboardingOperations = `-- name: RecoverHostOnboardingOperations :execrows
UPDATE host_onboarding_operations SET status='queued',lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE status='running' AND lease_expires_at<=now() AND attempts<3 AND expires_at>now()
`

func (q *Queries) RecoverHostOnboardingOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverHostOnboardingOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewHostOnboardingOperationLease = `-- name: RenewHostOnboardingOperationLease :execrows
UPDATE host_onboarding_operations SET lease_expires_at=now()+interval '90 seconds',updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='running' AND lease_owner=$3
`

type RenewHostOnboardingOperationLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	LeaseOwner   string    `json:"lease_owner"`
}

func (q *Queries) RenewHostOnboardingOperationLease(ctx context.Context, arg RenewHostOnboardingOperationLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewHostOnboardingOperationLease, arg.ID, arg.EnterpriseID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryHostOnboardingOperation = `-- name: RetryHostOnboardingOperation :one
UPDATE host_onboarding_operations SET status='queued',lease_owner='',lease_expires_at=NULL,error_code=$3,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='running' AND attempts<3 AND expires_at>now() RETURNING id, enterprise_id, host_id, connector_id, pending_action_id, retry_of, release_version_id, connection_test_id, install_method, ssh_path, target_platform, control_path, bastion_scope_id, status, stage, plan, plan_hash, attempts, lease_owner, fence, lease_expires_at, error_code, connector_online_at, expires_at, completed_at, created_at, updated_at
`

type RetryHostOnboardingOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) RetryHostOnboardingOperation(ctx context.Context, arg RetryHostOnboardingOperationParams) (HostOnboardingOperation, error) {
	row := q.db.QueryRow(ctx, retryHostOnboardingOperation, arg.ID, arg.EnterpriseID, arg.ErrorCode)
	var i HostOnboardingOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.PendingActionID,
		&i.RetryOf,
		&i.ReleaseVersionID,
		&i.ConnectionTestID,
		&i.InstallMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.BastionScopeID,
		&i.Status,
		&i.Stage,
		&i.Plan,
		&i.PlanHash,
		&i.Attempts,
		&i.LeaseOwner,
		&i.Fence,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.ConnectorOnlineAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeHostControlTunnelLeasesByHost = `-- name: RevokeHostControlTunnelLeasesByHost :execrows
UPDATE credential_leases lease SET status='revoked'
WHERE lease.enterprise_id=$2 AND lease.status='active' AND lease.operation_ref IN (
  SELECT 'connector_control_tunnel:'||tunnel.id::text FROM connector_control_tunnels tunnel WHERE tunnel.host_id=$1 AND tunnel.enterprise_id=$2
)
`

type RevokeHostControlTunnelLeasesByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeHostControlTunnelLeasesByHost(ctx context.Context, arg RevokeHostControlTunnelLeasesByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeHostControlTunnelLeasesByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeHostOnboardingCredentialLeasesByHost = `-- name: RevokeHostOnboardingCredentialLeasesByHost :execrows
UPDATE credential_leases lease SET status='revoked'
WHERE lease.enterprise_id=$2 AND lease.status='active' AND lease.operation_ref IN (
  SELECT operation.id::text FROM host_onboarding_operations operation WHERE operation.host_id=$1 AND operation.enterprise_id=$2
  UNION ALL
  SELECT 'host_onboarding:'||operation.id::text FROM host_onboarding_operations operation WHERE operation.host_id=$1 AND operation.enterprise_id=$2
)
`

type RevokeHostOnboardingCredentialLeasesByHostParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeHostOnboardingCredentialLeasesByHost(ctx context.Context, arg RevokeHostOnboardingCredentialLeasesByHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeHostOnboardingCredentialLeasesByHost, arg.HostID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setHostOnboardingRetryOf = `-- name: SetHostOnboardingRetryOf :exec
UPDATE host_onboarding_operations SET retry_of=$3 WHERE id=$1 AND enterprise_id=$2
`

type SetHostOnboardingRetryOfParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	RetryOf      uuid.NullUUID `json:"retry_of"`
}

func (q *Queries) SetHostOnboardingRetryOf(ctx context.Context, arg SetHostOnboardingRetryOfParams) error {
	_, err := q.db.Exec(ctx, setHostOnboardingRetryOf, arg.ID, arg.EnterpriseID, arg.RetryOf)
	return err
}
