// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_removal_operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceHostRemovalOperation = `-- name: AdvanceHostRemovalOperation :one
UPDATE host_removal_operations SET status=$3,stage=$4,error_code=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('queued','running','awaiting_manual_execution','failed','cleanup_unknown')
RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

type AdvanceHostRemovalOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Status       string    `json:"status"`
	Stage        string    `json:"stage"`
}

func (q *Queries) AdvanceHostRemovalOperation(ctx context.Context, arg AdvanceHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, advanceHostRemovalOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.Stage,
	)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimBastionHostRemovalOperations = `-- name: ClaimBastionHostRemovalOperations :many
WITH claimed AS (
 SELECT operation.id FROM host_removal_operations operation
 JOIN bastion_scopes scope ON scope.id=operation.bastion_scope_id AND scope.enterprise_id=operation.enterprise_id
 WHERE operation.status='queued' AND operation.delivery_method='ssh' AND operation.ssh_path='bastion_connector'
   AND operation.expires_at>now() AND scope.status='active' AND scope.active_connector_id IS NOT NULL
 ORDER BY operation.created_at,operation.id LIMIT $1 FOR UPDATE OF operation SKIP LOCKED
)
UPDATE host_removal_operations operation SET status='running',stage='terminating_sessions',attempts=attempts+1,
 lease_owner=$2,lease_expires_at=now()+interval '90 seconds',updated_at=now()
FROM claimed WHERE operation.id=claimed.id RETURNING operation.id, operation.enterprise_id, operation.pending_action_id, operation.target_type, operation.host_id, operation.bastion_scope_id, operation.connector_id, operation.removal_mode, operation.delivery_method, operation.ssh_path, operation.target_platform, operation.control_path, operation.connection_test_id, operation.credential_id, operation.credential_version, operation.pinned_host_key, operation.resource_version, operation.connector_version, operation.connection_epoch, operation.removal_generation, operation.trust_bundle_epoch, operation.plan, operation.plan_hash, operation.status, operation.stage, operation.attempts, operation.lease_owner, operation.lease_expires_at, operation.error_code, operation.local_cleanup, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimBastionHostRemovalOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimBastionHostRemovalOperations(ctx context.Context, arg ClaimBastionHostRemovalOperationsParams) ([]HostRemovalOperation, error) {
	rows, err := q.db.Query(ctx, claimBastionHostRemovalOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperation{}
	for rows.Next() {
		var i HostRemovalOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PendingActionID,
			&i.TargetType,
			&i.HostID,
			&i.BastionScopeID,
			&i.ConnectorID,
			&i.RemovalMode,
			&i.DeliveryMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.ConnectionTestID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.PinnedHostKey,
			&i.ResourceVersion,
			&i.ConnectorVersion,
			&i.ConnectionEpoch,
			&i.RemovalGeneration,
			&i.TrustBundleEpoch,
			&i.Plan,
			&i.PlanHash,
			&i.Status,
			&i.Stage,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.LocalCleanup,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDirectHostRemovalOperations = `-- name: ClaimDirectHostRemovalOperations :many
WITH claimed AS (
 SELECT id FROM host_removal_operations
 WHERE status='queued' AND delivery_method='ssh' AND ssh_path='direct_executor' AND expires_at>now()
 ORDER BY created_at,id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE host_removal_operations operation SET status='running',stage='terminating_sessions',attempts=attempts+1,
 lease_owner=$2,lease_expires_at=now()+interval '90 seconds',updated_at=now()
FROM claimed WHERE operation.id=claimed.id RETURNING operation.id, operation.enterprise_id, operation.pending_action_id, operation.target_type, operation.host_id, operation.bastion_scope_id, operation.connector_id, operation.removal_mode, operation.delivery_method, operation.ssh_path, operation.target_platform, operation.control_path, operation.connection_test_id, operation.credential_id, operation.credential_version, operation.pinned_host_key, operation.resource_version, operation.connector_version, operation.connection_epoch, operation.removal_generation, operation.trust_bundle_epoch, operation.plan, operation.plan_hash, operation.status, operation.stage, operation.attempts, operation.lease_owner, operation.lease_expires_at, operation.error_code, operation.local_cleanup, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimDirectHostRemovalOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimDirectHostRemovalOperations(ctx context.Context, arg ClaimDirectHostRemovalOperationsParams) ([]HostRemovalOperation, error) {
	rows, err := q.db.Query(ctx, claimDirectHostRemovalOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperation{}
	for rows.Next() {
		var i HostRemovalOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PendingActionID,
			&i.TargetType,
			&i.HostID,
			&i.BastionScopeID,
			&i.ConnectorID,
			&i.RemovalMode,
			&i.DeliveryMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.ConnectionTestID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.PinnedHostKey,
			&i.ResourceVersion,
			&i.ConnectorVersion,
			&i.ConnectionEpoch,
			&i.RemovalGeneration,
			&i.TrustBundleEpoch,
			&i.Plan,
			&i.PlanHash,
			&i.Status,
			&i.Stage,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.LocalCleanup,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimServerOnlyHostRemovalOperations = `-- name: ClaimServerOnlyHostRemovalOperations :many
WITH claimed AS (
 SELECT id FROM host_removal_operations
 WHERE status='queued' AND delivery_method='server_only' AND expires_at>now()
 ORDER BY created_at,id LIMIT $1 FOR UPDATE SKIP LOCKED
)
UPDATE host_removal_operations operation SET status='running',stage='terminating_sessions',attempts=attempts+1,
 lease_owner=$2,lease_expires_at=now()+interval '90 seconds',updated_at=now()
FROM claimed WHERE operation.id=claimed.id RETURNING operation.id, operation.enterprise_id, operation.pending_action_id, operation.target_type, operation.host_id, operation.bastion_scope_id, operation.connector_id, operation.removal_mode, operation.delivery_method, operation.ssh_path, operation.target_platform, operation.control_path, operation.connection_test_id, operation.credential_id, operation.credential_version, operation.pinned_host_key, operation.resource_version, operation.connector_version, operation.connection_epoch, operation.removal_generation, operation.trust_bundle_epoch, operation.plan, operation.plan_hash, operation.status, operation.stage, operation.attempts, operation.lease_owner, operation.lease_expires_at, operation.error_code, operation.local_cleanup, operation.expires_at, operation.completed_at, operation.created_at, operation.updated_at
`

type ClaimServerOnlyHostRemovalOperationsParams struct {
	Limit      int32  `json:"limit"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) ClaimServerOnlyHostRemovalOperations(ctx context.Context, arg ClaimServerOnlyHostRemovalOperationsParams) ([]HostRemovalOperation, error) {
	rows, err := q.db.Query(ctx, claimServerOnlyHostRemovalOperations, arg.Limit, arg.LeaseOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperation{}
	for rows.Next() {
		var i HostRemovalOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PendingActionID,
			&i.TargetType,
			&i.HostID,
			&i.BastionScopeID,
			&i.ConnectorID,
			&i.RemovalMode,
			&i.DeliveryMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.ConnectionTestID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.PinnedHostKey,
			&i.ResourceVersion,
			&i.ConnectorVersion,
			&i.ConnectionEpoch,
			&i.RemovalGeneration,
			&i.TrustBundleEpoch,
			&i.Plan,
			&i.PlanHash,
			&i.Status,
			&i.Stage,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.LocalCleanup,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeHostManagedChangeJournal = `-- name: CompleteHostManagedChangeJournal :execrows
UPDATE host_managed_change_journals SET status=$4,restored_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND host_id=$2 AND change_type=$3 AND status='active'
`

type CompleteHostManagedChangeJournalParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
	ChangeType   string    `json:"change_type"`
	Status       string    `json:"status"`
}

func (q *Queries) CompleteHostManagedChangeJournal(ctx context.Context, arg CompleteHostManagedChangeJournalParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeHostManagedChangeJournal,
		arg.EnterpriseID,
		arg.HostID,
		arg.ChangeType,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeHostRemovalOperation = `-- name: CompleteHostRemovalOperation :one
UPDATE host_removal_operations SET status='succeeded',stage='completed',local_cleanup=$3,error_code=$4,
 completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('running','awaiting_manual_execution','cleanup_unknown') RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

type CompleteHostRemovalOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	LocalCleanup string      `json:"local_cleanup"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) CompleteHostRemovalOperation(ctx context.Context, arg CompleteHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, completeHostRemovalOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.LocalCleanup,
		arg.ErrorCode,
	)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeHostRemovalToken = `-- name: ConsumeHostRemovalToken :execrows
UPDATE host_removal_tokens SET status='consumed',consumed_at=now()
WHERE id=$1 AND operation_id=$2 AND status='active' AND expires_at>now()
`

type ConsumeHostRemovalTokenParams struct {
	ID          uuid.UUID `json:"id"`
	OperationID uuid.UUID `json:"operation_id"`
}

func (q *Queries) ConsumeHostRemovalToken(ctx context.Context, arg ConsumeHostRemovalTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeHostRemovalToken, arg.ID, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createHostRemovalEvent = `-- name: CreateHostRemovalEvent :one
INSERT INTO host_removal_operation_events (id,operation_id,enterprise_id,sequence,stage,status,error_code)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at
`

type CreateHostRemovalEventParams struct {
	ID           uuid.UUID   `json:"id"`
	OperationID  uuid.UUID   `json:"operation_id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Sequence     int64       `json:"sequence"`
	Stage        string      `json:"stage"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateHostRemovalEvent(ctx context.Context, arg CreateHostRemovalEventParams) (HostRemovalOperationEvent, error) {
	row := q.db.QueryRow(ctx, createHostRemovalEvent,
		arg.ID,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.Stage,
		arg.Status,
		arg.ErrorCode,
	)
	var i HostRemovalOperationEvent
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EnterpriseID,
		&i.Sequence,
		&i.Stage,
		&i.Status,
		&i.ErrorCode,
		&i.OccurredAt,
	)
	return i, err
}

const createHostRemovalOperation = `-- name: CreateHostRemovalOperation :one
INSERT INTO host_removal_operations (
 id,enterprise_id,pending_action_id,target_type,host_id,bastion_scope_id,connector_id,removal_mode,
 delivery_method,ssh_path,target_platform,control_path,connection_test_id,credential_id,credential_version,
 pinned_host_key,resource_version,connector_version,connection_epoch,removal_generation,trust_bundle_epoch,
 plan,plan_hash,status,stage,expires_at
) VALUES (
 $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26
) RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

type CreateHostRemovalOperationParams struct {
	ID                uuid.UUID          `json:"id"`
	EnterpriseID      uuid.UUID          `json:"enterprise_id"`
	PendingActionID   uuid.UUID          `json:"pending_action_id"`
	TargetType        string             `json:"target_type"`
	HostID            uuid.UUID          `json:"host_id"`
	BastionScopeID    uuid.NullUUID      `json:"bastion_scope_id"`
	ConnectorID       uuid.UUID          `json:"connector_id"`
	RemovalMode       string             `json:"removal_mode"`
	DeliveryMethod    string             `json:"delivery_method"`
	SshPath           string             `json:"ssh_path"`
	TargetPlatform    string             `json:"target_platform"`
	ControlPath       string             `json:"control_path"`
	ConnectionTestID  uuid.NullUUID      `json:"connection_test_id"`
	CredentialID      uuid.NullUUID      `json:"credential_id"`
	CredentialVersion pgtype.Int8        `json:"credential_version"`
	PinnedHostKey     string             `json:"pinned_host_key"`
	ResourceVersion   int64              `json:"resource_version"`
	ConnectorVersion  int64              `json:"connector_version"`
	ConnectionEpoch   int64              `json:"connection_epoch"`
	RemovalGeneration int64              `json:"removal_generation"`
	TrustBundleEpoch  int64              `json:"trust_bundle_epoch"`
	Plan              []byte             `json:"plan"`
	PlanHash          []byte             `json:"plan_hash"`
	Status            string             `json:"status"`
	Stage             string             `json:"stage"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHostRemovalOperation(ctx context.Context, arg CreateHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, createHostRemovalOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.PendingActionID,
		arg.TargetType,
		arg.HostID,
		arg.BastionScopeID,
		arg.ConnectorID,
		arg.RemovalMode,
		arg.DeliveryMethod,
		arg.SshPath,
		arg.TargetPlatform,
		arg.ControlPath,
		arg.ConnectionTestID,
		arg.CredentialID,
		arg.CredentialVersion,
		arg.PinnedHostKey,
		arg.ResourceVersion,
		arg.ConnectorVersion,
		arg.ConnectionEpoch,
		arg.RemovalGeneration,
		arg.TrustBundleEpoch,
		arg.Plan,
		arg.PlanHash,
		arg.Status,
		arg.Stage,
		arg.ExpiresAt,
	)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHostRemovalToken = `-- name: CreateHostRemovalToken :one
INSERT INTO host_removal_tokens (id,operation_id,enterprise_id,purpose,token_hash,key_version,nonce,ciphertext,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id, operation_id, enterprise_id, purpose, token_hash, key_version, nonce, ciphertext, status, expires_at, consumed_at, created_at
`

type CreateHostRemovalTokenParams struct {
	ID           uuid.UUID          `json:"id"`
	OperationID  uuid.UUID          `json:"operation_id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	Purpose      string             `json:"purpose"`
	TokenHash    []byte             `json:"token_hash"`
	KeyVersion   int32              `json:"key_version"`
	Nonce        []byte             `json:"nonce"`
	Ciphertext   []byte             `json:"ciphertext"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHostRemovalToken(ctx context.Context, arg CreateHostRemovalTokenParams) (HostRemovalToken, error) {
	row := q.db.QueryRow(ctx, createHostRemovalToken,
		arg.ID,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Purpose,
		arg.TokenHash,
		arg.KeyVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.ExpiresAt,
	)
	var i HostRemovalToken
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EnterpriseID,
		&i.Purpose,
		&i.TokenHash,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUninstalledBastionHost = `-- name: DeleteUninstalledBastionHost :execrows
UPDATE hosts SET status='deleted',deleted_at=now(),resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND role='bastion' AND status='uninstalled'
`

type DeleteUninstalledBastionHostParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteUninstalledBastionHost(ctx context.Context, arg DeleteUninstalledBastionHostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUninstalledBastionHost, arg.ID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUninstalledBastionScope = `-- name: DeleteUninstalledBastionScope :one
UPDATE bastion_scopes scope SET status='deleted',deleted_at=now(),resource_version=scope.resource_version+1,updated_at=now()
WHERE scope.id=$1 AND scope.enterprise_id=$2 AND scope.resource_version=$3 AND scope.status='uninstalled'
  AND NOT EXISTS (SELECT 1 FROM hosts host WHERE host.enterprise_id=$2 AND host.bastion_scope_id=$1 AND host.role='managed_host' AND host.status<>'deleted')
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type DeleteUninstalledBastionScopeParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) DeleteUninstalledBastionScope(ctx context.Context, arg DeleteUninstalledBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, deleteUninstalledBastionScope, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const deleteUninstalledManagedHost = `-- name: DeleteUninstalledManagedHost :one
UPDATE hosts SET status='deleted',deleted_at=now(),resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND role='managed_host' AND status='uninstalled'
RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type DeleteUninstalledManagedHostParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) DeleteUninstalledManagedHost(ctx context.Context, arg DeleteUninstalledManagedHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, deleteUninstalledManagedHost, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const expireHostRemovalOperations = `-- name: ExpireHostRemovalOperations :many
UPDATE host_removal_operations SET status=CASE WHEN status='running' THEN 'cleanup_unknown' ELSE 'failed' END,
 error_code='HOST_REMOVAL_EXPIRED',local_cleanup='unknown',
 completed_at=now(),lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE status IN ('queued','running','awaiting_manual_execution') AND expires_at<=now() RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

func (q *Queries) ExpireHostRemovalOperations(ctx context.Context) ([]HostRemovalOperation, error) {
	rows, err := q.db.Query(ctx, expireHostRemovalOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperation{}
	for rows.Next() {
		var i HostRemovalOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PendingActionID,
			&i.TargetType,
			&i.HostID,
			&i.BastionScopeID,
			&i.ConnectorID,
			&i.RemovalMode,
			&i.DeliveryMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.ConnectionTestID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.PinnedHostKey,
			&i.ResourceVersion,
			&i.ConnectorVersion,
			&i.ConnectionEpoch,
			&i.RemovalGeneration,
			&i.TrustBundleEpoch,
			&i.Plan,
			&i.PlanHash,
			&i.Status,
			&i.Stage,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.LocalCleanup,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failHostRemovalOperation = `-- name: FailHostRemovalOperation :one
UPDATE host_removal_operations SET status=$3,error_code=$4,local_cleanup=$5,completed_at=now(),
 lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('queued','running','awaiting_manual_execution') RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

type FailHostRemovalOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	Status       string      `json:"status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	LocalCleanup string      `json:"local_cleanup"`
}

func (q *Queries) FailHostRemovalOperation(ctx context.Context, arg FailHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, failHostRemovalOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.ErrorCode,
		arg.LocalCleanup,
	)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeHostConnectorRemoval = `-- name: FinalizeHostConnectorRemoval :execrows
UPDATE connectors SET status='uninstalled',connection_epoch=connection_epoch+1,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$3 AND status<>'revoked'
`

type FinalizeHostConnectorRemovalParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) FinalizeHostConnectorRemoval(ctx context.Context, arg FinalizeHostConnectorRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeHostConnectorRemoval, arg.ID, arg.EnterpriseID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forceForgetBastionScope = `-- name: ForceForgetBastionScope :one
UPDATE bastion_scopes scope SET status='deleted',local_cleanup='unknown',relay_status='offline',deleted_at=now(),
 removal_generation=scope.removal_generation+1,resource_version=scope.resource_version+1,updated_at=now()
WHERE scope.id=$1 AND scope.enterprise_id=$2 AND scope.resource_version=$3
  AND scope.status IN ('offline','removal_failed','cleanup_unknown')
  AND NOT EXISTS (SELECT 1 FROM hosts host WHERE host.enterprise_id=$2 AND host.bastion_scope_id=$1 AND host.role='managed_host' AND host.status<>'deleted')
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type ForceForgetBastionScopeParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) ForceForgetBastionScope(ctx context.Context, arg ForceForgetBastionScopeParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, forceForgetBastionScope, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const forceForgetManagedHost = `-- name: ForceForgetManagedHost :one
UPDATE hosts SET status='deleted',local_cleanup='unknown',connection_status='offline',deleted_at=now(),
 removal_generation=removal_generation+1,resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND role='managed_host'
  AND (connection_status='offline' OR status IN ('removal_failed','cleanup_unknown')) RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type ForceForgetManagedHostParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ResourceVersion int64     `json:"resource_version"`
}

func (q *Queries) ForceForgetManagedHost(ctx context.Context, arg ForceForgetManagedHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, forceForgetManagedHost, arg.ID, arg.EnterpriseID, arg.ResourceVersion)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const getActiveHostManagedChangeJournal = `-- name: GetActiveHostManagedChangeJournal :one
SELECT id, enterprise_id, host_id, connector_id, change_type, before_state, applied_state, state_hash, status, restored_at, created_at, updated_at FROM host_managed_change_journals WHERE enterprise_id=$1 AND host_id=$2 AND change_type=$3 AND status='active'
`

type GetActiveHostManagedChangeJournalParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
	ChangeType   string    `json:"change_type"`
}

func (q *Queries) GetActiveHostManagedChangeJournal(ctx context.Context, arg GetActiveHostManagedChangeJournalParams) (HostManagedChangeJournal, error) {
	row := q.db.QueryRow(ctx, getActiveHostManagedChangeJournal, arg.EnterpriseID, arg.HostID, arg.ChangeType)
	var i HostManagedChangeJournal
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.ChangeType,
		&i.BeforeState,
		&i.AppliedState,
		&i.StateHash,
		&i.Status,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveHostRemovalToken = `-- name: GetActiveHostRemovalToken :one
SELECT id, operation_id, enterprise_id, purpose, token_hash, key_version, nonce, ciphertext, status, expires_at, consumed_at, created_at FROM host_removal_tokens
WHERE token_hash=$1 AND ((status='active' AND expires_at>now()) OR status='consumed') FOR UPDATE
`

func (q *Queries) GetActiveHostRemovalToken(ctx context.Context, tokenHash []byte) (HostRemovalToken, error) {
	row := q.db.QueryRow(ctx, getActiveHostRemovalToken, tokenHash)
	var i HostRemovalToken
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.EnterpriseID,
		&i.Purpose,
		&i.TokenHash,
		&i.KeyVersion,
		&i.Nonce,
		&i.Ciphertext,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHostRemovalOperation = `-- name: GetHostRemovalOperation :one
SELECT id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at FROM host_removal_operations WHERE id=$1 AND enterprise_id=$2
`

type GetHostRemovalOperationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetHostRemovalOperation(ctx context.Context, arg GetHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, getHostRemovalOperation, arg.ID, arg.EnterpriseID)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostRemovalOperationForUpdate = `-- name: GetHostRemovalOperationForUpdate :one
SELECT id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at FROM host_removal_operations WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type GetHostRemovalOperationForUpdateParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetHostRemovalOperationForUpdate(ctx context.Context, arg GetHostRemovalOperationForUpdateParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, getHostRemovalOperationForUpdate, arg.ID, arg.EnterpriseID)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestHostRemovalOperation = `-- name: GetLatestHostRemovalOperation :one
SELECT id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at FROM host_removal_operations WHERE host_id=$1 AND enterprise_id=$2
ORDER BY created_at DESC,id DESC LIMIT 1
`

type GetLatestHostRemovalOperationParams struct {
	HostID       uuid.UUID `json:"host_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetLatestHostRemovalOperation(ctx context.Context, arg GetLatestHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, getLatestHostRemovalOperation, arg.HostID, arg.EnterpriseID)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateHostTelemetryForRemoval = `-- name: InvalidateHostTelemetryForRemoval :execrows
WITH affected AS (
 UPDATE collector_instances SET status='uninstalled',version=version+1,updated_at=now()
 WHERE enterprise_id=$1 AND resource_type='host' AND resource_id=$2 AND status<>'uninstalled'
 RETURNING id
)
UPDATE telemetry_routes route SET status='invalidated',version=route.version+1,updated_at=now()
WHERE route.enterprise_id=$1 AND (route.collector_id IN (SELECT affected.id FROM affected) OR route.gateway_collector_id IN (SELECT affected.id FROM affected))
`

type InvalidateHostTelemetryForRemovalParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) InvalidateHostTelemetryForRemoval(ctx context.Context, arg InvalidateHostTelemetryForRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateHostTelemetryForRemoval, arg.EnterpriseID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBastionRemovalDependencies = `-- name: ListBastionRemovalDependencies :many
SELECT 'member_host'::text AS dependency_type, host.id AS dependency_id, host.name::text AS name,
       host.control_path::text AS reason
FROM hosts host WHERE host.enterprise_id=$1 AND host.bastion_scope_id=$2 AND host.role='managed_host' AND host.status<>'deleted'
UNION ALL
SELECT 'onboarding_operation'::text, operation.id, operation.ssh_path::text, operation.status::text
FROM host_onboarding_operations operation WHERE operation.enterprise_id=$1 AND operation.bastion_scope_id=$2
  AND operation.status IN ('queued','running')
UNION ALL
SELECT 'removal_operation'::text, operation.id, operation.ssh_path::text, operation.status::text
FROM host_removal_operations operation JOIN hosts host ON host.id=operation.host_id AND host.enterprise_id=operation.enterprise_id
WHERE operation.enterprise_id=$1 AND host.bastion_scope_id=$2
  AND host.role='managed_host'
  AND operation.status IN ('queued','running','awaiting_manual_execution','cleanup_unknown')
UNION ALL
SELECT 'collector'::text, collector.id, collector.role::text, collector.status::text
FROM collector_instances collector
WHERE collector.enterprise_id=$1 AND collector.resource_type='host' AND collector.resource_id=$3 AND collector.status<>'uninstalled'
UNION ALL
SELECT 'telemetry_route'::text, route.id, collector.role::text, route.status::text
FROM telemetry_routes route JOIN collector_instances collector ON collector.id=route.collector_id AND collector.enterprise_id=route.enterprise_id
WHERE route.enterprise_id=$1 AND (collector.resource_id=$3 OR route.gateway_collector_id IN (
  SELECT id FROM collector_instances WHERE enterprise_id=$1 AND resource_type='host' AND resource_id=$3
)) AND route.status<>'invalidated'
UNION ALL
SELECT 'remote_session'::text, session.id, session.protocol::text, session.status::text
FROM remote_access_sessions session JOIN hosts host ON host.id=session.host_id AND host.enterprise_id=session.enterprise_id
WHERE session.enterprise_id=$1 AND host.bastion_scope_id=$2 AND session.status IN ('authorized','connecting','active','terminating')
UNION ALL
SELECT 'connector_command'::text, command.id, command.command_type::text, command.status::text
FROM connector_commands command JOIN bastion_scopes scope ON scope.active_connector_id=command.connector_id AND scope.enterprise_id=command.enterprise_id
WHERE command.enterprise_id=$1 AND scope.id=$2 AND command.status IN ('queued','dispatched','acknowledged','running','delivery_unknown','result_unknown')
UNION ALL
SELECT 'credential_lease'::text, lease.id, lease.protocol::text, lease.status::text
FROM credential_leases lease JOIN bastion_scopes scope ON scope.enterprise_id=lease.enterprise_id AND scope.active_connector_id::text=lease.recipient_id
WHERE lease.enterprise_id=$1 AND scope.id=$2 AND lease.recipient_type='connector' AND lease.status='active' AND lease.expires_at>now()
UNION ALL
SELECT 'control_tunnel'::text, tunnel.id, tunnel.target_address::text, tunnel.status::text
FROM connector_control_tunnels tunnel WHERE tunnel.enterprise_id=$1 AND tunnel.bastion_scope_id=$2
  AND tunnel.host_id<>$3 AND tunnel.status<>'removed'
UNION ALL
SELECT 'telemetry_tunnel'::text, tunnel.id, tunnel.target_address::text, tunnel.status::text
FROM telemetry_tunnels tunnel
LEFT JOIN hosts host ON host.id=tunnel.host_id AND host.enterprise_id=tunnel.enterprise_id
WHERE tunnel.enterprise_id=$1 AND tunnel.status<>'removed' AND (
  tunnel.host_id=$3 OR host.bastion_scope_id=$2 OR tunnel.connector_id=(
    SELECT active_connector_id FROM bastion_scopes WHERE enterprise_id=$1 AND id=$2
  )
)
UNION ALL
SELECT 'collector_operation'::text, operation.id, operation.operation::text, operation.status::text
FROM telemetry_collector_operations operation
JOIN collector_instances collector ON collector.id=operation.collector_id AND collector.enterprise_id=operation.enterprise_id
LEFT JOIN hosts host ON host.id=collector.resource_id AND host.enterprise_id=collector.enterprise_id AND collector.resource_type='host'
WHERE operation.enterprise_id=$1 AND operation.status IN ('queued','running','result_unknown')
  AND collector.resource_type='host' AND (collector.resource_id=$3 OR host.bastion_scope_id=$2)
`

type ListBastionRemovalDependenciesParams struct {
	EnterpriseID   uuid.UUID     `json:"enterprise_id"`
	BastionScopeID uuid.NullUUID `json:"bastion_scope_id"`
	ResourceID     uuid.UUID     `json:"resource_id"`
}

type ListBastionRemovalDependenciesRow struct {
	DependencyType string    `json:"dependency_type"`
	DependencyID   uuid.UUID `json:"dependency_id"`
	Name           string    `json:"name"`
	Reason         string    `json:"reason"`
}

func (q *Queries) ListBastionRemovalDependencies(ctx context.Context, arg ListBastionRemovalDependenciesParams) ([]ListBastionRemovalDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listBastionRemovalDependencies, arg.EnterpriseID, arg.BastionScopeID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBastionRemovalDependenciesRow{}
	for rows.Next() {
		var i ListBastionRemovalDependenciesRow
		if err := rows.Scan(
			&i.DependencyType,
			&i.DependencyID,
			&i.Name,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostRemovalDependencies = `-- name: ListHostRemovalDependencies :many
SELECT 'remote_session'::text AS dependency_type, session.id AS dependency_id,
       session.protocol::text AS name, session.status::text AS reason
FROM remote_access_sessions session
WHERE session.enterprise_id=$1 AND session.host_id=$2 AND session.status IN ('authorized','connecting','active','terminating')
UNION ALL
SELECT 'collector'::text, collector.id, collector.role::text, collector.status::text
FROM collector_instances collector
WHERE collector.enterprise_id=$1 AND collector.resource_type='host' AND collector.resource_id=$2
  AND collector.status<>'uninstalled'
UNION ALL
SELECT 'control_tunnel'::text, tunnel.id, tunnel.target_address::text, tunnel.status::text
FROM connector_control_tunnels tunnel
WHERE tunnel.enterprise_id=$1 AND tunnel.host_id=$2 AND tunnel.status<>'removed'
UNION ALL
SELECT 'telemetry_tunnel'::text, tunnel.id, tunnel.target_address::text, tunnel.status::text
FROM telemetry_tunnels tunnel
WHERE tunnel.enterprise_id=$1 AND tunnel.host_id=$2 AND tunnel.status<>'removed'
UNION ALL
SELECT 'collector_operation'::text, operation.id, operation.operation::text, operation.status::text
FROM telemetry_collector_operations operation
JOIN collector_instances collector ON collector.id=operation.collector_id AND collector.enterprise_id=operation.enterprise_id
WHERE operation.enterprise_id=$1 AND collector.resource_type='host' AND collector.resource_id=$2
  AND operation.status IN ('queued','running','result_unknown')
`

type ListHostRemovalDependenciesParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

type ListHostRemovalDependenciesRow struct {
	DependencyType string    `json:"dependency_type"`
	DependencyID   uuid.UUID `json:"dependency_id"`
	Name           string    `json:"name"`
	Reason         string    `json:"reason"`
}

func (q *Queries) ListHostRemovalDependencies(ctx context.Context, arg ListHostRemovalDependenciesParams) ([]ListHostRemovalDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listHostRemovalDependencies, arg.EnterpriseID, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostRemovalDependenciesRow{}
	for rows.Next() {
		var i ListHostRemovalDependenciesRow
		if err := rows.Scan(
			&i.DependencyType,
			&i.DependencyID,
			&i.Name,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostRemovalEvents = `-- name: ListHostRemovalEvents :many
SELECT id, operation_id, enterprise_id, sequence, stage, status, error_code, occurred_at FROM host_removal_operation_events WHERE operation_id=$1 AND enterprise_id=$2 ORDER BY sequence
`

type ListHostRemovalEventsParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListHostRemovalEvents(ctx context.Context, arg ListHostRemovalEventsParams) ([]HostRemovalOperationEvent, error) {
	rows, err := q.db.Query(ctx, listHostRemovalEvents, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperationEvent{}
	for rows.Next() {
		var i HostRemovalOperationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.EnterpriseID,
			&i.Sequence,
			&i.Stage,
			&i.Status,
			&i.ErrorCode,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostRemovalSteps = `-- name: ListHostRemovalSteps :many
SELECT operation_id, enterprise_id, stage, status, attempt, postcondition, result_hash, error_code, started_at, completed_at, updated_at FROM host_removal_operation_steps WHERE operation_id=$1 AND enterprise_id=$2 ORDER BY updated_at,stage
`

type ListHostRemovalStepsParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListHostRemovalSteps(ctx context.Context, arg ListHostRemovalStepsParams) ([]HostRemovalOperationStep, error) {
	rows, err := q.db.Query(ctx, listHostRemovalSteps, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperationStep{}
	for rows.Next() {
		var i HostRemovalOperationStep
		if err := rows.Scan(
			&i.OperationID,
			&i.EnterpriseID,
			&i.Stage,
			&i.Status,
			&i.Attempt,
			&i.Postcondition,
			&i.ResultHash,
			&i.ErrorCode,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningBastionHostRemovalOperations = `-- name: ListRunningBastionHostRemovalOperations :many
SELECT id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at FROM host_removal_operations
WHERE status='running' AND delivery_method='ssh' AND ssh_path='bastion_connector'
ORDER BY updated_at,id
`

func (q *Queries) ListRunningBastionHostRemovalOperations(ctx context.Context) ([]HostRemovalOperation, error) {
	rows, err := q.db.Query(ctx, listRunningBastionHostRemovalOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostRemovalOperation{}
	for rows.Next() {
		var i HostRemovalOperation
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.PendingActionID,
			&i.TargetType,
			&i.HostID,
			&i.BastionScopeID,
			&i.ConnectorID,
			&i.RemovalMode,
			&i.DeliveryMethod,
			&i.SshPath,
			&i.TargetPlatform,
			&i.ControlPath,
			&i.ConnectionTestID,
			&i.CredentialID,
			&i.CredentialVersion,
			&i.PinnedHostKey,
			&i.ResourceVersion,
			&i.ConnectorVersion,
			&i.ConnectionEpoch,
			&i.RemovalGeneration,
			&i.TrustBundleEpoch,
			&i.Plan,
			&i.PlanHash,
			&i.Status,
			&i.Stage,
			&i.Attempts,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.ErrorCode,
			&i.LocalCleanup,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRemovalBastionHostTerminal = `-- name: MarkRemovalBastionHostTerminal :execrows
UPDATE hosts SET status=$5,local_cleanup=$6,connection_status='offline',resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND removal_generation=$4
  AND role='bastion' AND status IN ('draining','uninstalling','removal_failed','cleanup_unknown')
`

type MarkRemovalBastionHostTerminalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
	Status            string        `json:"status"`
	LocalCleanup      string        `json:"local_cleanup"`
}

func (q *Queries) MarkRemovalBastionHostTerminal(ctx context.Context, arg MarkRemovalBastionHostTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRemovalBastionHostTerminal,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
		arg.Status,
		arg.LocalCleanup,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRemovalBastionTerminal = `-- name: MarkRemovalBastionTerminal :execrows
UPDATE bastion_scopes SET status=$5, local_cleanup=$6, relay_status='offline',
 active_connector_id=CASE WHEN $5='uninstalled' THEN NULL ELSE active_connector_id END,
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND active_connector_id=$3 AND removal_generation=$4
  AND status IN ('draining','uninstalling','removal_failed','cleanup_unknown')
`

type MarkRemovalBastionTerminalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
	Status            string        `json:"status"`
	LocalCleanup      string        `json:"local_cleanup"`
}

func (q *Queries) MarkRemovalBastionTerminal(ctx context.Context, arg MarkRemovalBastionTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRemovalBastionTerminal,
		arg.ID,
		arg.EnterpriseID,
		arg.ActiveConnectorID,
		arg.RemovalGeneration,
		arg.Status,
		arg.LocalCleanup,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRemovalBastionUninstalling = `-- name: MarkRemovalBastionUninstalling :execrows
UPDATE bastion_scopes SET status='uninstalling', resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND active_connector_id=$3 AND removal_generation=$4
  AND status IN ('draining','uninstalling')
`

type MarkRemovalBastionUninstallingParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) MarkRemovalBastionUninstalling(ctx context.Context, arg MarkRemovalBastionUninstallingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRemovalBastionUninstalling,
		arg.ID,
		arg.EnterpriseID,
		arg.ActiveConnectorID,
		arg.RemovalGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRemovalHostTerminal = `-- name: MarkRemovalHostTerminal :execrows
UPDATE hosts SET status=$5, local_cleanup=$6, connection_status='offline',
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND removal_generation=$4
  AND status IN ('draining','uninstalling','removal_failed','cleanup_unknown')
`

type MarkRemovalHostTerminalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
	Status            string        `json:"status"`
	LocalCleanup      string        `json:"local_cleanup"`
}

func (q *Queries) MarkRemovalHostTerminal(ctx context.Context, arg MarkRemovalHostTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRemovalHostTerminal,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
		arg.Status,
		arg.LocalCleanup,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRemovalHostUninstalling = `-- name: MarkRemovalHostUninstalling :execrows
UPDATE hosts SET status='uninstalling', resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND removal_generation=$4
  AND status IN ('draining','uninstalling')
`

type MarkRemovalHostUninstallingParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) MarkRemovalHostUninstalling(ctx context.Context, arg MarkRemovalHostUninstallingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRemovalHostUninstalling,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextHostRemovalEventSequence = `-- name: NextHostRemovalEventSequence :one
SELECT COALESCE(max(sequence),0)::bigint+1 FROM host_removal_operation_events WHERE operation_id=$1
`

func (q *Queries) NextHostRemovalEventSequence(ctx context.Context, operationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextHostRemovalEventSequence, operationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recoverHostRemovalOperations = `-- name: RecoverHostRemovalOperations :execrows
UPDATE host_removal_operations SET status='queued',lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE status='running' AND delivery_method<>'manual' AND lease_expires_at<=now() AND attempts<10 AND expires_at>now()
`

func (q *Queries) RecoverHostRemovalOperations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverHostRemovalOperations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewHostRemovalOperationLease = `-- name: RenewHostRemovalOperationLease :execrows
UPDATE host_removal_operations SET lease_expires_at=now()+interval '90 seconds',updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='running' AND lease_owner=$3
`

type RenewHostRemovalOperationLeaseParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	LeaseOwner   string    `json:"lease_owner"`
}

func (q *Queries) RenewHostRemovalOperationLease(ctx context.Context, arg RenewHostRemovalOperationLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewHostRemovalOperationLease, arg.ID, arg.EnterpriseID, arg.LeaseOwner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumeBastionRootHostRemoval = `-- name: ResumeBastionRootHostRemoval :execrows
UPDATE hosts SET status='draining',local_cleanup='pending',resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND removal_generation=$4
  AND role='bastion' AND status IN ('removal_failed','cleanup_unknown')
`

type ResumeBastionRootHostRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) ResumeBastionRootHostRemoval(ctx context.Context, arg ResumeBastionRootHostRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeBastionRootHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumeBastionScopeRemoval = `-- name: ResumeBastionScopeRemoval :execrows
UPDATE bastion_scopes SET status='draining',local_cleanup='pending',resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND active_connector_id=$3 AND removal_generation=$4
  AND status IN ('removal_failed','cleanup_unknown')
`

type ResumeBastionScopeRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) ResumeBastionScopeRemoval(ctx context.Context, arg ResumeBastionScopeRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeBastionScopeRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ActiveConnectorID,
		arg.RemovalGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumeManagedHostRemoval = `-- name: ResumeManagedHostRemoval :execrows
UPDATE hosts SET status='draining',local_cleanup='pending',resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND removal_generation=$4
  AND status IN ('removal_failed','cleanup_unknown')
`

type ResumeManagedHostRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) ResumeManagedHostRemoval(ctx context.Context, arg ResumeManagedHostRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, resumeManagedHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryHostRemovalOperation = `-- name: RetryHostRemovalOperation :one
UPDATE host_removal_operations SET status=$3,stage=$4,error_code=NULL,completed_at=NULL,
 lease_owner='',lease_expires_at=NULL,expires_at=$5,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status IN ('failed','cleanup_unknown','awaiting_manual_execution') AND attempts<10 RETURNING id, enterprise_id, pending_action_id, target_type, host_id, bastion_scope_id, connector_id, removal_mode, delivery_method, ssh_path, target_platform, control_path, connection_test_id, credential_id, credential_version, pinned_host_key, resource_version, connector_version, connection_epoch, removal_generation, trust_bundle_epoch, plan, plan_hash, status, stage, attempts, lease_owner, lease_expires_at, error_code, local_cleanup, expires_at, completed_at, created_at, updated_at
`

type RetryHostRemovalOperationParams struct {
	ID           uuid.UUID          `json:"id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	Status       string             `json:"status"`
	Stage        string             `json:"stage"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RetryHostRemovalOperation(ctx context.Context, arg RetryHostRemovalOperationParams) (HostRemovalOperation, error) {
	row := q.db.QueryRow(ctx, retryHostRemovalOperation,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.Stage,
		arg.ExpiresAt,
	)
	var i HostRemovalOperation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.PendingActionID,
		&i.TargetType,
		&i.HostID,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.RemovalMode,
		&i.DeliveryMethod,
		&i.SshPath,
		&i.TargetPlatform,
		&i.ControlPath,
		&i.ConnectionTestID,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.PinnedHostKey,
		&i.ResourceVersion,
		&i.ConnectorVersion,
		&i.ConnectionEpoch,
		&i.RemovalGeneration,
		&i.TrustBundleEpoch,
		&i.Plan,
		&i.PlanHash,
		&i.Status,
		&i.Stage,
		&i.Attempts,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.ErrorCode,
		&i.LocalCleanup,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeHostRemovalCredentialLeases = `-- name: RevokeHostRemovalCredentialLeases :execrows
UPDATE credential_leases SET status='revoked'
WHERE enterprise_id=$1 AND target_resource_type='host' AND target_resource_id=$2 AND status='active'
`

type RevokeHostRemovalCredentialLeasesParams struct {
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	TargetResourceID uuid.UUID `json:"target_resource_id"`
}

func (q *Queries) RevokeHostRemovalCredentialLeases(ctx context.Context, arg RevokeHostRemovalCredentialLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeHostRemovalCredentialLeases, arg.EnterpriseID, arg.TargetResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeHostRemovalTokens = `-- name: RevokeHostRemovalTokens :execrows
UPDATE host_removal_tokens SET status='revoked'
WHERE operation_id=$1 AND enterprise_id=$2 AND status='active'
`

type RevokeHostRemovalTokensParams struct {
	OperationID  uuid.UUID `json:"operation_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) RevokeHostRemovalTokens(ctx context.Context, arg RevokeHostRemovalTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeHostRemovalTokens, arg.OperationID, arg.EnterpriseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRemovalConnectorCommands = `-- name: RevokeRemovalConnectorCommands :execrows
UPDATE connector_commands SET status='expired',error_code='HOST_REMOVAL_DRAINING',completed_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND connector_id=$2 AND status IN ('queued','dispatched','acknowledged','running')
`

type RevokeRemovalConnectorCommandsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ConnectorID  uuid.UUID `json:"connector_id"`
}

func (q *Queries) RevokeRemovalConnectorCommands(ctx context.Context, arg RevokeRemovalConnectorCommandsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRemovalConnectorCommands, arg.EnterpriseID, arg.ConnectorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startBastionRootHostRemoval = `-- name: StartBastionRootHostRemoval :one
UPDATE hosts SET status='draining',local_cleanup='pending',removal_generation=$4,
 resource_version=resource_version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND connector_id=$3 AND role='bastion'
  AND status IN ('active','disabled','removal_failed','cleanup_unknown') RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type StartBastionRootHostRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ConnectorID       uuid.NullUUID `json:"connector_id"`
	RemovalGeneration int64         `json:"removal_generation"`
}

func (q *Queries) StartBastionRootHostRemoval(ctx context.Context, arg StartBastionRootHostRemovalParams) (Host, error) {
	row := q.db.QueryRow(ctx, startBastionRootHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ConnectorID,
		arg.RemovalGeneration,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const startBastionScopeRemoval = `-- name: StartBastionScopeRemoval :one
UPDATE bastion_scopes SET status='draining', local_cleanup='pending', removal_generation=removal_generation+1,
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND active_connector_id=$4
  AND status IN ('active','suspected_offline','offline','removal_failed','cleanup_unknown')
RETURNING id, enterprise_id, name, environment, labels, labels_hash, status, connector_host_id, active_connector_id, fencing_generation, resource_version, deleted_at, created_at, updated_at, onboarding_mode, relay_address, relay_https_port, relay_gateway_port, relay_port_generation, relay_status, relay_error_code, removal_generation, local_cleanup
`

type StartBastionScopeRemovalParams struct {
	ID                uuid.UUID     `json:"id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	ResourceVersion   int64         `json:"resource_version"`
	ActiveConnectorID uuid.NullUUID `json:"active_connector_id"`
}

func (q *Queries) StartBastionScopeRemoval(ctx context.Context, arg StartBastionScopeRemovalParams) (BastionScope, error) {
	row := q.db.QueryRow(ctx, startBastionScopeRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceVersion,
		arg.ActiveConnectorID,
	)
	var i BastionScope
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.Status,
		&i.ConnectorHostID,
		&i.ActiveConnectorID,
		&i.FencingGeneration,
		&i.ResourceVersion,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnboardingMode,
		&i.RelayAddress,
		&i.RelayHttpsPort,
		&i.RelayGatewayPort,
		&i.RelayPortGeneration,
		&i.RelayStatus,
		&i.RelayErrorCode,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const startManagedHostRemoval = `-- name: StartManagedHostRemoval :one
UPDATE hosts SET status='draining', local_cleanup='pending', removal_generation=removal_generation+1,
 resource_version=resource_version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND resource_version=$3 AND connector_id=$4
  AND role='managed_host' AND status IN ('active','disabled','removal_failed','cleanup_unknown')
RETURNING id, enterprise_id, name, hostname, address, port, platform, bastion_scope_id, connector_id, environment, labels, labels_hash, labels_version, resource_version, connection_status, pinned_host_key, last_seen_at, status, deleted_at, created_at, updated_at, architecture, role, control_path, removal_generation, local_cleanup
`

type StartManagedHostRemovalParams struct {
	ID              uuid.UUID     `json:"id"`
	EnterpriseID    uuid.UUID     `json:"enterprise_id"`
	ResourceVersion int64         `json:"resource_version"`
	ConnectorID     uuid.NullUUID `json:"connector_id"`
}

func (q *Queries) StartManagedHostRemoval(ctx context.Context, arg StartManagedHostRemovalParams) (Host, error) {
	row := q.db.QueryRow(ctx, startManagedHostRemoval,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceVersion,
		arg.ConnectorID,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Hostname,
		&i.Address,
		&i.Port,
		&i.Platform,
		&i.BastionScopeID,
		&i.ConnectorID,
		&i.Environment,
		&i.Labels,
		&i.LabelsHash,
		&i.LabelsVersion,
		&i.ResourceVersion,
		&i.ConnectionStatus,
		&i.PinnedHostKey,
		&i.LastSeenAt,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Architecture,
		&i.Role,
		&i.ControlPath,
		&i.RemovalGeneration,
		&i.LocalCleanup,
	)
	return i, err
}

const supersedeHostRemovalCommands = `-- name: SupersedeHostRemovalCommands :execrows
UPDATE connector_commands SET status='failed',error_code='CONNECTOR_COMMAND_SUPERSEDED',completed_at=now(),updated_at=now()
WHERE enterprise_id=$1 AND operation_ref=$2 AND command_type='host_connector_removal'
  AND status IN ('delivery_unknown','result_unknown')
`

type SupersedeHostRemovalCommandsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OperationRef string    `json:"operation_ref"`
}

func (q *Queries) SupersedeHostRemovalCommands(ctx context.Context, arg SupersedeHostRemovalCommandsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeHostRemovalCommands, arg.EnterpriseID, arg.OperationRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeHostRemovalOperations = `-- name: SupersedeHostRemovalOperations :execrows
UPDATE host_removal_operations SET status='failed',error_code='HOST_REMOVAL_SUPERSEDED',completed_at=now(),
 lease_owner='',lease_expires_at=NULL,updated_at=now()
WHERE enterprise_id=$1 AND host_id=$2 AND status IN ('queued','running','awaiting_manual_execution','failed','cleanup_unknown')
`

type SupersedeHostRemovalOperationsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

func (q *Queries) SupersedeHostRemovalOperations(ctx context.Context, arg SupersedeHostRemovalOperationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeHostRemovalOperations, arg.EnterpriseID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const terminateRemoteAccessSessionsByHostRemoval = `-- name: TerminateRemoteAccessSessionsByHostRemoval :execrows
UPDATE remote_access_sessions SET status='terminating',session_fence=session_fence+1,
 termination_reason='host_removal',updated_at=now()
WHERE enterprise_id=$1 AND host_id=$2 AND status IN ('authorized','connecting','active')
`

type TerminateRemoteAccessSessionsByHostRemovalParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
}

func (q *Queries) TerminateRemoteAccessSessionsByHostRemoval(ctx context.Context, arg TerminateRemoteAccessSessionsByHostRemovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, terminateRemoteAccessSessionsByHostRemoval, arg.EnterpriseID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertHostManagedChangeJournal = `-- name: UpsertHostManagedChangeJournal :one
INSERT INTO host_managed_change_journals (id,enterprise_id,host_id,connector_id,change_type,before_state,applied_state,state_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (enterprise_id,host_id,change_type) WHERE status='active'
DO UPDATE SET connector_id=EXCLUDED.connector_id,before_state=EXCLUDED.before_state,applied_state=EXCLUDED.applied_state,
 state_hash=EXCLUDED.state_hash,updated_at=now() RETURNING id, enterprise_id, host_id, connector_id, change_type, before_state, applied_state, state_hash, status, restored_at, created_at, updated_at
`

type UpsertHostManagedChangeJournalParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	HostID       uuid.UUID `json:"host_id"`
	ConnectorID  uuid.UUID `json:"connector_id"`
	ChangeType   string    `json:"change_type"`
	BeforeState  []byte    `json:"before_state"`
	AppliedState []byte    `json:"applied_state"`
	StateHash    []byte    `json:"state_hash"`
}

func (q *Queries) UpsertHostManagedChangeJournal(ctx context.Context, arg UpsertHostManagedChangeJournalParams) (HostManagedChangeJournal, error) {
	row := q.db.QueryRow(ctx, upsertHostManagedChangeJournal,
		arg.ID,
		arg.EnterpriseID,
		arg.HostID,
		arg.ConnectorID,
		arg.ChangeType,
		arg.BeforeState,
		arg.AppliedState,
		arg.StateHash,
	)
	var i HostManagedChangeJournal
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.HostID,
		&i.ConnectorID,
		&i.ChangeType,
		&i.BeforeState,
		&i.AppliedState,
		&i.StateHash,
		&i.Status,
		&i.RestoredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHostRemovalStep = `-- name: UpsertHostRemovalStep :one
INSERT INTO host_removal_operation_steps (operation_id,enterprise_id,stage,status,attempt,postcondition,result_hash,error_code,started_at,completed_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $4='running' THEN now() ELSE NULL END,
 CASE WHEN $4 IN ('succeeded','failed','unknown') THEN now() ELSE NULL END)
ON CONFLICT (operation_id,stage) DO UPDATE SET status=EXCLUDED.status,attempt=EXCLUDED.attempt,
 postcondition=EXCLUDED.postcondition,result_hash=EXCLUDED.result_hash,error_code=EXCLUDED.error_code,
 started_at=COALESCE(host_removal_operation_steps.started_at,EXCLUDED.started_at),completed_at=EXCLUDED.completed_at,updated_at=now()
RETURNING operation_id, enterprise_id, stage, status, attempt, postcondition, result_hash, error_code, started_at, completed_at, updated_at
`

type UpsertHostRemovalStepParams struct {
	OperationID   uuid.UUID   `json:"operation_id"`
	EnterpriseID  uuid.UUID   `json:"enterprise_id"`
	Stage         string      `json:"stage"`
	Status        string      `json:"status"`
	Attempt       int32       `json:"attempt"`
	Postcondition []byte      `json:"postcondition"`
	ResultHash    []byte      `json:"result_hash"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) UpsertHostRemovalStep(ctx context.Context, arg UpsertHostRemovalStepParams) (HostRemovalOperationStep, error) {
	row := q.db.QueryRow(ctx, upsertHostRemovalStep,
		arg.OperationID,
		arg.EnterpriseID,
		arg.Stage,
		arg.Status,
		arg.Attempt,
		arg.Postcondition,
		arg.ResultHash,
		arg.ErrorCode,
	)
	var i HostRemovalOperationStep
	err := row.Scan(
		&i.OperationID,
		&i.EnterpriseID,
		&i.Stage,
		&i.Status,
		&i.Attempt,
		&i.Postcondition,
		&i.ResultHash,
		&i.ErrorCode,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
