// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.
package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                   uuid.UUID          `json:"id"`
	TokenHash            []byte             `json:"token_hash"`
	CsrfHash             []byte             `json:"csrf_hash"`
	Audience             string             `json:"audience"`
	UserID               uuid.UUID          `json:"user_id"`
	EnterpriseID         uuid.NullUUID      `json:"enterprise_id"`
	DepartmentID         uuid.NullUUID      `json:"department_id"`
	AuthorizationVersion pgtype.Int8        `json:"authorization_version"`
	Locale               string             `json:"locale"`
	IdleExpiresAt        pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt    pgtype.Timestamptz `json:"absolute_expires_at"`
	LastSeenAt           pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt            pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason         pgtype.Text        `json:"revoke_reason"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	AuthenticatedAt      pgtype.Timestamptz `json:"authenticated_at"`
	StepUpExpiresAt      pgtype.Timestamptz `json:"step_up_expires_at"`
	Amr                  []string           `json:"amr"`
}

type TelemetryCertificate struct {
	ID                     uuid.UUID          `json:"id"`
	CollectorID            uuid.UUID          `json:"collector_id"`
	SerialNumber           string             `json:"serial_number"`
	UriSan                 string             `json:"uri_san"`
	CsrHash                []byte             `json:"csr_hash"`
	CertificateHash        []byte             `json:"certificate_hash"`
	CertificateRequestName string             `json:"certificate_request_name"`
	IssuerGeneration       int32              `json:"issuer_generation"`
	NotBefore              pgtype.Timestamptz `json:"not_before"`
	NotAfter               pgtype.Timestamptz `json:"not_after"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	RevokeReason           pgtype.Text        `json:"revoke_reason"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	CertificateUsage       string             `json:"certificate_usage"`
}

type TelemetryCollectorOperation struct {
	ID              uuid.UUID          `json:"id"`
	EnterpriseID    uuid.UUID          `json:"enterprise_id"`
	CollectorID     uuid.UUID          `json:"collector_id"`
	PendingActionID uuid.UUID          `json:"pending_action_id"`
	Operation       string             `json:"operation"`
	ExecutorKind    string             `json:"executor_kind"`
	Status          string             `json:"status"`
	Plan            []byte             `json:"plan"`
	PlanHash        []byte             `json:"plan_hash"`
	LeaseOwner      pgtype.Text        `json:"lease_owner"`
	Fence           int64              `json:"fence"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	ResultHash      []byte             `json:"result_hash"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	Attempts        int32              `json:"attempts"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type TelemetryDlqRecord struct {
	ID           uuid.UUID          `json:"id"`
	Signal       string             `json:"signal"`
	Topic        string             `json:"topic"`
	Partition    int32              `json:"partition"`
	SourceOffset int64              `json:"source_offset"`
	DlqTopic     string             `json:"dlq_topic"`
	DlqPartition int32              `json:"dlq_partition"`
	DlqOffset    int64              `json:"dlq_offset"`
	RecordHash   []byte             `json:"record_hash"`
	ErrorCode    string             `json:"error_code"`
	Status       string             `json:"status"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	ReplayedAt   pgtype.Timestamptz `json:"replayed_at"`
}

type TelemetryEnrollmentToken struct {
	ID          uuid.UUID          `json:"id"`
	CollectorID uuid.UUID          `json:"collector_id"`
	TokenHash   []byte             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TelemetryRetentionPolicy struct {
	EnterpriseID   uuid.UUID          `json:"enterprise_id"`
	MetricsDays    int32              `json:"metrics_days"`
	LogsDays       int32              `json:"logs_days"`
	TracesDays     int32              `json:"traces_days"`
	MaxRows        int32              `json:"max_rows"`
	MaxScanBytes   int64              `json:"max_scan_bytes"`
	MaxExecutionMs int32              `json:"max_execution_ms"`
	Version        int64              `json:"version"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TelemetryRoute struct {
	ID                 uuid.UUID          `json:"id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	CollectorID        uuid.UUID          `json:"collector_id"`
	Kind               string             `json:"kind"`
	GatewayCollectorID uuid.NullUUID      `json:"gateway_collector_id"`
	Status             string             `json:"status"`
	Version            int64              `json:"version"`
	LastTestedAt       pgtype.Timestamptz `json:"last_tested_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Transport          string             `json:"transport"`
	LoopbackPort       pgtype.Int4        `json:"loopback_port"`
}

type TelemetryRouteTest struct {
	ID           uuid.UUID          `json:"id"`
	EnterpriseID uuid.UUID          `json:"enterprise_id"`
	RouteID      uuid.UUID          `json:"route_id"`
	Status       string             `json:"status"`
	ResultCode   pgtype.Text        `json:"result_code"`
	ResultHash   []byte             `json:"result_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type TelemetryTunnel struct {
	ID                   uuid.UUID          `json:"id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	HostID               uuid.UUID          `json:"host_id"`
	CollectorID          uuid.UUID          `json:"collector_id"`
	ConnectorID          uuid.NullUUID      `json:"connector_id"`
	CredentialID         uuid.UUID          `json:"credential_id"`
	CredentialVersion    int64              `json:"credential_version"`
	TargetAddress        string             `json:"target_address"`
	TargetPort           int32              `json:"target_port"`
	TargetUsername       string             `json:"target_username"`
	PinnedHostKey        string             `json:"pinned_host_key"`
	Initiator            string             `json:"initiator"`
	Transport            string             `json:"transport"`
	LoopbackPort         int32              `json:"loopback_port"`
	ForwardTarget        string             `json:"forward_target"`
	Status               string             `json:"status"`
	Epoch                int64              `json:"epoch"`
	LeaseOwner           string             `json:"lease_owner"`
	OwnerConnectionEpoch int64              `json:"owner_connection_epoch"`
	Fence                int64              `json:"fence"`
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
	LastClaimAt          pgtype.Timestamptz `json:"last_claim_at"`
	LastEstablishedAt    pgtype.Timestamptz `json:"last_established_at"`
	LastHeartbeatAt      pgtype.Timestamptz `json:"last_heartbeat_at"`
	LastDropReason       string             `json:"last_drop_reason"`
	ReconnectAttempt     int32              `json:"reconnect_attempt"`
	NextClaimAt          pgtype.Timestamptz `json:"next_claim_at"`
	BytesRelayed         int64              `json:"bytes_relayed"`
	ThrottledEvents      int64              `json:"throttled_events"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TelemetryUsageDaily struct {
	EnterpriseID          uuid.UUID          `json:"enterprise_id"`
	UsageDate             pgtype.Date        `json:"usage_date"`
	IngestedBytes         int64              `json:"ingested_bytes"`
	MetricPoints          int64              `json:"metric_points"`
	LogRecords            int64              `json:"log_records"`
	Spans                 int64              `json:"spans"`
	EstimatedStorageBytes int64              `json:"estimated_storage_bytes"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type TemplateAsset struct {
	Hash      string             `json:"hash"`
	Source    string             `json:"source"`
	Runtime   string             `json:"runtime"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TemporaryCredential struct {
	ID            uuid.UUID          `json:"id"`
	Audience      string             `json:"audience"`
	UserID        uuid.UUID          `json:"user_id"`
	ChallengeHash []byte             `json:"challenge_hash"`
	Status        string             `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ToolCall struct {
	ID                 uuid.UUID          `json:"id"`
	CallID             string             `json:"call_id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	RunID              uuid.UUID          `json:"run_id"`
	StepID             uuid.UUID          `json:"step_id"`
	ToolID             string             `json:"tool_id"`
	Source             string             `json:"source"`
	AuthorizationScope string             `json:"authorization_scope"`
	ModelCallID        uuid.NullUUID      `json:"model_call_id"`
	CallSequence       int32              `json:"call_sequence"`
	ConnectionID       uuid.NullUUID      `json:"connection_id"`
	SchemaHash         string             `json:"schema_hash"`
	DispatchedAt       pgtype.Timestamptz `json:"dispatched_at"`
	Input              []byte             `json:"input"`
	InputHash          []byte             `json:"input_hash"`
	Status             string             `json:"status"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ToolPresentation struct {
	ID                 uuid.UUID          `json:"id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	ConversationID     uuid.UUID          `json:"conversation_id"`
	ToolCallID         uuid.UUID          `json:"tool_call_id"`
	ToolVersion        string             `json:"tool_version"`
	AuthorizationScope string             `json:"authorization_scope"`
	TemplateHash       string             `json:"template_hash"`
	DetailData         []byte             `json:"detail_data"`
	ResourceRefs       []byte             `json:"resource_refs"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ToolResult struct {
	ID              uuid.UUID          `json:"id"`
	ToolCallID      uuid.UUID          `json:"tool_call_id"`
	EnterpriseID    uuid.UUID          `json:"enterprise_id"`
	ArtifactID      uuid.UUID          `json:"artifact_id"`
	Projection      []byte             `json:"projection"`
	ProjectionHash  []byte             `json:"projection_hash"`
	ProjectionBytes int32              `json:"projection_bytes"`
	Partial         bool               `json:"partial"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UserConfirmation struct {
	ID                   uuid.UUID          `json:"id"`
	PendingActionID      uuid.UUID          `json:"pending_action_id"`
	EnterpriseID         uuid.UUID          `json:"enterprise_id"`
	ActorUserID          uuid.UUID          `json:"actor_user_id"`
	AuthorizationVersion int64              `json:"authorization_version"`
	ConfirmedAt          pgtype.Timestamptz `json:"confirmed_at"`
}

type Workspace struct {
	ID                 uuid.UUID          `json:"id"`
	RuntimeUid         int32              `json:"runtime_uid"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	ConversationID     uuid.UUID          `json:"conversation_id"`
	Status             string             `json:"status"`
	PvcName            string             `json:"pvc_name"`
	Namespace          string             `json:"namespace"`
	CapacityBytes      int64              `json:"capacity_bytes"`
	EnvironmentVersion string             `json:"environment_version"`
	SourceResultRefs   []string           `json:"source_result_refs"`
	ActivePodName      pgtype.Text        `json:"active_pod_name"`
	ActiveSandboxID    pgtype.Text        `json:"active_sandbox_id"`
	LeaseOwner         pgtype.Text        `json:"lease_owner"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	FenceToken         int64              `json:"fence_token"`
	Version            int64              `json:"version"`
	LastUsedAt         pgtype.Timestamptz `json:"last_used_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceFile struct {
	ID               uuid.UUID          `json:"id"`
	EnterpriseID     uuid.UUID          `json:"enterprise_id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	ConversationID   uuid.UUID          `json:"conversation_id"`
	Name             string             `json:"name"`
	Path             string             `json:"path"`
	ByteSize         int64              `json:"byte_size"`
	ContentHash      string             `json:"content_hash"`
	MediaType        string             `json:"media_type"`
	SourceResultRefs []string           `json:"source_result_refs"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceQuota struct {
	EnterpriseID  uuid.UUID          `json:"enterprise_id"`
	LimitBytes    int64              `json:"limit_bytes"`
	ReservedBytes int64              `json:"reserved_bytes"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceUpload struct {
	ID            uuid.UUID          `json:"id"`
	EnterpriseID  uuid.UUID          `json:"enterprise_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	Name          string             `json:"name"`
	Path          string             `json:"path"`
	ExpectedBytes int64              `json:"expected_bytes"`
	Status        string             `json:"status"`
	RequestID     string             `json:"request_id"`
	FileID        uuid.NullUUID      `json:"file_id"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
