// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

func (q *Queries) MarkToolDispatched(ctx context.Context, arg MarkToolDispatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markToolDispatched, arg.ID, arg.EnterpriseID, arg.ExpectedRunVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reconcileInterruptedModelCalls = `-- name: ReconcileInterruptedModelCalls :exec
WITH interrupted AS (
 UPDATE model_calls SET status='failed',stop_reason='worker_interrupted',error_code='MODEL_RESPONSE_INTERRUPTED',completed_at=now()
 WHERE model_calls.run_id=$1 AND model_calls.enterprise_id=$2 AND model_calls.call_kind=$3 AND model_calls.status IN ('reserved','running') RETURNING model_calls.step_id
)
UPDATE run_steps SET status='failed',updated_at=now()
WHERE run_steps.id IN (SELECT step_id FROM interrupted)
OR (run_steps.status='running' AND run_steps.run_id=$1 AND run_steps.enterprise_id=$2
 AND EXISTS(SELECT 1 FROM model_calls c WHERE c.step_id=run_steps.id AND c.call_kind=$3))
`

type ReconcileInterruptedModelCallsParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	CallKind     string    `json:"call_kind"`
}

func (q *Queries) ReconcileInterruptedModelCalls(ctx context.Context, arg ReconcileInterruptedModelCallsParams) error {
	_, err := q.db.Exec(ctx, reconcileInterruptedModelCalls, arg.RunID, arg.EnterpriseID, arg.CallKind)
	return err
}

const releaseWorkspaceCapacity = `-- name: ReleaseWorkspaceCapacity :exec
UPDATE workspace_quotas SET reserved_bytes=GREATEST(0,reserved_bytes-$2),updated_at=now() WHERE enterprise_id=$1
`

type ReleaseWorkspaceCapacityParams struct {
	EnterpriseID  uuid.UUID `json:"enterprise_id"`
	ReservedBytes int64     `json:"reserved_bytes"`
}

func (q *Queries) ReleaseWorkspaceCapacity(ctx context.Context, arg ReleaseWorkspaceCapacityParams) error {
	_, err := q.db.Exec(ctx, releaseWorkspaceCapacity, arg.EnterpriseID, arg.ReservedBytes)
	return err
}

const releaseWorkspaceLease = `-- name: ReleaseWorkspaceLease :execrows
UPDATE workspaces SET lease_owner=NULL,lease_until=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND lease_owner=$3 AND fence_token=$4
`

type ReleaseWorkspaceLeaseParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	FenceToken   int64       `json:"fence_token"`
}

func (q *Queries) ReleaseWorkspaceLease(ctx context.Context, arg ReleaseWorkspaceLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWorkspaceLease,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.FenceToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewWorkspaceLease = `-- name: RenewWorkspaceLease :execrows
UPDATE workspaces SET lease_until=now()+$5::interval,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND lease_owner=$3 AND fence_token=$4 AND lease_until>now()
`

type RenewWorkspaceLeaseParams struct {
	ID           uuid.UUID       `json:"id"`
	EnterpriseID uuid.UUID       `json:"enterprise_id"`
	LeaseOwner   pgtype.Text     `json:"lease_owner"`
	FenceToken   int64           `json:"fence_token"`
	Column5      pgtype.Interval `json:"column_5"`
}

func (q *Queries) RenewWorkspaceLease(ctx context.Context, arg RenewWorkspaceLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewWorkspaceLease,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveWorkspaceCapacity = `-- name: ReserveWorkspaceCapacity :one
UPDATE workspace_quotas SET reserved_bytes=reserved_bytes+$2, updated_at=now()
WHERE enterprise_id=$1 AND reserved_bytes+$2<=limit_bytes RETURNING enterprise_id, limit_bytes, reserved_bytes, updated_at
`

type ReserveWorkspaceCapacityParams struct {
	EnterpriseID  uuid.UUID `json:"enterprise_id"`
	ReservedBytes int64     `json:"reserved_bytes"`
}

func (q *Queries) ReserveWorkspaceCapacity(ctx context.Context, arg ReserveWorkspaceCapacityParams) (WorkspaceQuota, error) {
	row := q.db.QueryRow(ctx, reserveWorkspaceCapacity, arg.EnterpriseID, arg.ReservedBytes)
	var i WorkspaceQuota
	err := row.Scan(
		&i.EnterpriseID,
		&i.LimitBytes,
		&i.ReservedBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const selectConversationMCPConnection = `-- name: SelectConversationMCPConnection :exec
INSERT INTO conversation_mcp_connections (conversation_id,enterprise_id,connection_id)
VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type SelectConversationMCPConnectionParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConnectionID   uuid.UUID `json:"connection_id"`
}

func (q *Queries) SelectConversationMCPConnection(ctx context.Context, arg SelectConversationMCPConnectionParams) error {
	_, err := q.db.Exec(ctx, selectConversationMCPConnection, arg.ConversationID, arg.EnterpriseID, arg.ConnectionID)
	return err
}

const setRunToolSnapshot = `-- name: SetRunToolSnapshot :one
UPDATE runs SET tool_snapshot=$3, tool_snapshot_hash=$4, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND tool_snapshot_hash='' RETURNING id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, verification_only, tool_snapshot, tool_snapshot_hash, stop_reason, error_code, version, created_at, updated_at
`

type SetRunToolSnapshotParams struct {
	ID               uuid.UUID `json:"id"`
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	ToolSnapshot     []byte    `json:"tool_snapshot"`
	ToolSnapshotHash string    `json:"tool_snapshot_hash"`
}

func (q *Queries) SetRunToolSnapshot(ctx context.Context, arg SetRunToolSnapshotParams) (Run, error) {
	row := q.db.QueryRow(ctx, setRunToolSnapshot,
		arg.ID,
		arg.EnterpriseID,
		arg.ToolSnapshot,
		arg.ToolSnapshotHash,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.VerificationOnly,
		&i.ToolSnapshot,
		&i.ToolSnapshotHash,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWorkspaceAttachment = `-- name: SetWorkspaceAttachment :execrows
UPDATE workspaces SET active_pod_name=$5,active_sandbox_id=$6,last_used_at=now(),updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND lease_owner=$3 AND fence_token=$4 AND lease_until>now()
`

type SetWorkspaceAttachmentParams struct {
	ID              uuid.UUID   `json:"id"`
	EnterpriseID    uuid.UUID   `json:"enterprise_id"`
	LeaseOwner      pgtype.Text `json:"lease_owner"`
	FenceToken      int64       `json:"fence_token"`
	ActivePodName   pgtype.Text `json:"active_pod_name"`
	ActiveSandboxID pgtype.Text `json:"active_sandbox_id"`
}

func (q *Queries) SetWorkspaceAttachment(ctx context.Context, arg SetWorkspaceAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkspaceAttachment,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.ActivePodName,
		arg.ActiveSandboxID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkspaceStatus = `-- name: SetWorkspaceStatus :one
UPDATE workspaces SET status=$3,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$4 RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type SetWorkspaceStatusParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Status       string    `json:"status"`
	Version      int64     `json:"version"`
}

func (q *Queries) SetWorkspaceStatus(ctx context.Context, arg SetWorkspaceStatusParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceStatus,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.Version,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnection = `-- name: UpdateMCPConnection :one
UPDATE mcp_connections SET name=$3, status=$4, current_revision=$5,
    current_tool_snapshot_id=$6, health_status=$7, last_error_code=$8,
    authorization_epoch=authorization_epoch+1, version=version+1, updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$9 RETURNING id, enterprise_id, name, status, health_status, current_revision, current_tool_snapshot_id, authorization_epoch, version, last_error_code, created_by, created_at, updated_at
`

type UpdateMCPConnectionParams struct {
	ID                    uuid.UUID     `json:"id"`
	EnterpriseID          uuid.UUID     `json:"enterprise_id"`
	Name                  string        `json:"name"`
	Status                string        `json:"status"`
	CurrentRevision       int32         `json:"current_revision"`
	CurrentToolSnapshotID uuid.NullUUID `json:"current_tool_snapshot_id"`
	HealthStatus          string        `json:"health_status"`
	LastErrorCode         pgtype.Text   `json:"last_error_code"`
	Version               int64         `json:"version"`
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRow(ctx, updateMCPConnection,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.Status,
		arg.CurrentRevision,
		arg.CurrentToolSnapshotID,
		arg.HealthStatus,
		arg.LastErrorCode,
		arg.Version,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Status,
		&i.HealthStatus,
		&i.CurrentRevision,
		&i.CurrentToolSnapshotID,
		&i.AuthorizationEpoch,
		&i.Version,
		&i.LastErrorCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
