// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpMCPAuthorization = `-- name: BumpMCPAuthorization :one
UPDATE mcp_connections SET authorization_epoch=authorization_epoch+1,version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND version=$3 RETURNING id, enterprise_id, name, status, health_status, current_revision, current_tool_snapshot_id, authorization_epoch, version, last_error_code, created_by, created_at, updated_at
`

type BumpMCPAuthorizationParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Version      int64     `json:"version"`
}

func (q *Queries) BumpMCPAuthorization(ctx context.Context, arg BumpMCPAuthorizationParams) (McpConnection, error) {
	row := q.db.QueryRow(ctx, bumpMCPAuthorization, arg.ID, arg.EnterpriseID, arg.Version)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Status,
		&i.HealthStatus,
		&i.CurrentRevision,
		&i.CurrentToolSnapshotID,
		&i.AuthorizationEpoch,
		&i.Version,
		&i.LastErrorCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimContextRevision = `-- name: ClaimContextRevision :one
UPDATE conversations SET context_revision=context_revision+1
WHERE id=$1 AND enterprise_id=$2 AND context_revision=$3 RETURNING context_revision
`

type ClaimContextRevisionParams struct {
	ID              uuid.UUID `json:"id"`
	EnterpriseID    uuid.UUID `json:"enterprise_id"`
	ContextRevision int64     `json:"context_revision"`
}

func (q *Queries) ClaimContextRevision(ctx context.Context, arg ClaimContextRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, claimContextRevision, arg.ID, arg.EnterpriseID, arg.ContextRevision)
	var context_revision int64
	err := row.Scan(&context_revision)
	return context_revision, err
}

const claimWorkspaceLease = `-- name: ClaimWorkspaceLease :one
UPDATE workspaces SET lease_owner=$3,lease_until=now()+$4::interval,fence_token=fence_token+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='ready'
AND fence_token=$5
AND (lease_until IS NULL OR lease_until<now()) RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type ClaimWorkspaceLeaseParams struct {
	ID            uuid.UUID       `json:"id"`
	EnterpriseID  uuid.UUID       `json:"enterprise_id"`
	LeaseOwner    pgtype.Text     `json:"lease_owner"`
	Column4       pgtype.Interval `json:"column_4"`
	ExpectedFence int64           `json:"expected_fence"`
}

func (q *Queries) ClaimWorkspaceLease(ctx context.Context, arg ClaimWorkspaceLeaseParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, claimWorkspaceLease,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.Column4,
		arg.ExpectedFence,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimWorkspaceUpload = `-- name: ClaimWorkspaceUpload :one
UPDATE workspace_uploads SET status='uploading',updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND owner_user_id=$3 AND status='pending' AND expires_at>now() RETURNING id, enterprise_id, workspace_id, owner_user_id, name, path, expected_bytes, status, request_id, file_id, error_code, expires_at, created_at, updated_at
`

type ClaimWorkspaceUploadParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) ClaimWorkspaceUpload(ctx context.Context, arg ClaimWorkspaceUploadParams) (WorkspaceUpload, error) {
	row := q.db.QueryRow(ctx, claimWorkspaceUpload, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i WorkspaceUpload
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Name,
		&i.Path,
		&i.ExpectedBytes,
		&i.Status,
		&i.RequestID,
		&i.FileID,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearConversationMCPConnections = `-- name: ClearConversationMCPConnections :exec
DELETE FROM conversation_mcp_connections WHERE conversation_id=$1 AND enterprise_id=$2
`

type ClearConversationMCPConnectionsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ClearConversationMCPConnections(ctx context.Context, arg ClearConversationMCPConnectionsParams) error {
	_, err := q.db.Exec(ctx, clearConversationMCPConnections, arg.ConversationID, arg.EnterpriseID)
	return err
}

const countRunInferenceCalls = `-- name: CountRunInferenceCalls :one
SELECT count(*) FROM model_calls WHERE run_id=$1 AND enterprise_id=$2 AND call_kind='inference'
`

type CountRunInferenceCallsParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CountRunInferenceCalls(ctx context.Context, arg CountRunInferenceCallsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunInferenceCalls, arg.RunID, arg.EnterpriseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFileDelivery = `-- name: CreateFileDelivery :one
INSERT INTO file_deliveries (id,enterprise_id,conversation_id,workspace_id,run_id,name,media_type,byte_size,content_hash,object_key,source_result_refs)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, enterprise_id, conversation_id, workspace_id, run_id, name, media_type, byte_size, content_hash, object_key, source_result_refs, created_at, deleted_at
`

type CreateFileDeliveryParams struct {
	ID               uuid.UUID     `json:"id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	ConversationID   uuid.UUID     `json:"conversation_id"`
	WorkspaceID      uuid.UUID     `json:"workspace_id"`
	RunID            uuid.NullUUID `json:"run_id"`
	Name             string        `json:"name"`
	MediaType        string        `json:"media_type"`
	ByteSize         int64         `json:"byte_size"`
	ContentHash      string        `json:"content_hash"`
	ObjectKey        string        `json:"object_key"`
	SourceResultRefs []string      `json:"source_result_refs"`
}

func (q *Queries) CreateFileDelivery(ctx context.Context, arg CreateFileDeliveryParams) (FileDelivery, error) {
	row := q.db.QueryRow(ctx, createFileDelivery,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.RunID,
		arg.Name,
		arg.MediaType,
		arg.ByteSize,
		arg.ContentHash,
		arg.ObjectKey,
		arg.SourceResultRefs,
	)
	var i FileDelivery
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.WorkspaceID,
		&i.RunID,
		&i.Name,
		&i.MediaType,
		&i.ByteSize,
		&i.ContentHash,
		&i.ObjectKey,
		&i.SourceResultRefs,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMCPConnection = `-- name: CreateMCPConnection :one
INSERT INTO mcp_connections (id, enterprise_id, name, created_by)
VALUES ($1,$2,$3,$4) RETURNING id, enterprise_id, name, status, health_status, current_revision, current_tool_snapshot_id, authorization_epoch, version, last_error_code, created_by, created_at, updated_at
`

type CreateMCPConnectionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Name         string    `json:"name"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateMCPConnection(ctx context.Context, arg CreateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRow(ctx, createMCPConnection,
		arg.ID,
		arg.EnterpriseID,
		arg.Name,
		arg.CreatedBy,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Status,
		&i.HealthStatus,
		&i.CurrentRevision,
		&i.CurrentToolSnapshotID,
		&i.AuthorizationEpoch,
		&i.Version,
		&i.LastErrorCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMCPConnectionRevision = `-- name: CreateMCPConnectionRevision :one
INSERT INTO mcp_connection_revisions (connection_id,enterprise_id,revision,endpoint,auth_type,credential_id,credential_version)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING connection_id, enterprise_id, revision, endpoint, auth_type, credential_id, credential_version, created_at
`

type CreateMCPConnectionRevisionParams struct {
	ConnectionID      uuid.UUID     `json:"connection_id"`
	EnterpriseID      uuid.UUID     `json:"enterprise_id"`
	Revision          int32         `json:"revision"`
	Endpoint          string        `json:"endpoint"`
	AuthType          string        `json:"auth_type"`
	CredentialID      uuid.NullUUID `json:"credential_id"`
	CredentialVersion pgtype.Int8   `json:"credential_version"`
}

func (q *Queries) CreateMCPConnectionRevision(ctx context.Context, arg CreateMCPConnectionRevisionParams) (McpConnectionRevision, error) {
	row := q.db.QueryRow(ctx, createMCPConnectionRevision,
		arg.ConnectionID,
		arg.EnterpriseID,
		arg.Revision,
		arg.Endpoint,
		arg.AuthType,
		arg.CredentialID,
		arg.CredentialVersion,
	)
	var i McpConnectionRevision
	err := row.Scan(
		&i.ConnectionID,
		&i.EnterpriseID,
		&i.Revision,
		&i.Endpoint,
		&i.AuthType,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createMCPToolSnapshot = `-- name: CreateMCPToolSnapshot :one
INSERT INTO mcp_tool_snapshots (id,connection_id,enterprise_id,connection_revision,schema_hash,tools)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (connection_id,connection_revision,schema_hash) DO UPDATE SET schema_hash=EXCLUDED.schema_hash
RETURNING id, connection_id, enterprise_id, connection_revision, schema_hash, tools, created_at
`

type CreateMCPToolSnapshotParams struct {
	ID                 uuid.UUID `json:"id"`
	ConnectionID       uuid.UUID `json:"connection_id"`
	EnterpriseID       uuid.UUID `json:"enterprise_id"`
	ConnectionRevision int32     `json:"connection_revision"`
	SchemaHash         string    `json:"schema_hash"`
	Tools              []byte    `json:"tools"`
}

func (q *Queries) CreateMCPToolSnapshot(ctx context.Context, arg CreateMCPToolSnapshotParams) (McpToolSnapshot, error) {
	row := q.db.QueryRow(ctx, createMCPToolSnapshot,
		arg.ID,
		arg.ConnectionID,
		arg.EnterpriseID,
		arg.ConnectionRevision,
		arg.SchemaHash,
		arg.Tools,
	)
	var i McpToolSnapshot
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.EnterpriseID,
		&i.ConnectionRevision,
		&i.SchemaHash,
		&i.Tools,
		&i.CreatedAt,
	)
	return i, err
}

const createModelToolCall = `-- name: CreateModelToolCall :one
INSERT INTO tool_calls (id,call_id,enterprise_id,run_id,step_id,tool_id,input,input_hash,status,source,model_call_id,call_sequence,connection_id,schema_hash,authorization_scope)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'prepared',$9,$10,$11,$12,$13,$14) RETURNING id, call_id, enterprise_id, run_id, step_id, tool_id, source, authorization_scope, model_call_id, call_sequence, connection_id, schema_hash, dispatched_at, input, input_hash, status, error_code, created_at, updated_at
`

type CreateModelToolCallParams struct {
	ID                 uuid.UUID     `json:"id"`
	CallID             string        `json:"call_id"`
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	RunID              uuid.UUID     `json:"run_id"`
	StepID             uuid.UUID     `json:"step_id"`
	ToolID             string        `json:"tool_id"`
	Input              []byte        `json:"input"`
	InputHash          []byte        `json:"input_hash"`
	Source             string        `json:"source"`
	ModelCallID        uuid.NullUUID `json:"model_call_id"`
	CallSequence       int32         `json:"call_sequence"`
	ConnectionID       uuid.NullUUID `json:"connection_id"`
	SchemaHash         string        `json:"schema_hash"`
	AuthorizationScope string        `json:"authorization_scope"`
}

func (q *Queries) CreateModelToolCall(ctx context.Context, arg CreateModelToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, createModelToolCall,
		arg.ID,
		arg.CallID,
		arg.EnterpriseID,
		arg.RunID,
		arg.StepID,
		arg.ToolID,
		arg.Input,
		arg.InputHash,
		arg.Source,
		arg.ModelCallID,
		arg.CallSequence,
		arg.ConnectionID,
		arg.SchemaHash,
		arg.AuthorizationScope,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.EnterpriseID,
		&i.RunID,
		&i.StepID,
		&i.ToolID,
		&i.Source,
		&i.AuthorizationScope,
		&i.ModelCallID,
		&i.CallSequence,
		&i.ConnectionID,
		&i.SchemaHash,
		&i.DispatchedAt,
		&i.Input,
		&i.InputHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateAsset = `-- name: CreateTemplateAsset :exec
INSERT INTO template_assets (hash,source,runtime) VALUES($1,$2,'argus-template/v1') ON CONFLICT DO NOTHING
`

type CreateTemplateAssetParams struct {
	Hash   string `json:"hash"`
	Source string `json:"source"`
}

func (q *Queries) CreateTemplateAsset(ctx context.Context, arg CreateTemplateAssetParams) error {
	_, err := q.db.Exec(ctx, createTemplateAsset, arg.Hash, arg.Source)
	return err
}

const createToolPresentation = `-- name: CreateToolPresentation :one
INSERT INTO tool_presentations (id,enterprise_id,conversation_id,tool_call_id,tool_version,authorization_scope,template_hash,detail_data,resource_refs,status)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, enterprise_id, conversation_id, tool_call_id, tool_version, authorization_scope, template_hash, detail_data, resource_refs, status, created_at
`

type CreateToolPresentationParams struct {
	ID                 uuid.UUID `json:"id"`
	EnterpriseID       uuid.UUID `json:"enterprise_id"`
	ConversationID     uuid.UUID `json:"conversation_id"`
	ToolCallID         uuid.UUID `json:"tool_call_id"`
	ToolVersion        string    `json:"tool_version"`
	AuthorizationScope string    `json:"authorization_scope"`
	TemplateHash       string    `json:"template_hash"`
	DetailData         []byte    `json:"detail_data"`
	ResourceRefs       []byte    `json:"resource_refs"`
	Status             string    `json:"status"`
}

func (q *Queries) CreateToolPresentation(ctx context.Context, arg CreateToolPresentationParams) (ToolPresentation, error) {
	row := q.db.QueryRow(ctx, createToolPresentation,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.ToolCallID,
		arg.ToolVersion,
		arg.AuthorizationScope,
		arg.TemplateHash,
		arg.DetailData,
		arg.ResourceRefs,
		arg.Status,
	)
	var i ToolPresentation
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ToolVersion,
		&i.AuthorizationScope,
		&i.TemplateHash,
		&i.DetailData,
		&i.ResourceRefs,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id,enterprise_id,conversation_id,pvc_name,namespace,capacity_bytes,environment_version)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID                 uuid.UUID `json:"id"`
	EnterpriseID       uuid.UUID `json:"enterprise_id"`
	ConversationID     uuid.UUID `json:"conversation_id"`
	PvcName            string    `json:"pvc_name"`
	Namespace          string    `json:"namespace"`
	CapacityBytes      int64     `json:"capacity_bytes"`
	EnvironmentVersion string    `json:"environment_version"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.EnterpriseID,
		arg.ConversationID,
		arg.PvcName,
		arg.Namespace,
		arg.CapacityBytes,
		arg.EnvironmentVersion,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceFile = `-- name: CreateWorkspaceFile :one
INSERT INTO workspace_files (id,enterprise_id,workspace_id,conversation_id,name,path,byte_size,content_hash,media_type,source_result_refs)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, enterprise_id, workspace_id, conversation_id, name, path, byte_size, content_hash, media_type, source_result_refs, created_at, deleted_at
`

type CreateWorkspaceFileParams struct {
	ID               uuid.UUID `json:"id"`
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	WorkspaceID      uuid.UUID `json:"workspace_id"`
	ConversationID   uuid.UUID `json:"conversation_id"`
	Name             string    `json:"name"`
	Path             string    `json:"path"`
	ByteSize         int64     `json:"byte_size"`
	ContentHash      string    `json:"content_hash"`
	MediaType        string    `json:"media_type"`
	SourceResultRefs []string  `json:"source_result_refs"`
}

func (q *Queries) CreateWorkspaceFile(ctx context.Context, arg CreateWorkspaceFileParams) (WorkspaceFile, error) {
	row := q.db.QueryRow(ctx, createWorkspaceFile,
		arg.ID,
		arg.EnterpriseID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Name,
		arg.Path,
		arg.ByteSize,
		arg.ContentHash,
		arg.MediaType,
		arg.SourceResultRefs,
	)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Name,
		&i.Path,
		&i.ByteSize,
		&i.ContentHash,
		&i.MediaType,
		&i.SourceResultRefs,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkspaceUpload = `-- name: CreateWorkspaceUpload :one
INSERT INTO workspace_uploads (id,enterprise_id,workspace_id,owner_user_id,name,path,expected_bytes,request_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, enterprise_id, workspace_id, owner_user_id, name, path, expected_bytes, status, request_id, file_id, error_code, expires_at, created_at, updated_at
`

type CreateWorkspaceUploadParams struct {
	ID            uuid.UUID `json:"id"`
	EnterpriseID  uuid.UUID `json:"enterprise_id"`
	WorkspaceID   uuid.UUID `json:"workspace_id"`
	OwnerUserID   uuid.UUID `json:"owner_user_id"`
	Name          string    `json:"name"`
	Path          string    `json:"path"`
	ExpectedBytes int64     `json:"expected_bytes"`
	RequestID     string    `json:"request_id"`
}

func (q *Queries) CreateWorkspaceUpload(ctx context.Context, arg CreateWorkspaceUploadParams) (WorkspaceUpload, error) {
	row := q.db.QueryRow(ctx, createWorkspaceUpload,
		arg.ID,
		arg.EnterpriseID,
		arg.WorkspaceID,
		arg.OwnerUserID,
		arg.Name,
		arg.Path,
		arg.ExpectedBytes,
		arg.RequestID,
	)
	var i WorkspaceUpload
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Name,
		&i.Path,
		&i.ExpectedBytes,
		&i.Status,
		&i.RequestID,
		&i.FileID,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPConnectionGrants = `-- name: DeleteMCPConnectionGrants :exec
DELETE FROM mcp_connection_grants WHERE connection_id=$1 AND enterprise_id=$2
`

type DeleteMCPConnectionGrantsParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteMCPConnectionGrants(ctx context.Context, arg DeleteMCPConnectionGrantsParams) error {
	_, err := q.db.Exec(ctx, deleteMCPConnectionGrants, arg.ConnectionID, arg.EnterpriseID)
	return err
}

const deleteWorkspaceDeliveryRecords = `-- name: DeleteWorkspaceDeliveryRecords :exec
UPDATE file_deliveries SET deleted_at=now() WHERE workspace_id=$1 AND enterprise_id=$2 AND deleted_at IS NULL
`

type DeleteWorkspaceDeliveryRecordsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteWorkspaceDeliveryRecords(ctx context.Context, arg DeleteWorkspaceDeliveryRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceDeliveryRecords, arg.WorkspaceID, arg.EnterpriseID)
	return err
}

const deleteWorkspaceFileRecords = `-- name: DeleteWorkspaceFileRecords :exec
UPDATE workspace_files SET deleted_at=now() WHERE workspace_id=$1 AND enterprise_id=$2 AND deleted_at IS NULL
`

type DeleteWorkspaceFileRecordsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) DeleteWorkspaceFileRecords(ctx context.Context, arg DeleteWorkspaceFileRecordsParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceFileRecords, arg.WorkspaceID, arg.EnterpriseID)
	return err
}

const ensureWorkspaceQuota = `-- name: EnsureWorkspaceQuota :exec
INSERT INTO workspace_quotas (enterprise_id,limit_bytes) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type EnsureWorkspaceQuotaParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	LimitBytes   int64     `json:"limit_bytes"`
}

func (q *Queries) EnsureWorkspaceQuota(ctx context.Context, arg EnsureWorkspaceQuotaParams) error {
	_, err := q.db.Exec(ctx, ensureWorkspaceQuota, arg.EnterpriseID, arg.LimitBytes)
	return err
}

const finishWorkspaceUpload = `-- name: FinishWorkspaceUpload :execrows
UPDATE workspace_uploads SET status=$3,file_id=$4,error_code=$5,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='uploading'
`

type FinishWorkspaceUploadParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	Status       string        `json:"status"`
	FileID       uuid.NullUUID `json:"file_id"`
	ErrorCode    pgtype.Text   `json:"error_code"`
}

func (q *Queries) FinishWorkspaceUpload(ctx context.Context, arg FinishWorkspaceUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishWorkspaceUpload,
		arg.ID,
		arg.EnterpriseID,
		arg.Status,
		arg.FileID,
		arg.ErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveConversationSnapshot = `-- name: GetActiveConversationSnapshot :one
SELECT id, enterprise_id, conversation_id, run_id, revision, source_from_sequence, source_through_sequence, first_kept_sequence, typed_checkpoint, narrative_summary, compaction_model_id, compaction_model_revision, prompt_version, estimated_tokens_before, actual_tokens_after, source_hash, snapshot_hash, status, error_code, created_at FROM context_snapshots WHERE conversation_id=$1 AND enterprise_id=$2 AND status='active'
`

type GetActiveConversationSnapshotParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetActiveConversationSnapshot(ctx context.Context, arg GetActiveConversationSnapshotParams) (ContextSnapshot, error) {
	row := q.db.QueryRow(ctx, getActiveConversationSnapshot, arg.ConversationID, arg.EnterpriseID)
	var i ContextSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.RunID,
		&i.Revision,
		&i.SourceFromSequence,
		&i.SourceThroughSequence,
		&i.FirstKeptSequence,
		&i.TypedCheckpoint,
		&i.NarrativeSummary,
		&i.CompactionModelID,
		&i.CompactionModelRevision,
		&i.PromptVersion,
		&i.EstimatedTokensBefore,
		&i.ActualTokensAfter,
		&i.SourceHash,
		&i.SnapshotHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationMCPConnections = `-- name: GetConversationMCPConnections :many
SELECT connection_id FROM conversation_mcp_connections WHERE conversation_id=$1 AND enterprise_id=$2 ORDER BY connection_id
`

type GetConversationMCPConnectionsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConversationMCPConnections(ctx context.Context, arg GetConversationMCPConnectionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConversationMCPConnections, arg.ConversationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var connection_id uuid.UUID
		if err := rows.Scan(&connection_id); err != nil {
			return nil, err
		}
		items = append(items, connection_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationWorkspace = `-- name: GetConversationWorkspace :one
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE conversation_id=$1 AND enterprise_id=$2 AND status<>'deleted'
`

type GetConversationWorkspaceParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetConversationWorkspace(ctx context.Context, arg GetConversationWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getConversationWorkspace, arg.ConversationID, arg.EnterpriseID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileDelivery = `-- name: GetFileDelivery :one
SELECT id, enterprise_id, conversation_id, workspace_id, run_id, name, media_type, byte_size, content_hash, object_key, source_result_refs, created_at, deleted_at FROM file_deliveries WHERE id=$1 AND enterprise_id=$2 AND deleted_at IS NULL
`

type GetFileDeliveryParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetFileDelivery(ctx context.Context, arg GetFileDeliveryParams) (FileDelivery, error) {
	row := q.db.QueryRow(ctx, getFileDelivery, arg.ID, arg.EnterpriseID)
	var i FileDelivery
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.WorkspaceID,
		&i.RunID,
		&i.Name,
		&i.MediaType,
		&i.ByteSize,
		&i.ContentHash,
		&i.ObjectKey,
		&i.SourceResultRefs,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMCPConnection = `-- name: GetMCPConnection :one
SELECT id, enterprise_id, name, status, health_status, current_revision, current_tool_snapshot_id, authorization_epoch, version, last_error_code, created_by, created_at, updated_at FROM mcp_connections WHERE id = $1 AND enterprise_id = $2
`

type GetMCPConnectionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetMCPConnection(ctx context.Context, arg GetMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRow(ctx, getMCPConnection, arg.ID, arg.EnterpriseID)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.Name,
		&i.Status,
		&i.HealthStatus,
		&i.CurrentRevision,
		&i.CurrentToolSnapshotID,
		&i.AuthorizationEpoch,
		&i.Version,
		&i.LastErrorCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPConnectionRevision = `-- name: GetMCPConnectionRevision :one
SELECT connection_id, enterprise_id, revision, endpoint, auth_type, credential_id, credential_version, created_at FROM mcp_connection_revisions WHERE connection_id=$1 AND enterprise_id=$2 AND revision=$3
`

type GetMCPConnectionRevisionParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	Revision     int32     `json:"revision"`
}

func (q *Queries) GetMCPConnectionRevision(ctx context.Context, arg GetMCPConnectionRevisionParams) (McpConnectionRevision, error) {
	row := q.db.QueryRow(ctx, getMCPConnectionRevision, arg.ConnectionID, arg.EnterpriseID, arg.Revision)
	var i McpConnectionRevision
	err := row.Scan(
		&i.ConnectionID,
		&i.EnterpriseID,
		&i.Revision,
		&i.Endpoint,
		&i.AuthType,
		&i.CredentialID,
		&i.CredentialVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPToolSnapshot = `-- name: GetMCPToolSnapshot :one
SELECT id, connection_id, enterprise_id, connection_revision, schema_hash, tools, created_at FROM mcp_tool_snapshots WHERE id=$1 AND enterprise_id=$2
`

type GetMCPToolSnapshotParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetMCPToolSnapshot(ctx context.Context, arg GetMCPToolSnapshotParams) (McpToolSnapshot, error) {
	row := q.db.QueryRow(ctx, getMCPToolSnapshot, arg.ID, arg.EnterpriseID)
	var i McpToolSnapshot
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.EnterpriseID,
		&i.ConnectionRevision,
		&i.SchemaHash,
		&i.Tools,
		&i.CreatedAt,
	)
	return i, err
}

const getModelToolCall = `-- name: GetModelToolCall :one
SELECT id, call_id, enterprise_id, run_id, step_id, tool_id, source, authorization_scope, model_call_id, call_sequence, connection_id, schema_hash, dispatched_at, input, input_hash, status, error_code, created_at, updated_at FROM tool_calls WHERE step_id=$1 AND call_id=$2 AND enterprise_id=$3
`

type GetModelToolCallParams struct {
	StepID       uuid.UUID `json:"step_id"`
	CallID       string    `json:"call_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetModelToolCall(ctx context.Context, arg GetModelToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, getModelToolCall, arg.StepID, arg.CallID, arg.EnterpriseID)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.EnterpriseID,
		&i.RunID,
		&i.StepID,
		&i.ToolID,
		&i.Source,
		&i.AuthorizationScope,
		&i.ModelCallID,
		&i.CallSequence,
		&i.ConnectionID,
		&i.SchemaHash,
		&i.DispatchedAt,
		&i.Input,
		&i.InputHash,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersistedToolResult = `-- name: GetPersistedToolResult :one
SELECT id, tool_call_id, enterprise_id, artifact_id, projection, projection_hash, projection_bytes, partial, created_at FROM tool_results WHERE tool_call_id=$1 AND enterprise_id=$2
`

type GetPersistedToolResultParams struct {
	ToolCallID   uuid.UUID `json:"tool_call_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetPersistedToolResult(ctx context.Context, arg GetPersistedToolResultParams) (ToolResult, error) {
	row := q.db.QueryRow(ctx, getPersistedToolResult, arg.ToolCallID, arg.EnterpriseID)
	var i ToolResult
	err := row.Scan(
		&i.ID,
		&i.ToolCallID,
		&i.EnterpriseID,
		&i.ArtifactID,
		&i.Projection,
		&i.ProjectionHash,
		&i.ProjectionBytes,
		&i.Partial,
		&i.CreatedAt,
	)
	return i, err
}

const getRunAwaitingPendingAction = `-- name: GetRunAwaitingPendingAction :one
SELECT r.id, r.conversation_id, r.enterprise_id, r.actor_user_id, r.model_id, r.model_revision, r.locale, r.status, r.current_step_id, r.authorization_version, r.checkpoint, r.verification_only, r.tool_snapshot, r.tool_snapshot_hash, r.stop_reason, r.error_code, r.version, r.created_at, r.updated_at FROM runs r WHERE r.id=$1 AND r.enterprise_id=$2
AND r.status='waiting_input' AND r.stop_reason='pending_action_confirmation'
AND EXISTS(SELECT 1 FROM conversation_events e WHERE e.run_id=r.id
    AND e.enterprise_id=r.enterprise_id AND e.event_type='pending_action_created'
    AND e.payload->>'action_ref'=$3::text)
AND NOT EXISTS(SELECT 1 FROM pending_actions other WHERE other.run_id=r.id
    AND other.enterprise_id=r.enterprise_id AND other.action_ref<>$3::text
    AND other.status NOT IN ('cancelled','expired','rejected','invalidated'))
FOR UPDATE
`

type GetRunAwaitingPendingActionParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	ActionRef    string    `json:"action_ref"`
}

func (q *Queries) GetRunAwaitingPendingAction(ctx context.Context, arg GetRunAwaitingPendingActionParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunAwaitingPendingAction, arg.ID, arg.EnterpriseID, arg.ActionRef)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.VerificationOnly,
		&i.ToolSnapshot,
		&i.ToolSnapshotHash,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, verification_only, tool_snapshot, tool_snapshot_hash, stop_reason, error_code, version, created_at, updated_at FROM runs WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type GetRunForUpdateParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, arg.ID, arg.EnterpriseID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.EnterpriseID,
		&i.ActorUserID,
		&i.ModelID,
		&i.ModelRevision,
		&i.Locale,
		&i.Status,
		&i.CurrentStepID,
		&i.AuthorizationVersion,
		&i.Checkpoint,
		&i.VerificationOnly,
		&i.ToolSnapshot,
		&i.ToolSnapshotHash,
		&i.StopReason,
		&i.ErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolPresentation = `-- name: GetToolPresentation :one
SELECT p.id, p.enterprise_id, p.conversation_id, p.tool_call_id, p.tool_version, p.authorization_scope, p.template_hash, p.detail_data, p.resource_refs, p.status, p.created_at,a.source AS template_source FROM tool_presentations p JOIN template_assets a ON a.hash=p.template_hash
WHERE p.tool_call_id=$1 AND p.enterprise_id=$2 AND p.conversation_id=$3
`

type GetToolPresentationParams struct {
	ToolCallID     uuid.UUID `json:"tool_call_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
}

type GetToolPresentationRow struct {
	ID                 uuid.UUID          `json:"id"`
	EnterpriseID       uuid.UUID          `json:"enterprise_id"`
	ConversationID     uuid.UUID          `json:"conversation_id"`
	ToolCallID         uuid.UUID          `json:"tool_call_id"`
	ToolVersion        string             `json:"tool_version"`
	AuthorizationScope string             `json:"authorization_scope"`
	TemplateHash       string             `json:"template_hash"`
	DetailData         []byte             `json:"detail_data"`
	ResourceRefs       []byte             `json:"resource_refs"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TemplateSource     string             `json:"template_source"`
}

func (q *Queries) GetToolPresentation(ctx context.Context, arg GetToolPresentationParams) (GetToolPresentationRow, error) {
	row := q.db.QueryRow(ctx, getToolPresentation, arg.ToolCallID, arg.EnterpriseID, arg.ConversationID)
	var i GetToolPresentationRow
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.ToolCallID,
		&i.ToolVersion,
		&i.AuthorizationScope,
		&i.TemplateHash,
		&i.DetailData,
		&i.ResourceRefs,
		&i.Status,
		&i.CreatedAt,
		&i.TemplateSource,
	)
	return i, err
}

const getToolResultEventSequence = `-- name: GetToolResultEventSequence :one
SELECT sequence FROM conversation_events WHERE enterprise_id=$1 AND conversation_id=$2 AND event_type='tool_call_result'
AND payload->>'tool_call_id'=$3::text ORDER BY sequence DESC LIMIT 1
`

type GetToolResultEventSequenceParams struct {
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	ToolCallID     string    `json:"tool_call_id"`
}

func (q *Queries) GetToolResultEventSequence(ctx context.Context, arg GetToolResultEventSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, getToolResultEventSequence, arg.EnterpriseID, arg.ConversationID, arg.ToolCallID)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE id=$1 AND enterprise_id=$2
`

type GetWorkspaceParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, arg.ID, arg.EnterpriseID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceFile = `-- name: GetWorkspaceFile :one
SELECT id, enterprise_id, workspace_id, conversation_id, name, path, byte_size, content_hash, media_type, source_result_refs, created_at, deleted_at FROM workspace_files WHERE id=$1 AND enterprise_id=$2 AND deleted_at IS NULL
`

type GetWorkspaceFileParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) GetWorkspaceFile(ctx context.Context, arg GetWorkspaceFileParams) (WorkspaceFile, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFile, arg.ID, arg.EnterpriseID)
	var i WorkspaceFile
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.ConversationID,
		&i.Name,
		&i.Path,
		&i.ByteSize,
		&i.ContentHash,
		&i.MediaType,
		&i.SourceResultRefs,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceUpload = `-- name: GetWorkspaceUpload :one
SELECT id, enterprise_id, workspace_id, owner_user_id, name, path, expected_bytes, status, request_id, file_id, error_code, expires_at, created_at, updated_at FROM workspace_uploads WHERE id=$1 AND enterprise_id=$2 AND owner_user_id=$3
`

type GetWorkspaceUploadParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) GetWorkspaceUpload(ctx context.Context, arg GetWorkspaceUploadParams) (WorkspaceUpload, error) {
	row := q.db.QueryRow(ctx, getWorkspaceUpload, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i WorkspaceUpload
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.WorkspaceID,
		&i.OwnerUserID,
		&i.Name,
		&i.Path,
		&i.ExpectedBytes,
		&i.Status,
		&i.RequestID,
		&i.FileID,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantMCPConnection = `-- name: GrantMCPConnection :exec
INSERT INTO mcp_connection_grants (connection_id,enterprise_id,user_id)
VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type GrantMCPConnectionParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) GrantMCPConnection(ctx context.Context, arg GrantMCPConnectionParams) error {
	_, err := q.db.Exec(ctx, grantMCPConnection, arg.ConnectionID, arg.EnterpriseID, arg.UserID)
	return err
}

const hasMCPConnectionGrant = `-- name: HasMCPConnectionGrant :one
SELECT EXISTS(SELECT 1 FROM mcp_connection_grants g
JOIN enterprise_users u ON u.id=g.user_id AND u.enterprise_id=g.enterprise_id AND u.status='active'
JOIN enterprises e ON e.id=g.enterprise_id AND e.status='active'
WHERE g.connection_id=$1 AND g.enterprise_id=$2 AND g.user_id=$3)::boolean
`

type HasMCPConnectionGrantParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) HasMCPConnectionGrant(ctx context.Context, arg HasMCPConnectionGrantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMCPConnectionGrant, arg.ConnectionID, arg.EnterpriseID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasUnknownRunToolResult = `-- name: HasUnknownRunToolResult :one
SELECT EXISTS(SELECT 1 FROM tool_calls WHERE run_id=$1 AND enterprise_id=$2 AND status='result_unknown')
`

type HasUnknownRunToolResultParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) HasUnknownRunToolResult(ctx context.Context, arg HasUnknownRunToolResultParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnknownRunToolResult, arg.RunID, arg.EnterpriseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRuntimeTaskLeaseCurrent = `-- name: IsRuntimeTaskLeaseCurrent :one
SELECT EXISTS(SELECT 1 FROM runtime_tasks WHERE id=$1 AND lease_owner=$2 AND fence_token=$3 AND status='running' AND lease_until>now())::boolean
`

type IsRuntimeTaskLeaseCurrentParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
	FenceToken int64       `json:"fence_token"`
}

func (q *Queries) IsRuntimeTaskLeaseCurrent(ctx context.Context, arg IsRuntimeTaskLeaseCurrentParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRuntimeTaskLeaseCurrent, arg.ID, arg.LeaseOwner, arg.FenceToken)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listConversationActionFacts = `-- name: ListConversationActionFacts :many
SELECT action.action_ref,action.status,action.resource_type,action.resource_id,
 action.result_summary,action.error_code,execution.execution_ref,execution.status AS execution_status
FROM pending_actions action JOIN runs run ON run.id=action.run_id AND run.enterprise_id=action.enterprise_id
LEFT JOIN executions execution ON execution.pending_action_id=action.id AND execution.enterprise_id=action.enterprise_id
WHERE run.conversation_id=$1 AND action.enterprise_id=$2 AND action.creator_subject_id=$3
ORDER BY action.updated_at DESC LIMIT 20
`

type ListConversationActionFactsParams struct {
	ConversationID   uuid.UUID `json:"conversation_id"`
	EnterpriseID     uuid.UUID `json:"enterprise_id"`
	CreatorSubjectID uuid.UUID `json:"creator_subject_id"`
}

type ListConversationActionFactsRow struct {
	ActionRef       string        `json:"action_ref"`
	Status          string        `json:"status"`
	ResourceType    string        `json:"resource_type"`
	ResourceID      uuid.NullUUID `json:"resource_id"`
	ResultSummary   string        `json:"result_summary"`
	ErrorCode       pgtype.Text   `json:"error_code"`
	ExecutionRef    pgtype.Text   `json:"execution_ref"`
	ExecutionStatus pgtype.Text   `json:"execution_status"`
}

func (q *Queries) ListConversationActionFacts(ctx context.Context, arg ListConversationActionFactsParams) ([]ListConversationActionFactsRow, error) {
	rows, err := q.db.Query(ctx, listConversationActionFacts, arg.ConversationID, arg.EnterpriseID, arg.CreatorSubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationActionFactsRow{}
	for rows.Next() {
		var i ListConversationActionFactsRow
		if err := rows.Scan(
			&i.ActionRef,
			&i.Status,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResultSummary,
			&i.ErrorCode,
			&i.ExecutionRef,
			&i.ExecutionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationContextEvents = `-- name: ListConversationContextEvents :many
SELECT id, enterprise_id, conversation_id, run_id, step_id, sequence, event_type, actor_type, actor_id, payload, content_hash, artifact_ref, data_classification, occurred_at FROM conversation_events WHERE conversation_id=$1 AND enterprise_id=$2 AND sequence>$3 ORDER BY sequence LIMIT $4
`

type ListConversationContextEventsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
	Sequence       int64     `json:"sequence"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListConversationContextEvents(ctx context.Context, arg ListConversationContextEventsParams) ([]ConversationEvent, error) {
	rows, err := q.db.Query(ctx, listConversationContextEvents,
		arg.ConversationID,
		arg.EnterpriseID,
		arg.Sequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationEvent{}
	for rows.Next() {
		var i ConversationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.RunID,
			&i.StepID,
			&i.Sequence,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.ContentHash,
			&i.ArtifactRef,
			&i.DataClassification,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedMCPConnections = `-- name: ListGrantedMCPConnections :many
SELECT c.id, c.enterprise_id, c.name, c.status, c.health_status, c.current_revision, c.current_tool_snapshot_id, c.authorization_epoch, c.version, c.last_error_code, c.created_by, c.created_at, c.updated_at FROM mcp_connections c
JOIN mcp_connection_grants g ON g.connection_id = c.id AND g.enterprise_id = c.enterprise_id
WHERE c.enterprise_id = $1 AND g.user_id = $2
ORDER BY c.name, c.id
`

type ListGrantedMCPConnectionsParams struct {
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) ListGrantedMCPConnections(ctx context.Context, arg ListGrantedMCPConnectionsParams) ([]McpConnection, error) {
	rows, err := q.db.Query(ctx, listGrantedMCPConnections, arg.EnterpriseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpConnection{}
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Status,
			&i.HealthStatus,
			&i.CurrentRevision,
			&i.CurrentToolSnapshotID,
			&i.AuthorizationEpoch,
			&i.Version,
			&i.LastErrorCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdleWorkspaces = `-- name: ListIdleWorkspaces :many
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE status='ready' AND active_pod_name IS NOT NULL
AND last_used_at<$1 AND (lease_until IS NULL OR lease_until<now()) ORDER BY last_used_at LIMIT $2
`

type ListIdleWorkspacesParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListIdleWorkspaces(ctx context.Context, arg ListIdleWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listIdleWorkspaces, arg.LastUsedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeUid,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.Status,
			&i.PvcName,
			&i.Namespace,
			&i.CapacityBytes,
			&i.EnvironmentVersion,
			&i.SourceResultRefs,
			&i.ActivePodName,
			&i.ActiveSandboxID,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.FenceToken,
			&i.Version,
			&i.LastUsedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPConnectionMembers = `-- name: ListMCPConnectionMembers :many
SELECT user_id FROM mcp_connection_grants WHERE connection_id=$1 AND enterprise_id=$2 ORDER BY user_id
`

type ListMCPConnectionMembersParams struct {
	ConnectionID uuid.UUID `json:"connection_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListMCPConnectionMembers(ctx context.Context, arg ListMCPConnectionMembersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMCPConnectionMembers, arg.ConnectionID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPConnections = `-- name: ListMCPConnections :many
SELECT id, enterprise_id, name, status, health_status, current_revision, current_tool_snapshot_id, authorization_epoch, version, last_error_code, created_by, created_at, updated_at FROM mcp_connections WHERE enterprise_id = $1 ORDER BY name, id
`

func (q *Queries) ListMCPConnections(ctx context.Context, enterpriseID uuid.UUID) ([]McpConnection, error) {
	rows, err := q.db.Query(ctx, listMCPConnections, enterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpConnection{}
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.Name,
			&i.Status,
			&i.HealthStatus,
			&i.CurrentRevision,
			&i.CurrentToolSnapshotID,
			&i.AuthorizationEpoch,
			&i.Version,
			&i.LastErrorCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedRunToolCalls = `-- name: ListUnfinishedRunToolCalls :many
SELECT call.id, call.call_id, call.enterprise_id, call.run_id, call.step_id, call.tool_id, call.source, call.authorization_scope, call.model_call_id, call.call_sequence, call.connection_id, call.schema_hash, call.dispatched_at, call.input, call.input_hash, call.status, call.error_code, call.created_at, call.updated_at FROM tool_calls call JOIN run_steps step ON step.id=call.step_id
WHERE call.run_id=$1 AND call.enterprise_id=$2 AND call.status IN ('prepared','dispatched')
ORDER BY step.sequence,call.call_sequence
`

type ListUnfinishedRunToolCallsParams struct {
	RunID        uuid.UUID `json:"run_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListUnfinishedRunToolCalls(ctx context.Context, arg ListUnfinishedRunToolCallsParams) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listUnfinishedRunToolCalls, arg.RunID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.EnterpriseID,
			&i.RunID,
			&i.StepID,
			&i.ToolID,
			&i.Source,
			&i.AuthorizationScope,
			&i.ModelCallID,
			&i.CallSequence,
			&i.ConnectionID,
			&i.SchemaHash,
			&i.DispatchedAt,
			&i.Input,
			&i.InputHash,
			&i.Status,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDeliveries = `-- name: ListWorkspaceDeliveries :many
SELECT id, enterprise_id, conversation_id, workspace_id, run_id, name, media_type, byte_size, content_hash, object_key, source_result_refs, created_at, deleted_at FROM file_deliveries WHERE workspace_id=$1 AND enterprise_id=$2 AND deleted_at IS NULL ORDER BY created_at,id
`

type ListWorkspaceDeliveriesParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListWorkspaceDeliveries(ctx context.Context, arg ListWorkspaceDeliveriesParams) ([]FileDelivery, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDeliveries, arg.WorkspaceID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileDelivery{}
	for rows.Next() {
		var i FileDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.WorkspaceID,
			&i.RunID,
			&i.Name,
			&i.MediaType,
			&i.ByteSize,
			&i.ContentHash,
			&i.ObjectKey,
			&i.SourceResultRefs,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceFiles = `-- name: ListWorkspaceFiles :many
SELECT id, enterprise_id, workspace_id, conversation_id, name, path, byte_size, content_hash, media_type, source_result_refs, created_at, deleted_at FROM workspace_files WHERE workspace_id=$1 AND enterprise_id=$2 AND deleted_at IS NULL ORDER BY created_at,id
`

type ListWorkspaceFilesParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ListWorkspaceFiles(ctx context.Context, arg ListWorkspaceFilesParams) ([]WorkspaceFile, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFiles, arg.WorkspaceID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceFile{}
	for rows.Next() {
		var i WorkspaceFile
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.WorkspaceID,
			&i.ConversationID,
			&i.Name,
			&i.Path,
			&i.ByteSize,
			&i.ContentHash,
			&i.MediaType,
			&i.SourceResultRefs,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuntimeTaskLease = `-- name: LockRuntimeTaskLease :one
SELECT id FROM runtime_tasks WHERE id=$1 AND lease_owner=$2 AND fence_token=$3 AND status='running' AND lease_until>now() FOR UPDATE
`

type LockRuntimeTaskLeaseParams struct {
	ID         uuid.UUID   `json:"id"`
	LeaseOwner pgtype.Text `json:"lease_owner"`
	FenceToken int64       `json:"fence_token"`
}

func (q *Queries) LockRuntimeTaskLease(ctx context.Context, arg LockRuntimeTaskLeaseParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRuntimeTaskLease, arg.ID, arg.LeaseOwner, arg.FenceToken)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE id=$1 AND enterprise_id=$2 FOR UPDATE
`

type LockWorkspaceParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) LockWorkspace(ctx context.Context, arg LockWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, arg.ID, arg.EnterpriseID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markMCPManagedSecret = `-- name: MarkMCPManagedSecret :exec
UPDATE secrets SET owner_type='mcp_connection',owner_id=$3 WHERE id=$1 AND enterprise_id=$2
`

type MarkMCPManagedSecretParams struct {
	ID           uuid.UUID     `json:"id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	OwnerID      uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) MarkMCPManagedSecret(ctx context.Context, arg MarkMCPManagedSecretParams) error {
	_, err := q.db.Exec(ctx, markMCPManagedSecret, arg.ID, arg.EnterpriseID, arg.OwnerID)
	return err
}

const markModelDispatched = `-- name: MarkModelDispatched :exec
UPDATE model_calls SET status='running',projection_hash=$3,tool_snapshot_hash=$4,capability_snapshot=$5,
dispatched_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='reserved'
`

type MarkModelDispatchedParams struct {
	ID                 uuid.UUID `json:"id"`
	EnterpriseID       uuid.UUID `json:"enterprise_id"`
	ProjectionHash     []byte    `json:"projection_hash"`
	ToolSnapshotHash   string    `json:"tool_snapshot_hash"`
	CapabilitySnapshot []byte    `json:"capability_snapshot"`
}

func (q *Queries) MarkModelDispatched(ctx context.Context, arg MarkModelDispatchedParams) error {
	_, err := q.db.Exec(ctx, markModelDispatched,
		arg.ID,
		arg.EnterpriseID,
		arg.ProjectionHash,
		arg.ToolSnapshotHash,
		arg.CapabilitySnapshot,
	)
	return err
}

const markRunVerificationOnly = `-- name: MarkRunVerificationOnly :exec
UPDATE runs SET verification_only=true,updated_at=now() WHERE id=$1 AND enterprise_id=$2
`

type MarkRunVerificationOnlyParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkRunVerificationOnly(ctx context.Context, arg MarkRunVerificationOnlyParams) error {
	_, err := q.db.Exec(ctx, markRunVerificationOnly, arg.ID, arg.EnterpriseID)
	return err
}

const markToolDispatched = `-- name: MarkToolDispatched :execrows
UPDATE tool_calls SET status='dispatched',dispatched_at=now(),updated_at=now()
WHERE tool_calls.id=$1 AND tool_calls.enterprise_id=$2 AND tool_calls.status='prepared'
AND EXISTS(SELECT 1 FROM runs r WHERE r.id=tool_calls.run_id AND r.enterprise_id=tool_calls.enterprise_id
  AND r.version=$3 AND r.status NOT IN ('succeeded','failed','cancelled'))
`

type MarkToolDispatchedParams struct {
	ID                 uuid.UUID `json:"id"`
	EnterpriseID       uuid.UUID `json:"enterprise_id"`
	ExpectedRunVersion int64     `json:"expected_run_version"`
}
