// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_overview.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformMonthlySandboxUsage = `-- name: GetPlatformMonthlySandboxUsage :many
SELECT to_char(month, 'YYYY-MM')::text AS month,
  sum(session_count)::bigint AS session_count, sum(session_seconds)::bigint AS session_seconds
FROM sandbox_usage
WHERE month >= $1::date AND month < $2::date
GROUP BY month ORDER BY month
`

type GetPlatformMonthlySandboxUsageParams struct {
	FromMonth pgtype.Date `json:"from_month"`
	ToMonth   pgtype.Date `json:"to_month"`
}

type GetPlatformMonthlySandboxUsageRow struct {
	Month          string `json:"month"`
	SessionCount   int64  `json:"session_count"`
	SessionSeconds int64  `json:"session_seconds"`
}

func (q *Queries) GetPlatformMonthlySandboxUsage(ctx context.Context, arg GetPlatformMonthlySandboxUsageParams) ([]GetPlatformMonthlySandboxUsageRow, error) {
	rows, err := q.db.Query(ctx, getPlatformMonthlySandboxUsage, arg.FromMonth, arg.ToMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlatformMonthlySandboxUsageRow{}
	for rows.Next() {
		var i GetPlatformMonthlySandboxUsageRow
		if err := rows.Scan(&i.Month, &i.SessionCount, &i.SessionSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatformOverviewCounts = `-- name: GetPlatformOverviewCounts :one
SELECT
  (SELECT count(*) FROM enterprises)::bigint AS enterprise_count,
  (SELECT count(*) FROM enterprises WHERE status = 'active')::bigint AS active_enterprise_count,
  (SELECT count(*) FROM sandbox_sessions WHERE status IN ('creating', 'running', 'terminating', 'unknown'))::bigint AS active_sandbox_session_count,
  (SELECT count(*) FROM enterprise_users eu
   WHERE eu.status = 'active' AND eu.last_login_at IS NULL AND EXISTS (
     SELECT 1 FROM role_bindings rb
     JOIN roles r ON r.id = rb.role_id AND r.enterprise_id = rb.enterprise_id
     WHERE rb.enterprise_id = eu.enterprise_id AND rb.subject_type = 'user' AND rb.subject_id = eu.id
       AND rb.status = 'active' AND r.identity_key = 'enterprise_admin' AND r.builtin AND r.status = 'active'
       AND (rb.valid_from IS NULL OR rb.valid_from <= now()) AND (rb.valid_until IS NULL OR rb.valid_until > now())
   ))::bigint AS pending_admin_count
`

type GetPlatformOverviewCountsRow struct {
	EnterpriseCount           int64 `json:"enterprise_count"`
	ActiveEnterpriseCount     int64 `json:"active_enterprise_count"`
	ActiveSandboxSessionCount int64 `json:"active_sandbox_session_count"`
	PendingAdminCount         int64 `json:"pending_admin_count"`
}

func (q *Queries) GetPlatformOverviewCounts(ctx context.Context) (GetPlatformOverviewCountsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOverviewCounts)
	var i GetPlatformOverviewCountsRow
	err := row.Scan(
		&i.EnterpriseCount,
		&i.ActiveEnterpriseCount,
		&i.ActiveSandboxSessionCount,
		&i.PendingAdminCount,
	)
	return i, err
}
