// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_actions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const hasRunPendingActionEvent = `-- name: HasRunPendingActionEvent :one
SELECT EXISTS(SELECT 1 FROM conversation_events
WHERE run_id=$1 AND enterprise_id=$2 AND event_type='pending_action_created'
AND payload->>'action_ref'=$3::text)
`

type HasRunPendingActionEventParams struct {
	RunID        uuid.NullUUID `json:"run_id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
	ActionRef    string        `json:"action_ref"`
}

func (q *Queries) HasRunPendingActionEvent(ctx context.Context, arg HasRunPendingActionEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunPendingActionEvent, arg.RunID, arg.EnterpriseID, arg.ActionRef)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRunPendingActions = `-- name: ListRunPendingActions :many
SELECT id, action_ref, enterprise_id, creator_subject_id, authorization_version, action_type, title, summary, risk, preview, diff, status, resource_type, resource_id, expected_resource_version, impact_hash, result_resource_type, result_resource_id, result_resource_version, result_summary, error_code, expires_at, created_at, updated_at, creator_subject_type, run_id, confirmation_required, policy_snapshot_hash FROM pending_actions
WHERE run_id=$1 AND enterprise_id=$2 AND creator_subject_id=$3 AND creator_subject_type='user'
ORDER BY created_at,id
`

type ListRunPendingActionsParams struct {
	RunID            uuid.NullUUID `json:"run_id"`
	EnterpriseID     uuid.UUID     `json:"enterprise_id"`
	CreatorSubjectID uuid.UUID     `json:"creator_subject_id"`
}

func (q *Queries) ListRunPendingActions(ctx context.Context, arg ListRunPendingActionsParams) ([]PendingAction, error) {
	rows, err := q.db.Query(ctx, listRunPendingActions, arg.RunID, arg.EnterpriseID, arg.CreatorSubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingAction{}
	for rows.Next() {
		var i PendingAction
		if err := rows.Scan(
			&i.ID,
			&i.ActionRef,
			&i.EnterpriseID,
			&i.CreatorSubjectID,
			&i.AuthorizationVersion,
			&i.ActionType,
			&i.Title,
			&i.Summary,
			&i.Risk,
			&i.Preview,
			&i.Diff,
			&i.Status,
			&i.ResourceType,
			&i.ResourceID,
			&i.ExpectedResourceVersion,
			&i.ImpactHash,
			&i.ResultResourceType,
			&i.ResultResourceID,
			&i.ResultResourceVersion,
			&i.ResultSummary,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorSubjectType,
			&i.RunID,
			&i.ConfirmationRequired,
			&i.PolicySnapshotHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
