// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.
package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

func (q *Queries) UpsertCollectorForAction(ctx context.Context, arg UpsertCollectorForActionParams) (CollectorInstance, error) {
	row := q.db.QueryRow(ctx, upsertCollectorForAction,
		arg.ID,
		arg.EnterpriseID,
		arg.ResourceType,
		arg.ResourceID,
		arg.DistributionVersionID,
		arg.Platform,
		arg.Role,
	)
	var i CollectorInstance
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.ResourceType,
		&i.ResourceID,
		&i.DistributionVersionID,
		&i.Platform,
		&i.Role,
		&i.Status,
		&i.DesiredRevision,
		&i.EffectiveRevision,
		&i.AuthorizationVersion,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceGeneration,
	)
	return i, err
}

const upsertKubernetesNodeHostBindingProposal = `-- name: UpsertKubernetesNodeHostBindingProposal :one
INSERT INTO kubernetes_node_host_bindings (
  id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id,
  matched_by, evidence, evidence_hash, confidence, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'proposed')
ON CONFLICT (enterprise_id, kubernetes_cluster_id, node_uid) DO UPDATE SET
  node_name = EXCLUDED.node_name,
	host_id = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.host_id ELSE EXCLUDED.host_id END,
  evidence = EXCLUDED.evidence,
  evidence_hash = EXCLUDED.evidence_hash,
	matched_by = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.matched_by ELSE EXCLUDED.matched_by END,
	confidence = CASE
		WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash
		THEN kubernetes_node_host_bindings.confidence ELSE EXCLUDED.confidence END,
  status = CASE WHEN kubernetes_node_host_bindings.status = 'verified' AND kubernetes_node_host_bindings.evidence_hash = EXCLUDED.evidence_hash THEN 'verified' ELSE 'proposed' END,
  version = kubernetes_node_host_bindings.version + 1,
  updated_at = now()
RETURNING id, enterprise_id, kubernetes_cluster_id, node_uid, node_name, host_id, matched_by, evidence, evidence_hash, confidence, status, version, created_at, updated_at
`

type UpsertKubernetesNodeHostBindingProposalParams struct {
	ID                  uuid.UUID     `json:"id"`
	EnterpriseID        uuid.UUID     `json:"enterprise_id"`
	KubernetesClusterID uuid.UUID     `json:"kubernetes_cluster_id"`
	NodeUid             string        `json:"node_uid"`
	NodeName            string        `json:"node_name"`
	HostID              uuid.NullUUID `json:"host_id"`
	MatchedBy           string        `json:"matched_by"`
	Evidence            []byte        `json:"evidence"`
	EvidenceHash        []byte        `json:"evidence_hash"`
	Confidence          int32         `json:"confidence"`
}

func (q *Queries) UpsertKubernetesNodeHostBindingProposal(ctx context.Context, arg UpsertKubernetesNodeHostBindingProposalParams) (KubernetesNodeHostBinding, error) {
	row := q.db.QueryRow(ctx, upsertKubernetesNodeHostBindingProposal,
		arg.ID,
		arg.EnterpriseID,
		arg.KubernetesClusterID,
		arg.NodeUid,
		arg.NodeName,
		arg.HostID,
		arg.MatchedBy,
		arg.Evidence,
		arg.EvidenceHash,
		arg.Confidence,
	)
	var i KubernetesNodeHostBinding
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.KubernetesClusterID,
		&i.NodeUid,
		&i.NodeName,
		&i.HostID,
		&i.MatchedBy,
		&i.Evidence,
		&i.EvidenceHash,
		&i.Confidence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTelemetryRoute = `-- name: UpsertTelemetryRoute :one
INSERT INTO telemetry_routes (
  id, enterprise_id, collector_id, kind, gateway_collector_id, transport, loopback_port, status
) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending')
ON CONFLICT (collector_id) DO UPDATE SET
  kind = EXCLUDED.kind,
  gateway_collector_id = EXCLUDED.gateway_collector_id,
  transport = EXCLUDED.transport,
  loopback_port = EXCLUDED.loopback_port,
  status = 'pending',
  version = telemetry_routes.version + 1,
  updated_at = now()
RETURNING id, enterprise_id, collector_id, kind, gateway_collector_id, status, version, last_tested_at, created_at, updated_at, transport, loopback_port
`

type UpsertTelemetryRouteParams struct {
	ID                 uuid.UUID     `json:"id"`
	EnterpriseID       uuid.UUID     `json:"enterprise_id"`
	CollectorID        uuid.UUID     `json:"collector_id"`
	Kind               string        `json:"kind"`
	GatewayCollectorID uuid.NullUUID `json:"gateway_collector_id"`
	Transport          string        `json:"transport"`
	LoopbackPort       pgtype.Int4   `json:"loopback_port"`
}

func (q *Queries) UpsertTelemetryRoute(ctx context.Context, arg UpsertTelemetryRouteParams) (TelemetryRoute, error) {
	row := q.db.QueryRow(ctx, upsertTelemetryRoute,
		arg.ID,
		arg.EnterpriseID,
		arg.CollectorID,
		arg.Kind,
		arg.GatewayCollectorID,
		arg.Transport,
		arg.LoopbackPort,
	)
	var i TelemetryRoute
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.Kind,
		&i.GatewayCollectorID,
		&i.Status,
		&i.Version,
		&i.LastTestedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Transport,
		&i.LoopbackPort,
	)
	return i, err
}
