// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telemetry_sources.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listTelemetrySources = `-- name: ListTelemetrySources :many
SELECT source.id, source.enterprise_id, source.collector_id, source.generation, source.resource_type, source.resource_id, source.source_key, source.source_type, source.signals, source.config_revision, source.config_hash, source.capability_version, source.created_at, (source.generation=collector.source_generation AND collector.status NOT IN ('uninstalled','uninstalling'))::boolean AS current_installation
FROM telemetry_sources source JOIN collector_instances collector ON collector.id=source.collector_id AND collector.enterprise_id=source.enterprise_id
WHERE source.enterprise_id=$1
 AND source.resource_id=ANY($2::uuid[]) AND source.source_type=$3
 AND $4::text=ANY(source.signals)
ORDER BY source.id,source.config_revision
`

type ListTelemetrySourcesParams struct {
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	ResourceIds  []uuid.UUID `json:"resource_ids"`
	SourceType   string      `json:"source_type"`
	Signal       string      `json:"signal"`
}

type ListTelemetrySourcesRow struct {
	ID                  uuid.UUID          `json:"id"`
	EnterpriseID        uuid.UUID          `json:"enterprise_id"`
	CollectorID         uuid.UUID          `json:"collector_id"`
	Generation          uuid.UUID          `json:"generation"`
	ResourceType        string             `json:"resource_type"`
	ResourceID          uuid.UUID          `json:"resource_id"`
	SourceKey           string             `json:"source_key"`
	SourceType          string             `json:"source_type"`
	Signals             []string           `json:"signals"`
	ConfigRevision      int64              `json:"config_revision"`
	ConfigHash          []byte             `json:"config_hash"`
	CapabilityVersion   string             `json:"capability_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CurrentInstallation bool               `json:"current_installation"`
}

func (q *Queries) ListTelemetrySources(ctx context.Context, arg ListTelemetrySourcesParams) ([]ListTelemetrySourcesRow, error) {
	rows, err := q.db.Query(ctx, listTelemetrySources,
		arg.EnterpriseID,
		arg.ResourceIds,
		arg.SourceType,
		arg.Signal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTelemetrySourcesRow{}
	for rows.Next() {
		var i ListTelemetrySourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.CollectorID,
			&i.Generation,
			&i.ResourceType,
			&i.ResourceID,
			&i.SourceKey,
			&i.SourceType,
			&i.Signals,
			&i.ConfigRevision,
			&i.ConfigHash,
			&i.CapabilityVersion,
			&i.CreatedAt,
			&i.CurrentInstallation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerTelemetrySource = `-- name: RegisterTelemetrySource :exec
INSERT INTO telemetry_sources(id,enterprise_id,collector_id,generation,resource_type,resource_id,source_key,source_type,signals,config_revision,config_hash,capability_version)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type RegisterTelemetrySourceParams struct {
	ID                uuid.UUID `json:"id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	CollectorID       uuid.UUID `json:"collector_id"`
	Generation        uuid.UUID `json:"generation"`
	ResourceType      string    `json:"resource_type"`
	ResourceID        uuid.UUID `json:"resource_id"`
	SourceKey         string    `json:"source_key"`
	SourceType        string    `json:"source_type"`
	Signals           []string  `json:"signals"`
	ConfigRevision    int64     `json:"config_revision"`
	ConfigHash        []byte    `json:"config_hash"`
	CapabilityVersion string    `json:"capability_version"`
}

func (q *Queries) RegisterTelemetrySource(ctx context.Context, arg RegisterTelemetrySourceParams) error {
	_, err := q.db.Exec(ctx, registerTelemetrySource,
		arg.ID,
		arg.EnterpriseID,
		arg.CollectorID,
		arg.Generation,
		arg.ResourceType,
		arg.ResourceID,
		arg.SourceKey,
		arg.SourceType,
		arg.Signals,
		arg.ConfigRevision,
		arg.ConfigHash,
		arg.CapabilityVersion,
	)
	return err
}

const resolveTelemetrySource = `-- name: ResolveTelemetrySource :one
SELECT source.id, source.enterprise_id, source.collector_id, source.generation, source.resource_type, source.resource_id, source.source_key, source.source_type, source.signals, source.config_revision, source.config_hash, source.capability_version, source.created_at FROM telemetry_sources source
JOIN collector_instances collector ON collector.id=source.collector_id AND collector.enterprise_id=source.enterprise_id AND collector.source_generation=source.generation
WHERE source.id=$1 AND source.config_revision=$2 AND source.collector_id=$3 AND source.enterprise_id=$4
 AND source.resource_id=collector.resource_id AND source.resource_type=collector.resource_type
 AND collector.status NOT IN ('uninstalled','uninstalling')
`

type ResolveTelemetrySourceParams struct {
	ID             uuid.UUID `json:"id"`
	ConfigRevision int64     `json:"config_revision"`
	CollectorID    uuid.UUID `json:"collector_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) ResolveTelemetrySource(ctx context.Context, arg ResolveTelemetrySourceParams) (TelemetrySource, error) {
	row := q.db.QueryRow(ctx, resolveTelemetrySource,
		arg.ID,
		arg.ConfigRevision,
		arg.CollectorID,
		arg.EnterpriseID,
	)
	var i TelemetrySource
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.CollectorID,
		&i.Generation,
		&i.ResourceType,
		&i.ResourceID,
		&i.SourceKey,
		&i.SourceType,
		&i.Signals,
		&i.ConfigRevision,
		&i.ConfigHash,
		&i.CapabilityVersion,
		&i.CreatedAt,
	)
	return i, err
}
