// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_runtime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelConversationAgentRuns = `-- name: CancelConversationAgentRuns :many
UPDATE runs SET status='cancelled',stop_reason='workspace_deleted',version=version+1,updated_at=now()
WHERE conversation_id=$1 AND enterprise_id=$2 AND status NOT IN ('succeeded','failed','cancelled') RETURNING id, conversation_id, enterprise_id, actor_user_id, model_id, model_revision, locale, status, current_step_id, authorization_version, checkpoint, verification_only, tool_snapshot, tool_snapshot_hash, stop_reason, error_code, version, created_at, updated_at
`

type CancelConversationAgentRunsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) CancelConversationAgentRuns(ctx context.Context, arg CancelConversationAgentRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, cancelConversationAgentRuns, arg.ConversationID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.EnterpriseID,
			&i.ActorUserID,
			&i.ModelID,
			&i.ModelRevision,
			&i.Locale,
			&i.Status,
			&i.CurrentStepID,
			&i.AuthorizationVersion,
			&i.Checkpoint,
			&i.VerificationOnly,
			&i.ToolSnapshot,
			&i.ToolSnapshotHash,
			&i.StopReason,
			&i.ErrorCode,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimWorkspaceDeletion = `-- name: ClaimWorkspaceDeletion :one
UPDATE workspaces SET lease_owner=$3,lease_until=now()+$4::interval,fence_token=fence_token+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='deleting' AND (lease_until IS NULL OR lease_until<now()) RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type ClaimWorkspaceDeletionParams struct {
	ID           uuid.UUID       `json:"id"`
	EnterpriseID uuid.UUID       `json:"enterprise_id"`
	LeaseOwner   pgtype.Text     `json:"lease_owner"`
	Column4      pgtype.Interval `json:"column_4"`
}

func (q *Queries) ClaimWorkspaceDeletion(ctx context.Context, arg ClaimWorkspaceDeletionParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, claimWorkspaceDeletion,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.Column4,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimWorkspaceProvision = `-- name: ClaimWorkspaceProvision :one
UPDATE workspaces SET lease_owner=$3,lease_until=now()+$4::interval,fence_token=fence_token+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='provisioning' AND (lease_until IS NULL OR lease_until<now()) RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type ClaimWorkspaceProvisionParams struct {
	ID           uuid.UUID       `json:"id"`
	EnterpriseID uuid.UUID       `json:"enterprise_id"`
	LeaseOwner   pgtype.Text     `json:"lease_owner"`
	Column4      pgtype.Interval `json:"column_4"`
}

func (q *Queries) ClaimWorkspaceProvision(ctx context.Context, arg ClaimWorkspaceProvisionParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, claimWorkspaceProvision,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.Column4,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspaceSandboxSession = `-- name: CreateWorkspaceSandboxSession :one
INSERT INTO sandbox_sessions (id,enterprise_id,workspace_id,tool_call_id,profile_id,profile_revision,upstream_session_id,status,expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,'creating',$8) RETURNING id, enterprise_id, task_id, workspace_id, tool_call_id, profile_id, profile_revision, upstream_session_id, status, expires_at, started_at, terminated_at, created_at, updated_at
`

type CreateWorkspaceSandboxSessionParams struct {
	ID                uuid.UUID          `json:"id"`
	EnterpriseID      uuid.UUID          `json:"enterprise_id"`
	WorkspaceID       uuid.NullUUID      `json:"workspace_id"`
	ToolCallID        uuid.NullUUID      `json:"tool_call_id"`
	ProfileID         uuid.UUID          `json:"profile_id"`
	ProfileRevision   int32              `json:"profile_revision"`
	UpstreamSessionID string             `json:"upstream_session_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWorkspaceSandboxSession(ctx context.Context, arg CreateWorkspaceSandboxSessionParams) (SandboxSession, error) {
	row := q.db.QueryRow(ctx, createWorkspaceSandboxSession,
		arg.ID,
		arg.EnterpriseID,
		arg.WorkspaceID,
		arg.ToolCallID,
		arg.ProfileID,
		arg.ProfileRevision,
		arg.UpstreamSessionID,
		arg.ExpiresAt,
	)
	var i SandboxSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.TaskID,
		&i.WorkspaceID,
		&i.ToolCallID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.UpstreamSessionID,
		&i.Status,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.TerminatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireWorkspaceUploads = `-- name: ExpireWorkspaceUploads :many
UPDATE workspace_uploads SET status='failed',error_code='WORKSPACE_UPLOAD_EXPIRED',updated_at=now()
WHERE expires_at<now() AND status IN ('pending','uploading') RETURNING id, enterprise_id, workspace_id, owner_user_id, name, path, expected_bytes, status, request_id, file_id, error_code, expires_at, created_at, updated_at
`

func (q *Queries) ExpireWorkspaceUploads(ctx context.Context) ([]WorkspaceUpload, error) {
	rows, err := q.db.Query(ctx, expireWorkspaceUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceUpload{}
	for rows.Next() {
		var i WorkspaceUpload
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.WorkspaceID,
			&i.OwnerUserID,
			&i.Name,
			&i.Path,
			&i.ExpectedBytes,
			&i.Status,
			&i.RequestID,
			&i.FileID,
			&i.ErrorCode,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failDeletedWorkspaceUploads = `-- name: FailDeletedWorkspaceUploads :exec
UPDATE workspace_uploads SET status='failed',error_code='WORKSPACE_DELETED',updated_at=now()
WHERE workspace_id=$1 AND enterprise_id=$2 AND status IN ('pending','uploading')
`

type FailDeletedWorkspaceUploadsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) FailDeletedWorkspaceUploads(ctx context.Context, arg FailDeletedWorkspaceUploadsParams) error {
	_, err := q.db.Exec(ctx, failDeletedWorkspaceUploads, arg.WorkspaceID, arg.EnterpriseID)
	return err
}

const finishConversationFileCleanup = `-- name: FinishConversationFileCleanup :exec
UPDATE conversations SET files_cleaned_at=now() WHERE id=$1 AND status='deleted'
`

func (q *Queries) FinishConversationFileCleanup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishConversationFileCleanup, id)
	return err
}

const finishWorkspaceDeletion = `-- name: FinishWorkspaceDeletion :execrows
UPDATE workspaces SET status='deleted',deleted_at=now(),version=version+1,lease_owner=NULL,lease_until=NULL,
active_pod_name=NULL,active_sandbox_id=NULL,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='deleting' AND lease_owner=$3 AND fence_token=$4 AND lease_until>now()
`

type FinishWorkspaceDeletionParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	FenceToken   int64       `json:"fence_token"`
}

func (q *Queries) FinishWorkspaceDeletion(ctx context.Context, arg FinishWorkspaceDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishWorkspaceDeletion,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.FenceToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceForAdmission = `-- name: GetWorkspaceForAdmission :one
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE id=$1 AND namespace=$2 AND fence_token=$3 AND lease_until>now() AND status='ready'
`

type GetWorkspaceForAdmissionParams struct {
	ID         uuid.UUID `json:"id"`
	Namespace  string    `json:"namespace"`
	FenceToken int64     `json:"fence_token"`
}

func (q *Queries) GetWorkspaceForAdmission(ctx context.Context, arg GetWorkspaceForAdmissionParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForAdmission, arg.ID, arg.Namespace, arg.FenceToken)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceQuota = `-- name: GetWorkspaceQuota :one
SELECT enterprise_id, limit_bytes, reserved_bytes, updated_at FROM workspace_quotas WHERE enterprise_id=$1
`

func (q *Queries) GetWorkspaceQuota(ctx context.Context, enterpriseID uuid.UUID) (WorkspaceQuota, error) {
	row := q.db.QueryRow(ctx, getWorkspaceQuota, enterpriseID)
	var i WorkspaceQuota
	err := row.Scan(
		&i.EnterpriseID,
		&i.LimitBytes,
		&i.ReservedBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceSandboxSession = `-- name: GetWorkspaceSandboxSession :one
SELECT id, enterprise_id, task_id, workspace_id, tool_call_id, profile_id, profile_revision, upstream_session_id, status, expires_at, started_at, terminated_at, created_at, updated_at FROM sandbox_sessions WHERE tool_call_id=$1 AND enterprise_id=$2
`

type GetWorkspaceSandboxSessionParams struct {
	ToolCallID   uuid.NullUUID `json:"tool_call_id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
}

func (q *Queries) GetWorkspaceSandboxSession(ctx context.Context, arg GetWorkspaceSandboxSessionParams) (SandboxSession, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSandboxSession, arg.ToolCallID, arg.EnterpriseID)
	var i SandboxSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.TaskID,
		&i.WorkspaceID,
		&i.ToolCallID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.UpstreamSessionID,
		&i.Status,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.TerminatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeletedConversationsForCleanup = `-- name: ListDeletedConversationsForCleanup :many
SELECT files_cleaned_at, id, enterprise_id, owner_user_id, title, selected_model_id, context_revision, event_sequence, status, version, created_at, updated_at FROM conversations c WHERE status='deleted' AND files_cleaned_at IS NULL
AND NOT EXISTS(SELECT 1 FROM workspaces w WHERE w.conversation_id=c.id AND w.status<>'deleted') LIMIT $1
`

func (q *Queries) ListDeletedConversationsForCleanup(ctx context.Context, limit int32) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listDeletedConversationsForCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.FilesCleanedAt,
			&i.ID,
			&i.EnterpriseID,
			&i.OwnerUserID,
			&i.Title,
			&i.SelectedModelID,
			&i.ContextRevision,
			&i.EventSequence,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletingWorkspaces = `-- name: ListDeletingWorkspaces :many
SELECT id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at FROM workspaces WHERE status='deleting' AND (lease_until IS NULL OR lease_until<now()) ORDER BY updated_at LIMIT $1
`

func (q *Queries) ListDeletingWorkspaces(ctx context.Context, limit int32) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listDeletingWorkspaces, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeUid,
			&i.EnterpriseID,
			&i.ConversationID,
			&i.Status,
			&i.PvcName,
			&i.Namespace,
			&i.CapacityBytes,
			&i.EnvironmentVersion,
			&i.SourceResultRefs,
			&i.ActivePodName,
			&i.ActiveSandboxID,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.FenceToken,
			&i.Version,
			&i.LastUsedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceSandboxSessions = `-- name: ListWorkspaceSandboxSessions :many
SELECT id, enterprise_id, task_id, workspace_id, tool_call_id, profile_id, profile_revision, upstream_session_id, status, expires_at, started_at, terminated_at, created_at, updated_at FROM sandbox_sessions WHERE workspace_id=$1 AND enterprise_id=$2 AND status NOT IN ('terminated','failed')
`

type ListWorkspaceSandboxSessionsParams struct {
	WorkspaceID  uuid.NullUUID `json:"workspace_id"`
	EnterpriseID uuid.UUID     `json:"enterprise_id"`
}

func (q *Queries) ListWorkspaceSandboxSessions(ctx context.Context, arg ListWorkspaceSandboxSessionsParams) ([]SandboxSession, error) {
	rows, err := q.db.Query(ctx, listWorkspaceSandboxSessions, arg.WorkspaceID, arg.EnterpriseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SandboxSession{}
	for rows.Next() {
		var i SandboxSession
		if err := rows.Scan(
			&i.ID,
			&i.EnterpriseID,
			&i.TaskID,
			&i.WorkspaceID,
			&i.ToolCallID,
			&i.ProfileID,
			&i.ProfileRevision,
			&i.UpstreamSessionID,
			&i.Status,
			&i.ExpiresAt,
			&i.StartedAt,
			&i.TerminatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationDeleted = `-- name: MarkConversationDeleted :one
UPDATE conversations SET status='deleted',version=version+1,updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND owner_user_id=$3 RETURNING files_cleaned_at, id, enterprise_id, owner_user_id, title, selected_model_id, context_revision, event_sequence, status, version, created_at, updated_at
`

type MarkConversationDeletedParams struct {
	ID           uuid.UUID `json:"id"`
	EnterpriseID uuid.UUID `json:"enterprise_id"`
	OwnerUserID  uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) MarkConversationDeleted(ctx context.Context, arg MarkConversationDeletedParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, markConversationDeleted, arg.ID, arg.EnterpriseID, arg.OwnerUserID)
	var i Conversation
	err := row.Scan(
		&i.FilesCleanedAt,
		&i.ID,
		&i.EnterpriseID,
		&i.OwnerUserID,
		&i.Title,
		&i.SelectedModelID,
		&i.ContextRevision,
		&i.EventSequence,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markConversationWorkspacesDeleting = `-- name: MarkConversationWorkspacesDeleting :exec
UPDATE workspaces SET status='deleting',version=version+1,updated_at=now()
WHERE conversation_id=$1 AND enterprise_id=$2 AND status NOT IN ('deleted','deleting')
`

type MarkConversationWorkspacesDeletingParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	EnterpriseID   uuid.UUID `json:"enterprise_id"`
}

func (q *Queries) MarkConversationWorkspacesDeleting(ctx context.Context, arg MarkConversationWorkspacesDeletingParams) error {
	_, err := q.db.Exec(ctx, markConversationWorkspacesDeleting, arg.ConversationID, arg.EnterpriseID)
	return err
}

const registerWorkspaceSource = `-- name: RegisterWorkspaceSource :one
UPDATE workspaces SET source_result_refs=ARRAY(SELECT DISTINCT unnest(array_append(source_result_refs,$5::text)) ORDER BY 1)
WHERE id=$1 AND enterprise_id=$2 AND lease_owner=$3 AND fence_token=$4 AND lease_until>now() AND status='ready'
RETURNING id, runtime_uid, enterprise_id, conversation_id, status, pvc_name, namespace, capacity_bytes, environment_version, source_result_refs, active_pod_name, active_sandbox_id, lease_owner, lease_until, fence_token, version, last_used_at, deleted_at, created_at, updated_at
`

type RegisterWorkspaceSourceParams struct {
	ID           uuid.UUID   `json:"id"`
	EnterpriseID uuid.UUID   `json:"enterprise_id"`
	LeaseOwner   pgtype.Text `json:"lease_owner"`
	FenceToken   int64       `json:"fence_token"`
	ResultRef    string      `json:"result_ref"`
}

func (q *Queries) RegisterWorkspaceSource(ctx context.Context, arg RegisterWorkspaceSourceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, registerWorkspaceSource,
		arg.ID,
		arg.EnterpriseID,
		arg.LeaseOwner,
		arg.FenceToken,
		arg.ResultRef,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.RuntimeUid,
		&i.EnterpriseID,
		&i.ConversationID,
		&i.Status,
		&i.PvcName,
		&i.Namespace,
		&i.CapacityBytes,
		&i.EnvironmentVersion,
		&i.SourceResultRefs,
		&i.ActivePodName,
		&i.ActiveSandboxID,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.FenceToken,
		&i.Version,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWorkspaceSandboxUpstream = `-- name: SetWorkspaceSandboxUpstream :one
UPDATE sandbox_sessions SET upstream_session_id=$3,status='running',started_at=now(),updated_at=now()
WHERE id=$1 AND enterprise_id=$2 AND status='creating' RETURNING id, enterprise_id, task_id, workspace_id, tool_call_id, profile_id, profile_revision, upstream_session_id, status, expires_at, started_at, terminated_at, created_at, updated_at
`

type SetWorkspaceSandboxUpstreamParams struct {
	ID                uuid.UUID `json:"id"`
	EnterpriseID      uuid.UUID `json:"enterprise_id"`
	UpstreamSessionID string    `json:"upstream_session_id"`
}

func (q *Queries) SetWorkspaceSandboxUpstream(ctx context.Context, arg SetWorkspaceSandboxUpstreamParams) (SandboxSession, error) {
	row := q.db.QueryRow(ctx, setWorkspaceSandboxUpstream, arg.ID, arg.EnterpriseID, arg.UpstreamSessionID)
	var i SandboxSession
	err := row.Scan(
		&i.ID,
		&i.EnterpriseID,
		&i.TaskID,
		&i.WorkspaceID,
		&i.ToolCallID,
		&i.ProfileID,
		&i.ProfileRevision,
		&i.UpstreamSessionID,
		&i.Status,
		&i.ExpiresAt,
		&i.StartedAt,
		&i.TerminatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
