// sqlc-split keeps generated Go files below the repository's 2000-line limit.
// Run after sqlc generation; it has no dependency on the generated package.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/imports"
)

const marker = "// Code generated by sqlc and scripts/sqlc-split. DO NOT EDIT.\n"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() error {
	directory := filepath.Join("internal", "storage", "postgres", "db")
	files, err := filepath.Glob(filepath.Join(directory, "*.go"))
	if err != nil {
		return err
	}
	// Only remove this generator's own prior parts. Canonical sqlc regeneration
	// recreates the complete original files before this program runs.
	for _, file := range files {
		if strings.Contains(filepath.Base(file), "_part") {
			base := file[:strings.LastIndex(file, "_part")] + ".go"
			original, readErr := os.ReadFile(base)
			if readErr != nil && !os.IsNotExist(readErr) {
				return readErr
			}
			if bytes.HasPrefix(original, []byte(marker)) {
				continue
			}
			data, err := os.ReadFile(file)
			if err != nil {
				return err
			}
			if !bytes.HasPrefix(data, []byte(marker)) {
				return fmt.Errorf("refusing unknown generated part %s", file)
			}
			if err := os.Remove(file); err != nil {
				return err
			}
		}
	}
	for _, file := range files {
		if strings.Contains(filepath.Base(file), "_part") {
			continue
		}
		data, err := os.ReadFile(file)
		if err != nil {
			return err
		}
		if bytes.Count(data, []byte("\n")) <= 1900 {
			continue
		}
		if !bytes.Contains(data[:min(len(data), 200)], []byte("Code generated by sqlc")) {
			continue
		}
		if err := split(file, data); err != nil {
			return err
		}
	}
	return nil
}
func split(filename string, data []byte) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, data, parser.ParseComments)
	if err != nil {
		return err
	}
	offsets := fset.File(file.Pos())
	prefix := marker + "package " + file.Name.Name + "\n\n"
	for _, decl := range file.Decls {
		if group, ok := decl.(*ast.GenDecl); ok && group.Tok == token.IMPORT {
			prefix += string(data[offsets.Offset(decl.Pos()):offsets.Offset(decl.End())]) + "\n"
		}
	}
	chunks := []string{}
	chunk := ""
	lines := 0
	for _, decl := range file.Decls {
		if group, ok := decl.(*ast.GenDecl); ok && group.Tok == token.IMPORT {
			continue
		}
		start := decl.Pos()
		switch decl := decl.(type) {
		case *ast.GenDecl:
			if decl.Doc != nil {
				start = decl.Doc.Pos()
			}
		case *ast.FuncDecl:
			if decl.Doc != nil {
				start = decl.Doc.Pos()
			}
		}
		source := string(data[offsets.Offset(start):offsets.Offset(decl.End())]) + "\n\n"
		count := strings.Count(source, "\n")
		if count > 1800 {
			return fmt.Errorf("single generated declaration exceeds limit: %s", filename)
		}
		if lines+count > 1800 && chunk != "" {
			chunks = append(chunks, chunk)
			chunk = ""
			lines = 0
		}
		chunk += source
		lines += count
	}
	if chunk != "" {
		chunks = append(chunks, chunk)
	}
	for index, chunk := range chunks {
		name := filename
		if index > 0 {
			name = strings.TrimSuffix(filename, ".go") + fmt.Sprintf("_part%02d.go", index+1)
		}
		formatted, err := imports.Process(name, []byte(prefix+chunk), nil)
		if err != nil {
			return err
		}
		if bytes.Count(formatted, []byte("\n")) > 2000 {
			return fmt.Errorf("generated chunk too large: %s", name)
		}
		if err := os.WriteFile(name, formatted, 0644); err != nil {
			return err
		}
	}
	return nil
}
