package toolgateway

import "github.com/kakj-go/Argus/internal/mcp"

// Business documentation belongs to the same package as each native handler.
// Unknown registrations remain empty and fail Gateway startup validation.
var resourceDiscovery = map[string]mcp.Discovery{
	"host.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出主机 / List hosts",
		Description:       "查看当前企业内有权访问的主机清单与连接状态，不修改资源。 List authorized host resources and their connection status without mutation.",
		Keywords:          []string{"主机", "列表", "清单", "查询", "查看", "list", "inventory", "status", "host"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"需要对应读取权限，资源授权在查询时重新检查。 Requires read permission and current resource authorization."},
		Examples:          []mcp.DiscoveryExample{{Request: "有哪些主机？ / Which host resources are available?", Guidance: "使用空参数对象 {} 查询清单，再从返回结果选择真实 ID。 Invoke with {} and select actual IDs from the result."}},
	},
	"host.get": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "查看主机详情 / Get host",
		Description:       "读取单个主机的当前配置、状态和版本，为后续操作提供真实前件。 Read the current configuration, status and version of one host.",
		Keywords:          []string{"主机", "详情", "状态", "查看", "查询", "detail", "inspect", "get", "host"},
		ResultDescription: "返回当前资源详情和版本；不存在或无权访问时返回受控错误。 Returns current resource details and version, or a controlled unavailable/forbidden error.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看所选主机的详情。 / Inspect the selected host.", Guidance: "先列出资源，再把返回的 ID 填入 host_id。 List resources first, then use its returned ID."}},
	},
	"kubernetes.cluster.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出Kubernetes 集群 / List Kubernetes clusters",
		Description:       "查看当前企业内有权访问的Kubernetes 集群清单与连接状态，不修改资源。 List authorized Kubernetes cluster resources and their connection status without mutation.",
		Keywords:          []string{"Kubernetes 集群", "列表", "清单", "查询", "查看", "list", "inventory", "status", "Kubernetes cluster"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"需要对应读取权限，资源授权在查询时重新检查。 Requires read permission and current resource authorization."},
		Examples:          []mcp.DiscoveryExample{{Request: "有哪些Kubernetes 集群？ / Which Kubernetes cluster resources are available?", Guidance: "使用空参数对象 {} 查询清单，再从返回结果选择真实 ID。 Invoke with {} and select actual IDs from the result."}},
	},
	"kubernetes.cluster.get": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "查看Kubernetes 集群详情 / Get Kubernetes cluster",
		Description:       "读取单个Kubernetes 集群的当前配置、状态和版本，为后续操作提供真实前件。 Read the current configuration, status and version of one Kubernetes cluster.",
		Keywords:          []string{"Kubernetes 集群", "详情", "状态", "查看", "查询", "detail", "inspect", "get", "Kubernetes cluster"},
		ResultDescription: "返回当前资源详情和版本；不存在或无权访问时返回受控错误。 Returns current resource details and version, or a controlled unavailable/forbidden error.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看所选Kubernetes 集群的详情。 / Inspect the selected Kubernetes cluster.", Guidance: "先列出资源，再把返回的 ID 填入 cluster_id。 List resources first, then use its returned ID."}},
	},
	"connector.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出Connector 连接代理 / List Connectors",
		Description:       "查看当前企业内有权访问的Connector 连接代理清单与连接状态，不修改资源。 List authorized Connector resources and their connection status without mutation.",
		Keywords:          []string{"Connector 连接代理", "列表", "清单", "查询", "查看", "list", "inventory", "status", "Connector"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"需要对应读取权限，资源授权在查询时重新检查。 Requires read permission and current resource authorization."},
		Examples:          []mcp.DiscoveryExample{{Request: "有哪些Connector 连接代理？ / Which Connector resources are available?", Guidance: "使用空参数对象 {} 查询清单，再从返回结果选择真实 ID。 Invoke with {} and select actual IDs from the result."}},
	},
	"connector.get": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "查看Connector 连接代理详情 / Get Connector",
		Description:       "读取单个Connector 连接代理的当前配置、状态和版本，为后续操作提供真实前件。 Read the current configuration, status and version of one Connector.",
		Keywords:          []string{"Connector 连接代理", "详情", "状态", "查看", "查询", "detail", "inspect", "get", "Connector"},
		ResultDescription: "返回当前资源详情和版本；不存在或无权访问时返回受控错误。 Returns current resource details and version, or a controlled unavailable/forbidden error.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看所选Connector 连接代理的详情。 / Inspect the selected Connector.", Guidance: "先列出资源，再把返回的 ID 填入 connector_id。 List resources first, then use its returned ID."}},
	},
	"host.create.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "创建主机预览 / Preview create host",
		Description:       "创建主机前先生成影响范围。 根据已确认的连接方式和配置接入新资源；不会凭空分配凭据或替用户提交。 Preview onboarding from confirmed connection settings; do not invent credentials.",
		Keywords:          []string{"新增主机", "添加主机", "新建主机", "接入主机", "主机", "创建", "创建主机", "新增", "添加", "接入", "create", "preview", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请创建指定的主机，先给我预览。 / Preview create for the selected host.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"host.update.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "更新主机预览 / Preview update host",
		Description:       "更新主机前先生成影响范围。 先读取资源和当前版本，再预览配置修改。 Read the current resource/version before previewing a configuration update.",
		Keywords:          []string{"修改主机", "编辑主机", "主机", "更新", "更新主机", "修改", "编辑", "update", "preview", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请更新指定的主机，先给我预览。 / Preview update for the selected host.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"host.delete.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "删除主机预览 / Preview delete host",
		Description:       "删除主机前先生成影响范围。 预览移除控制面资源记录；主机卸载应使用 removal 预览。 Preview removal of the resource record; use host removal for uninstalling host components.",
		Keywords:          []string{"移除主机", "注销主机", "主机", "删除", "删除主机", "移除", "注销", "delete", "preview", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请删除指定的主机，先给我预览。 / Preview delete for the selected host.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"kubernetes.cluster.create.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "创建Kubernetes 集群预览 / Preview create Kubernetes cluster",
		Description:       "创建Kubernetes 集群前先生成影响范围。 根据已确认的连接方式和配置接入新资源；不会凭空分配凭据或替用户提交。 Preview onboarding from confirmed connection settings; do not invent credentials.",
		Keywords:          []string{"创建集群", "新增集群", "添加集群", "接入集群", "Kubernetes 集群", "创建", "创建Kubernetes 集群", "新增", "添加", "接入", "create", "preview", "Kubernetes cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请创建指定的Kubernetes 集群，先给我预览。 / Preview create for the selected Kubernetes cluster.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"kubernetes.cluster.update.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "更新Kubernetes 集群预览 / Preview update Kubernetes cluster",
		Description:       "更新Kubernetes 集群前先生成影响范围。 先读取资源和当前版本，再预览配置修改。 Read the current resource/version before previewing a configuration update.",
		Keywords:          []string{"更新集群", "修改集群", "Kubernetes 集群", "更新", "更新Kubernetes 集群", "修改", "编辑", "update", "preview", "Kubernetes cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请更新指定的Kubernetes 集群，先给我预览。 / Preview update for the selected Kubernetes cluster.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"kubernetes.cluster.delete.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "删除Kubernetes 集群预览 / Preview delete Kubernetes cluster",
		Description:       "删除Kubernetes 集群前先生成影响范围。 预览移除控制面资源记录；主机卸载应使用 removal 预览。 Preview removal of the resource record; use host removal for uninstalling host components.",
		Keywords:          []string{"删除集群", "移除集群", "Kubernetes 集群", "删除", "删除Kubernetes 集群", "移除", "注销", "delete", "preview", "Kubernetes cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results. 新增资源前收集所有必填连接字段。 Collect required connection fields before creating resources."},
		Examples:          []mcp.DiscoveryExample{{Request: "请删除指定的Kubernetes 集群，先给我预览。 / Preview delete for the selected Kubernetes cluster.", Guidance: "先 Describe 读取输入 Schema，再使用已确认参数；把确认交给宿主控件。 Read the input schema, use confirmed settings, and leave confirmation to the host."}},
	},
	"kubernetes.namespace.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 命名空间 / List namespaces",
		Description:       "查询指定集群中的命名空间，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query namespace resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "命名空间", "namespace", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的命名空间。 / List namespace resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.node.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 节点 / List nodes",
		Description:       "查询指定集群中的节点，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query node resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "节点", "node", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的节点。 / List node resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.pod.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 容器组 / List pods",
		Description:       "查询指定集群中的容器组，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query pod resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "容器组", "pod", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的容器组。 / List pod resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.deployment.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 无状态工作负载 / List deployments",
		Description:       "查询指定集群中的无状态工作负载，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query deployment resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "无状态工作负载", "deployment", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的无状态工作负载。 / List deployment resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.statefulset.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 有状态工作负载 / List statefulsets",
		Description:       "查询指定集群中的有状态工作负载，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query statefulset resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "有状态工作负载", "statefulset", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的有状态工作负载。 / List statefulset resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.daemonset.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 守护进程集 / List daemonsets",
		Description:       "查询指定集群中的守护进程集，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query daemonset resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "守护进程集", "daemonset", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的守护进程集。 / List daemonset resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.service.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出 Kubernetes 服务 / List services",
		Description:       "查询指定集群中的服务，可按 query/limit 限制结果；命名空间资源需要 namespace。 Query service resources in a selected cluster with bounded query/limit; namespaced resources require namespace.",
		Keywords:          []string{"Kubernetes", "k8s", "集群", "服务", "service", "列表", "清单", "查询", "list", "inventory"},
		ResultDescription: "仅返回当前主体获授权的资源；空列表表示无可见数据。 Returns only authorized resources; an empty list means no visible data.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看集群的服务。 / List service resources.", Guidance: "先查询 cluster.list 得到 cluster_id；对命名空间资源显式提供 namespace。 Obtain cluster_id from cluster.list and provide namespace when required."}},
	},
	"kubernetes.pod.logs": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "读取 Pod 容器日志 / Read pod logs",
		Description:       "读取指定 Pod/容器的最近日志行，支持 tail_lines 限制；用于排查当前容器故障。 Read recent log lines from a selected pod/container for troubleshooting.",
		Keywords:          []string{"Kubernetes", "k8s", "pod", "容器", "日志", "日志排查", "logs", "container", "troubleshoot"},
		ResultDescription: "返回有界日志文本；不会订阅实时流或更改 Pod。 Returns bounded log text without subscribing to a live stream or changing the pod.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "查看这个 Pod 的最近日志。 / Show recent logs for this pod.", Guidance: "提供实际 cluster_id、namespace、pod，按需指定 container 和 tail_lines。 Use actual cluster_id, namespace and pod; optionally set container and tail_lines."}},
	},
	"pending_action.list": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "列出待确认操作 / List pending actions",
		Description:       "查询本企业可见的待确认操作清单，不执行或确认操作。 List visible pending actions without executing or confirming them.",
		Keywords:          []string{"待确认", "待办", "操作", "列表", "pending", "actions", "list"},
		ResultDescription: "返回公开操作数据或取消后的状态，不包含私有提交 Token。 Returns public action data or cancellation state without private commit tokens.",
		Preconditions:     []string{"仅使用服务端返回的 action_ref，取消必须符合当前状态。 Use only server-issued action_ref values and respect the current cancellation state."},
		Examples:          []mcp.DiscoveryExample{{Request: "请查看待确认操作。 / Inspect pending actions.", Guidance: "list 使用 {}；get/cancel 使用返回的 action_ref。 Use {} for list, and a returned action_ref for get/cancel."}},
	},
	"pending_action.get": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "查看操作状态 / Get action status",
		Description:       "读取指定公开 action_ref 的预览、审批及执行状态。 Read preview, approval and execution state for a public action reference.",
		Keywords:          []string{"操作", "确认状态", "审批", "执行状态", "详情", "action", "status", "approval", "get"},
		ResultDescription: "返回公开操作数据或取消后的状态，不包含私有提交 Token。 Returns public action data or cancellation state without private commit tokens.",
		Preconditions:     []string{"仅使用服务端返回的 action_ref，取消必须符合当前状态。 Use only server-issued action_ref values and respect the current cancellation state."},
		Examples:          []mcp.DiscoveryExample{{Request: "请查看待确认操作。 / Inspect pending actions.", Guidance: "list 使用 {}；get/cancel 使用返回的 action_ref。 Use {} for list, and a returned action_ref for get/cancel."}},
	},
	"pending_action.cancel": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "取消待确认操作 / Cancel pending action",
		Description:       "取消指定尚可取消的待确认操作；不会撤销已发生的业务变更。 Cancel a cancellable pending action; this does not undo an executed business change.",
		Keywords:          []string{"取消", "撤销待办", "待确认", "操作", "cancel", "pending"},
		ResultDescription: "返回公开操作数据或取消后的状态，不包含私有提交 Token。 Returns public action data or cancellation state without private commit tokens.",
		Preconditions:     []string{"仅使用服务端返回的 action_ref，取消必须符合当前状态。 Use only server-issued action_ref values and respect the current cancellation state."},
		Examples:          []mcp.DiscoveryExample{{Request: "请取消这项待确认操作。 / Cancel this pending action.", Guidance: "list 使用 {}；get/cancel 使用返回的 action_ref。 Use {} for list, and a returned action_ref for get/cancel."}},
	},
	"host.install.retry.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "重试主机安装 / Retry host installation",
		Description:       "重试已有主机的失败安装流程。 Retry a failed host installation.",
		Keywords:          []string{"主机", "安装", "重试", "重装", "host", "install", "retry"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "重试主机安装 / Retry host installation，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 host_id 和完整连接配置 / host_id and complete connection settings，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"host.removal.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "卸载主机组件 / Remove host components",
		Description:       "预览卸载受管主机或其安装组件，按 removal mode 明确影响。 Preview removal of managed host components according to the chosen removal mode.",
		Keywords:          []string{"主机", "卸载", "清理", "移除", "host", "removal", "uninstall"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "卸载主机组件 / Remove host components，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 target_type、target_id、mode 和当前 expected_version / target type, ID, mode and current version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"host.windows_rdp.enable.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "启用 Windows 远程桌面 / Enable Windows RDP",
		Description:       "预览在目标 Windows 主机启用远程桌面访问配置。 Preview enabling Remote Desktop on a Windows host.",
		Keywords:          []string{"主机", "windows", "远程桌面", "开启远程桌面", "启用", "rdp", "enable"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "启用 Windows 远程桌面 / Enable Windows RDP，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 host_id 和当前 expected_version / host_id and current expected_version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.bastion.create.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "创建堡垒机范围 / Create bastion scope",
		Description:       "预览创建堡垒机管理范围及其连接配置。 Preview a new bastion management scope and connection configuration.",
		Keywords:          []string{"堡垒机", "跳板机", "创建", "新增", "bastion", "create"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "创建堡垒机范围 / Create bastion scope，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 已确认的名称、环境和安装方式 / confirmed name, environment and installation mode，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.bastion.update.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "修改堡垒机范围 / Update bastion scope",
		Description:       "预览更新现有堡垒机范围的公开配置。 Preview changes to an existing bastion scope.",
		Keywords:          []string{"堡垒机", "跳板机", "修改", "更新", "bastion", "update"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "修改堡垒机范围 / Update bastion scope，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 scope_id、expected_version 和目标配置 / scope ID, current version and desired settings，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.bastion.delete.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "删除堡垒机范围 / Delete bastion scope",
		Description:       "预览删除指定堡垒机范围及其影响。 Preview deletion of a bastion scope and its impact.",
		Keywords:          []string{"堡垒机", "跳板机", "删除", "移除", "bastion", "delete"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "删除堡垒机范围 / Delete bastion scope，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 scope_id 和当前 expected_version / scope ID and current version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.bastion.enrollment_rotate.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "轮换堡垒机注册凭据 / Rotate bastion enrollment",
		Description:       "预览轮换指定堡垒机的接入注册材料，不返回凭据正文。 Preview rotating bastion enrollment material without exposing credential values.",
		Keywords:          []string{"堡垒机", "注册", "轮换", "接入凭据", "bastion", "enrollment", "rotate"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "轮换堡垒机注册凭据 / Rotate bastion enrollment，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 scope_id 和当前 expected_version / scope ID and current version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.bastion.replacement.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "替换堡垒机代理 / Replace bastion connector",
		Description:       "预览由新的 Connector 接管已有堡垒机范围。 Preview replacement of the connector serving a bastion scope.",
		Keywords:          []string{"堡垒机", "代理", "替换", "接管", "bastion", "replacement", "takeover"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "替换堡垒机代理 / Replace bastion connector，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 scope_id、expected_version 和新代理安装配置 / scope, version and replacement installation settings，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.install.retry.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "重试代理安装 / Retry connector installation",
		Description:       "预览重试已有失败的 Connector 安装操作。 Preview retrying a failed connector installation operation.",
		Keywords:          []string{"连接代理", "安装", "重试", "connector", "install", "retry"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "重试代理安装 / Retry connector installation，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 真实 operation_id / actual operation_id，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"connector.uninstall.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "卸载连接代理 / Uninstall connector",
		Description:       "预览从目标环境卸载 Connector，显示受影响的连接能力。 Preview uninstalling a connector and its affected connectivity.",
		Keywords:          []string{"连接代理", "代理", "卸载", "移除", "connector", "uninstall"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "卸载连接代理 / Uninstall connector，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 connector_id 和当前 expected_version / connector ID and current version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"kubernetes.node_host_binding.confirm.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "确认节点主机绑定 / Confirm node host binding",
		Description:       "预览确认 Kubernetes 节点与受管主机的物理身份绑定。 Preview confirmation of a Kubernetes node to managed host identity binding.",
		Keywords:          []string{"节点", "主机", "绑定", "确认绑定", "node", "host", "binding"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "确认节点主机绑定 / Confirm node host binding，先展示影响范围。 / Show the impact before execution.", Guidance: "先取得 binding_id、host_id 和当前 expected_version / binding ID, host ID and current version，再生成 Preview；不要替用户确认。 Obtain these parameters and generate a preview; do not confirm for the user."}},
	},
	"host.collector.install.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "安装主机采集器 / Install host collector",
		Description:       "预览在主机上安装遥测采集器及其采集链路。 Preview install of the telemetry collector and its collection route on a host.",
		Keywords:          []string{"主机", "采集器", "遥测", "安装", "部署", "collector", "install", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请安装这个主机的采集器。 / Install this host collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"host.collector.configure.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "配置主机采集器 / Configure host collector",
		Description:       "预览在主机上配置遥测采集器及其采集链路。 Preview configure of the telemetry collector and its collection route on a host.",
		Keywords:          []string{"主机", "采集器", "遥测", "配置", "调整配置", "collector", "configure", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请配置这个主机的采集器。 / Configure this host collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"host.collector.upgrade.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "升级主机采集器 / Upgrade host collector",
		Description:       "预览在主机上升级遥测采集器及其采集链路。 Preview upgrade of the telemetry collector and its collection route on a host.",
		Keywords:          []string{"主机", "采集器", "遥测", "升级", "更新版本", "collector", "upgrade", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请升级这个主机的采集器。 / Upgrade this host collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"host.collector.repair.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "修复主机采集器 / Repair host collector",
		Description:       "预览在主机上修复遥测采集器及其采集链路。 Preview repair of the telemetry collector and its collection route on a host.",
		Keywords:          []string{"主机", "采集器", "遥测", "修复", "修理", "collector", "repair", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请修复这个主机的采集器。 / Repair this host collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"host.collector.uninstall.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "卸载主机采集器 / Uninstall host collector",
		Description:       "预览在主机上卸载遥测采集器及其采集链路。 Preview uninstall of the telemetry collector and its collection route on a host.",
		Keywords:          []string{"主机", "采集器", "遥测", "卸载", "移除采集器", "collector", "uninstall", "host"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请卸载这个主机的采集器。 / Uninstall this host collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"kubernetes.collector.install.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "安装集群采集器 / Install cluster collector",
		Description:       "预览在集群上安装遥测采集器及其采集链路。 Preview install of the telemetry collector and its collection route on a cluster.",
		Keywords:          []string{"集群", "采集器", "遥测", "安装", "部署", "collector", "install", "cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请安装这个集群的采集器。 / Install this cluster collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"kubernetes.collector.configure.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "配置集群采集器 / Configure cluster collector",
		Description:       "预览在集群上配置遥测采集器及其采集链路。 Preview configure of the telemetry collector and its collection route on a cluster.",
		Keywords:          []string{"集群", "采集器", "遥测", "配置", "调整配置", "collector", "configure", "cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请配置这个集群的采集器。 / Configure this cluster collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"kubernetes.collector.upgrade.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "升级集群采集器 / Upgrade cluster collector",
		Description:       "预览在集群上升级遥测采集器及其采集链路。 Preview upgrade of the telemetry collector and its collection route on a cluster.",
		Keywords:          []string{"集群", "采集器", "遥测", "升级", "更新版本", "collector", "upgrade", "cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请升级这个集群的采集器。 / Upgrade this cluster collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"kubernetes.collector.repair.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "修复集群采集器 / Repair cluster collector",
		Description:       "预览在集群上修复遥测采集器及其采集链路。 Preview repair of the telemetry collector and its collection route on a cluster.",
		Keywords:          []string{"集群", "采集器", "遥测", "修复", "修理", "collector", "repair", "cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请修复这个集群的采集器。 / Repair this cluster collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
	"kubernetes.collector.uninstall.preview": {
		SchemaVersion:     "argus.tool_discovery/v1",
		Revision:          "1",
		Title:             "卸载集群采集器 / Uninstall cluster collector",
		Description:       "预览在集群上卸载遥测采集器及其采集链路。 Preview uninstall of the telemetry collector and its collection route on a cluster.",
		Keywords:          []string{"集群", "采集器", "遥测", "卸载", "移除采集器", "collector", "uninstall", "cluster"},
		ResultDescription: "返回公开影响范围、待确认 action_ref 和预览状态；实际变更由宿主确认及审批后确定性执行。 Returns a public preview and pending action reference; execution requires host confirmation and applicable approval.",
		Preconditions:     []string{"使用查询结果中的真实资源 ID 和当前版本，不从示例或历史摘要猜测。 Use actual resource IDs and current versions from query results."},
		Examples:          []mcp.DiscoveryExample{{Request: "请卸载这个集群的采集器。 / Uninstall this cluster collector.", Guidance: "从当前资源获取目标 ID，使用已发布 distribution_version_id、profile_ids 和合法 route_kind/transport。 Use a current target ID, published distribution version/profiles and supported route/transport."}},
	},
}
